### ISSUE TITLE
Create user after upgrade

### ISSUE THREAD

**Issue by miquelangeld** [BRACKETS-by-TRIAD/craftable#100]
When I try to create a new user using tinker I get this error
PHP Error:  Class 'Brackets/AdminAuth/Models/User' not found in /var/www/jves/vendor/laravel/framework/src/Illuminate/Database/Eloquent/FactoryBuilder.php on line 291
 I created new user directly in DB but I get unauthorized exceptions when I try to access to any of the cruds.

**Comment by miquelangeld** [comment]
By the way, that happen after upgrade to v3

**Comment by dejwCake** [comment]
Hello, the reason could be that class 'Brackets/AdminAuth/Models/User' really does not exists, we have    'Brackets/AdminAuth/Models/AdminUser' class, used for administration login. However, if you upgraded from v2 to v3, probably you need to use App/Models/User, it depends on your use case and on guards defined in config. 

The user created in DB does not have role and therefore he does not have permissions. You can attach this over tinker. But also roles and permissions are based on guards.
