### ISSUE TITLE
Flash of ugly form

### ISSUE THREAD

**Issue by matejminar** [BRACKETS-by-TRIAD/craftable#101]
Every time we go to edit page, there is a flash of ugly form for a split second (see attachment).

Maybe we could fix this using something like v-cloak which would hide the form while page is loading.

<img width="1429" alt="Screenshot 2019-05-07 at 17 37 14 (2)" src="https://user-images.githubusercontent.com/9060071/57317225-eacc4780-70f7-11e9-8b2e-f7ddb1aa74dc.png">

**Comment by xDefcon** [comment]
Can confirm this also happens to me most of the times.

**Comment by RichardDominik** [comment]
Fixed in new version of Craftable https://github.com/BRACKETS-by-TRIAD/craftable/releases/tag/v3.1.0
