### ISSUE TITLE
override page_title_suffix

### ISSUE THREAD

**Issue by jmendozaf** [BRACKETS-by-TRIAD/craftable#103]
I need to override or ovoid the 'Craftable' page_title_suffix for all the views. The laravel APP_NAME wasn't 'Laravel' at 'php artisan craftable:install' time. I've managed to create or orverride some layouts views like master.blade.php and default.blade.php, but I couldn't do it for the home, translations or admin auth views.

**Comment by palypster** [comment]
Hey, check out https://laravel.com/docs/5.8/packages#views and `Overriding Package Views` section. It should do the trick.
