### ISSUE TITLE
is there a way to rollback menu creation or recreate it using admin:generate?

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#104]
The problem I am having that after the menu is creating using:
```
php artisan admin:generate table_name
```

and I need to recreate it or delete it to create it again... because something was missing etc... and I ended up having lot of menus...

my question:
Is there a way to delete or rollback the menu creation with craftable?

I did not find anything regarding this topic...
can anyone tell me how to do this?
thanks a lot!

**Comment by palypster** [comment]
you can update the menu on your own in  `resources/views/admin/layout/sidebar.blade.php`
