### ISSUE TITLE
any chance craftable can also work with MySQL 5.6 database?

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#109]
I know the requirements say mysql 5.7+ but in my case I am working locally for this reason and I wanted to put my code online but all hosting companies does not offer mysql 5.7 or above at the moment... 

is there any solution to use craftable also on my server online or must continue using it locally until hosting companies upgrade mysql versions?

any ideas or solutions? I do not own a dedicated server!
thanks

**Comment by palypster** [comment]
Hey,

sorry, we at BRACKETS  don't use MySQL at all  (we use PostgreSQL), so I'm afraid we cannot assist you on this one.

If I remember correctly, I think v5.6 is not sufficient because it does not support JSON data type. It is needed for storing translations.

**Comment by talyosha** [comment]
> I know the requirements say mysql 5.7+ but in my case I am working locally for this reason and I wanted to put my code online but all hosting companies does not offer mysql 5.7 or above at the moment...
> 
> is there any solution to use craftable also on my server online or must continue using it locally until hosting companies upgrade mysql versions?
> 
> any ideas or solutions? I do not own a dedicated server!
> thanks
@rapgithub have you found any solutions for this issue ?
