### ISSUE TITLE
Installation aborted after DB Question on Win10

### ISSUE THREAD

**Issue by Banquo1** [BRACKETS-by-TRIAD/craftable#11]
Hi there, just want to try out craftable (with "craftable new" command) but my installation always abort at the end after the DB system question "What database driver do you use?" ==> "Aborted".
System:Win 10 with php 7.1, MySQL 5.7.14 
![image](https://user-images.githubusercontent.com/5023328/35503138-8970afba-04df-11e8-887f-70fdfcb5f2cd.png)

**Comment by palypster** [comment]
Hi @Banquo1, can you be more specific - it displays the question and you do nothing and it got aborted (immediately)? Or it is waiting on the question and after you hit "return" (so you choose mysql option) then it got aborted? Thanks

**Comment by palypster** [comment]
Can you please attach your `composer` and `craftable` versions? Thank you.

**Comment by Banquo1** [comment]
Hi @palypster , no there is no input from me - just the commad "craftable new testproject". No other input. Tried it serveral times now.
Did some testing on an other L5.5 Project ->the command line  choice command did work there and prompts me with the choices.

Craftable Version 1.0.2
Composer: 1.6.2

**Comment by Banquo1** [comment]
Update: Tried with PowerShell - same result.

if I manually do: "php artisan craftable:init-dev" -  this works for me and i get promted with all db settings.

**Comment by verybigelephants** [comment]
actually, on my windows machine it auto accepts/skips my input during the installation as well :(

![image](https://user-images.githubusercontent.com/3118985/35506416-7a06f64c-04e9-11e8-9767-e2cee4b72554.png)

**Comment by palypster** [comment]
Okay, so this is the _craftable-installer_ issue not _craftable_ itself. It looks that TTY is not supported on Windows platform (Symfony\Component\Process@setTty) and I guess it may cause. Maybe we need to switch to full Illuminate\Console\Command so we may call artisan commands "natively".

As a workaround, instead of running single:
```
craftable new project_name
```
run all the commands manually and it should work:
```
craftable new --no-install project_name
php artisan craftable:init-env
php artisan craftable:install
npm install
npm run dev
```

Can you confirm this workaround works for you?

**Comment by ThiagoLovatine** [comment]
It worked for me, thanks! I use blank password for local database development so if I leave it blank in the wizard it defaults to "secret", and that's because I got this error, but this fixed it for me.
Thank you!

**Comment by Banquo1** [comment]
Can't verify at the moment, because the installation doesn't work at the moment. Some L5.6 dependencies fail:

**brackets/admin-translations v2.0.0 requires illuminate/database 5.5.*:**

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - brackets/craftable v2.0.0 requires brackets/admin-translations ^2.0 -> satisfiable by brackets/admin-translations[v2.0.0].
    - Installation request for brackets/craftable ^2.0 -> satisfiable by brackets/craftable[v2.0.0].
    - Conclusion: remove laravel/framework v5.6.3
    - Conclusion: don't install laravel/framework v5.6.3
    - brackets/admin-translations v2.0.0 requires illuminate/database 5.5.* -> satisfiable by laravel/framework[5.5.x-dev], illuminate/database[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.3].
    - don't install illuminate/database 5.5.x-dev|don't install laravel/framework v5.6.3
    - don't install illuminate/database v5.5.0|don't install laravel/framework v5.6.3
    - don't install illuminate/database v5.5.16|don't install laravel/framework v5.6.3
    - don't install illuminate/database v5.5.17|don't install laravel/framework v5.6.3
    - don't install illuminate/database v5.5.2|don't install laravel/framework v5.6.3
    - don't install illuminate/database v5.5.28|don't install laravel/framework v5.6.3
    - don't install illuminate/database v5.5.33|don't install laravel/framework v5.6.3
    - don't install illuminate/database v5.5.34|don't install laravel/framework v5.6.3
    - Installation request for laravel/framework (locked at v5.6.3, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.3].

**Comment by palypster** [comment]
@Banquo1 what version of craftable installer do you have? `craftable --version`

**Comment by weidmaster** [comment]
@palypster the workaround is still necessary. It works and should be added to the documentation.

**Comment by palypster** [comment]
@RichardDominik please add this https://github.com/BRACKETS-by-TRIAD/craftable/issues/11#issuecomment-361755342 to the docs, so it reaches more people.

**Comment by RichardDominik** [comment]
Information was added to documentation.
