### ISSUE TITLE
Translate Cache

### ISSUE THREAD

**Issue by hungbu** [BRACKETS-by-TRIAD/craftable#110]
I have 2 source:
1. source production
2. source local

On product source: 
The customer entered the translation language data of the template.

When I release new features.
I have released the wrong version.
Then I copy all source (all files in the source) to the source production

And the result admin translate data product is translate data of local.
I try update one row, after save : data translation of production is come back

Please explain the way you save data translation.
I want to know more about it, thanks.

**Comment by palypster** [comment]
1. translations are stored in the database.
1. translations files are only used as the defaults
1. after every release you should call `php artisan admin-translations:scan-and-save`

**Comment by hungbu** [comment]
thanks
