### ISSUE TITLE
Dynamic Dependent dropdown creation how to make it work in Craftable? 

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#111]
I need to create a dynamic dependent dropdown using craftable but it seems not to work inside craftable...

I followed these steps but I always have problems with the js scripts to run...

I wonder where in craftable do I have to put the js script to run without errors?

here the link to the tutorial without craftable:

https://www.webslesson.info/2018/03/ajax-dynamic-dependent-dropdown-in-laravel.html

any ideas how to make this work inside craftable? 

I have only countries and cities where cities are dependent on country selection!

is there a sample of this using craftable? thanks 

any ideas?

**Comment by palypster** [comment]
Related #146
