### ISSUE TITLE
How to display name instead of id for country_id inside index.blade.php using craftable?

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#113]
I have been applying the modifyQuery inside my controller index()... but not working 

I have this tables relationship between places and countries:

```
places->country_id with country->id
```

I want to show in the index.blade.php not the id but the name of the country but still not working :( always show the country_id instead of the name...

In the places model I have

    public function country()
    {
        return $this->belongsTo('App\Models\Country');
    }
    

my places table:

```
id
place_name
country_id
```

my country table:

```
id
country_name
```

here my index.blade.php                 
             
```html
<td>@{{item}}</td> //print the json object displaying all fields
<td>@{{item.country_id}}</td> //print id of the country
```

how in craftable can I show the name of country instead of id in the index.blade.php using item object?

is there any sample of code for the models and the controller to do this?

thanks a lot!

**Comment by palypster** [comment]
Check out our demo and the sources
https://demo.getcraftable.com/admin/articles-with-relationships
