### ISSUE TITLE
index.blade.php display image not rendering data inside handlebars if inside img html tag

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#115]
I am trying to show the image related to the record inside the index.blade.php list but it seems that when using @{{url('/')}}/media/@{{item.cover[0]}}/conversions/thumb_200.jpg inside the img tag it is not rendering the data...

any ideas why?

here the code:

```
<td>
<img src="{{url('/')}}/media/@{{item.cover[0]}}/conversions/thumb_200.jpg">
</td>
```

thanks

**Comment by palypster** [comment]
You shouldn't build the URL to the media yourself. You should use it like in the documentation:
https://docs.spatie.be/laravel-medialibrary/v6/basic-usage/retrieving-media/

**Comment by futurewebsites** [comment]
How do you display an image in your view if for instance I have the path to a remotely stored image in my collection? 

Blade would be <img src="{{$collection->image_url}}"> 

but as above @{{collection.image_url}} doesn't work ?
