### ISSUE TITLE
how to display an image inside index.blade? in my case inside img tag the item data it is not working... 

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#116]
I want to show the media thumbnail of the image uploaded associated with a record but it seems that inside img tag the handlebars is not rendering the data...

```
                                <tr v-for="(item, index) in collection">
                                    <td>@{{ item.id }}</td>
                                    <td>
                                      <img src="{{url('/')}}/media/@{{item.cover[0]}}/conversions/thumb_200.jpg" width="100">
                                    </td>

```

if I use only this it works:

```
{{url('/')}}/media/@{{item.cover[0]}}/conversions/thumb_200.jpg
```

but this does not work:

```
 <img src="{{url('/')}}/media/@{{item.cover[0]}}/conversions/thumb_200.jpg" width="100">
```

**Comment by ShamarKellman** [comment]
Since this package uses Laravel Media library you get the first image url using 
```
$url = $model->getFirstMediaUrl('collection');
```
See more in the docs [https://docs.spatie.be/laravel-medialibrary/v7/basic-usage/retrieving-media/](https://docs.spatie.be/laravel-medialibrary/v7/basic-usage/retrieving-media/)
