### ISSUE TITLE
model translatable : how to avoid the required fields to be required in the other translations languages? 

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#117]
I have a model translatable but in the default language I want the some fields to be required fields but not in the translations yet only if I enter the translation language to enter the data...

I mean I cannot save the model in the default language if I do not complete all the language translations now :(

for me it will be more logic to ask only for the translations required fields in case I switch the language to it... then I will need to fill those fields too but not first...

any ideas?
thanks

**Comment by palypster** [comment]
Hey, I understand that this behaviour does not fit your needs. Unfortunately, this is how Craftable works -  we see the "requireness" of an attribute as a global thing, among all language mutations. There is no direct support for this. You have to override the frontend yourself.

**Comment by palypster** [comment]
@rapgithub

**Comment by palypster** [comment]
Hey @rapgithub, when I re-read your issue, I realized that something similar (but not exactly the same) is already implemented. You can set required attributes per locale:
https://www.getcraftable.com/docs/5.0/translatable#required-locales

Alternatively, you don't have to use `TranslatableFormRequest` at all, and rather define the `rules()` in your own `FormRequest` class. Also, you may edit the javascript to provide the described functionality (attribute being required once the language was switched via drop-down).
