### ISSUE TITLE
403 error after generating crud

### ISSUE THREAD

**Issue by DanielQuirogaDev** [BRACKETS-by-TRIAD/craftable#119]
After i generate crud with craftable every crud except the ones it includes throws 403 error, nothing in log...

**Comment by hungbu** [comment]
you can try:
`app/Models/yourModel.php`
add code:
`protected $table = "youtable";`

-hope to help you-

**Comment by DanielQuirogaDev** [comment]
Yeah! That did it. 

"npm install && npm run dev" and it started working just beautifully :)

Thanks.

What do i need to do in my database so Craftable can read my relationships and create a drop menu?

Thanks :)

**Comment by rapgithub** [comment]
in my case you need to create the relation by yourself! and create the dropdown, can you send the table relation you have?

**Comment by rapgithub** [comment]
inside your form-elements.blade.php

you add a dropdown like this:

```
        <div class="form-group row align-items-center"
             :class="{'has-danger': errors.has('provider_id'), 'has-success': this.fields.provider_id && this.fields.provider_id.valid }">
            <label for="tour_provider_id"
                   class="col-form-label text-center col-md-4 col-lg-3">{{ trans('admin.tour.columns.provider_id') }}</label>
            <div class="col-md-8 col-lg-9">
                <select v-model="form.provider_id" @input="validate($event)" class="form-control" id="provider_id" name="provider_id">
                    @foreach($all_providers as $provider)
                        <option value="{{ $provider->id}}">{{$provider->name}}</option>
                    @endforeach
                </select>

                <div v-if="errors.has('provider_id')" class="form-control-feedback form-text" v-cloak>@{{
                    errors.first('provider_id') }}
                </div>
            </div>
        </div>
```

replace **provider_id** with your field name...

then go to Http/Controllers/Admin/ and edit your model name controller file...

add your other model at the top of the page that needs to be in relation with the present model:

```
use App\Models\Provider;
```


inside function create modify it to look like this:

```
    public function create()
    {
        $this->authorize('admin.tour.create');

        return view('admin.tour.create', [
            'all_providers' => Provider::all(),
            'mode' => 'create',
        ]);

    }

```

and inside function edit modify it to look like this:

```
    public function edit(Tour $tour)
    {
        return view('admin.tour.edit', [
            'all_providers' => Provider::all(),
            'mode' => 'edit',
        ]);

    }

```

then go edit your model inside Models/yourmodelname.php

add the top of the code add:

```
use App\Models\Provider;

```

add at the end this relation:

```
    public function provider()
    {
        return $this->belongsTo(Provider::class);
    }
```

then go Http/Requests/yourmodelfolder

inside the Store....php file

add to your rules your column name at the end of the other fields:

```
    public function rules()
    {
        return [
            'provider_id' => ['required',],            
        ];
    }

```

then go to Resources/js/admin/yourmodelfolder

and inside the Form.js add it there too at the end of the others fields:

```
import AppForm from '../app-components/Form/AppForm';

Vue.component('post-form', {
    mixins: [AppForm],
    data: function() {
        return {
            form: {
                provider_id: '',
                
            },
            mediaCollections: ['cover', 'gallery', 'pdf']
        }
    }

});


```

and that is it! 

remember before all this to create the migration relation for that table, I always create first my tables and then I create only the relations using for instance this migration file for this particular column field I need the relation, for instance below I am adding the provider_id column to my table Place:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class AddProviderIdToPlaceTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::table('places', function (Blueprint $table) {
            $table->unsignedBigInteger('provider_id')->unsigned()->nullable();
            $table->foreign('provider_id')->references('id')->on('providers')->onDelete('cascade');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::table('places', function (Blueprint $table) {
            $table->dropColumn('provider_id');
        });
    }
}
```

Let me know if you could create the relation and the dropdown accordingly!
best regards!
