### ISSUE TITLE
first login issue on fresh installation 

### ISSUE THREAD

**Issue by amritms** [BRACKETS-by-TRIAD/craftable#12]
I freshly installed craftable and head to /admin page. Then it showed me follwing error:

> "The Mix manifest does not exist. (View: craftablecms/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php) (View: craftablecms/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php) (View: craftablecms/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php)

I am using `php artisan serve` for development

**Comment by palypster** [comment]
This says the Laravel Mix was not build -> npm was not run. It should be done automatically via `craftable new project` command. If that failed, it would be inevitable to paste here the output. Or you can try to run it manually `npm run dev`.

**Comment by matejminar** [comment]
this seems to be a laravel-mix's windows specific issue - discussed [here](https://github.com/JeffreyWay/laravel-mix/issues/131)

installing cross-env globally should do the trick:
`npm i -g cross-env`
