### ISSUE TITLE
created a module but blank screen on admin

### ISSUE THREAD

**Issue by hitmc** [BRACKETS-by-TRIAD/craftable#120]
Hi all,

I am new here. Installed Craftable in localhost for a new project. After installation, I created a module following this tutorial - https://blog.brackets.sk/laravel-5-7-crud-tutorial-example-using-craftable/

All went right until I found in admin - the new module index page is not displaying. it shows the table for a millisecond while loading page after loaded it disappears. very weird. manage access and translation tabs are working fine.

any idea why this happens? admin/module/create also acts the same as admin/module page. can't see a thing. just flashing and disappears.

help me

**Comment by hitmc** [comment]
Really sorry "npm install && npm run dev" done the job.

**Comment by hitmc** [comment]
Ticket Solved

**Comment by hitmc** [comment]
Forgot to tell you I have added protected $table = "mode_table_name"; in Model.php in App\Models then "npm install && npm run dev" solved the issue

**Comment by radek3911** [comment]
I had similar issue for me I had to CTRL+F5 to clear cache and also make sure if you are developing behind Cloudflare (silly me) to enable Cloudflare developer mode.
