### ISSUE TITLE
Not an Issue Need Advise

### ISSUE THREAD

**Issue by hitmc** [BRACKETS-by-TRIAD/craftable#121]
Hi,

I am new to craftable. Learning it. 

In sidebar.blade.php file I found this code
{{--<li class="nav-item"><a class="nav-link" href="{{ url('admin/configuration') }}"><i class="nav-icon icon-settings"></i> {{ __('Configuration') }}</a></li>--}}

Its a menu link to admin configuration I think. But i can't see this link in admin dashboard. when I typed the link in browser I am getting a 404 error.

Is it normal? if not help me activate this link on dashboard. if yes pls tell why this link is in the template.

thank you all. just curious.

**Comment by palypster** [comment]
It's there only for inspiration. Craftable currently doesn't provide any configuration page, sorry.
