### ISSUE TITLE
leave image file names unchanged

### ISSUE THREAD

**Issue by azzagazz** [BRACKETS-by-TRIAD/craftable#123]
hi there :wave:

first off, great product!

i have problems with the image file names being obfuscated when uploaded via the media library.

so if i upload a file i get a filename of `2XErs7IFabAXzvdt98mjJ5Z8Y7bdH6uDNaVTN2A8.png` for example, which is a horror for image seo 😆 

 i think i read something about this being an issue with media library < v6, but not sure if it was a general issue or not. so i guess my questions are:

1. is there a way to leave the filenames untouched in the current implementation?
2. will the project be updated to include media library v7 in the near future?

thanks!
daniel

**Comment by dejwCake** [comment]
Hello @azzagazz , 

thank you for your issue. Yes the image name is obfuscated during the upload. You can override the FileUploadController.php. However we are thinking to change it also in our package. We will release a new version supporting V7 media library soon.

Best regards

**Comment by palypster** [comment]
Craftable 4 and 5 use v7. Closing this one.
