### ISSUE TITLE
After "npm run dev" admin try to find icon on img/ folder instead images/ 

### ISSUE THREAD

**Issue by kamekun** [BRACKETS-by-TRIAD/craftable#127]
Hi, dunno why but the icons from the admin are missing after rpm run dev command.

it llook for example `../img/envelope.png instead` of `../images/vendor/craftable/envelope.png`

https://imgur.com/a/q2QuC4F

Regards.-

**Comment by kamekun** [comment]
In case  of a needed issue for this may be on this part: https://i.imgur.com/Zskmfzp.png

**Comment by palypster** [comment]
Can you still confirm this issue?

**Comment by kamekun** [comment]
Yes they issue still persist on the last versión.

**Comment by palypster** [comment]
Sorry, we cannot reproduce :(
