### ISSUE TITLE
403 This action is unauthorized. after generating a new form...

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#128]
After migration of tables and after running:

php artisan admin:generate <db-table-name>

npm install && npm run dev

and in administration I see the new created form menu,

but when I click on that new menu I get:

403 This action is unauthorized.

Anyone knows why this problem? I installed many times craftable online on my server and I always getting this on the new generated menu items. tables are created OK, everything seems to be created OK but I cannot access the new pages generated from the administrator menu.

any ideas how to fix this?
thanks a lot!

**Comment by palypster** [comment]
@rapgithub were you able to fix this one?

**Comment by rapgithub** [comment]
Yes but I didn't know how because I installed the project again and dissapeared!

Is there a way to fix this problem if happening again with a Model using just a command? 

like: php artisan .... ?

thanks

**Comment by palypster** [comment]
`artisan migrate:fresh` should do the trick

**Comment by contrerasroaca** [comment]
Hello I had the same problem as you, I solved it as follows

php artisan migrate --path = database \ migrations \ namemigration.php
