### ISSUE TITLE
Permission Issues after DB migration

### ISSUE THREAD

**Issue by azzagazz** [BRACKETS-by-TRIAD/craftable#130]
hi,

i am wondering what the expected db setup should be for the admin user to work. after some migration issues, i have my site working again, but cannot log in to the backend with my admin user. in the db i have the `admin` role in the `roles` table and all the permissions in the `permissions` table. the `role_has_permission` table was empty. 

````
/var/www/vendor/brackets/admin-auth/src/Http/Middleware/CanAdmin.php
        $this->guard = config('admin-auth.defaults.guard');
    }
 
    /**
     * Handle an incoming request.
     *
     * @param Request $request
     * @param Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        if (Auth::guard($this->guard)->check() && Auth::guard($this->guard)->user()->can('admin')) {
            return $next($request);
        }
 
        if (!Auth::guard($this->guard)->check()) {
            return redirect()->guest('/admin/login');
        } else {
            throw new UnauthorizedException('Unathorized');
        }
    }
}
````

after populating the `permissions` table with `givePermissionTo(Permission::all()` i still get the same error.

any help would be appreciated.

thanks!
daniel

**Comment by palypster** [comment]
Paste the .sql export of your tables related to the permissions (roles, permissions, role_has_permission) and the ID of your AdminUser you are trying to use.

**Comment by azzagazz** [comment]
ah, sorry. figured it out in the meantime. it had to do with how my tables were seeded. had to run the seeder for the two pivot tables again manually and everything worked fine again.
