### ISSUE TITLE
Support for Laravel 6

### ISSUE THREAD

**Issue by Elshaden** [BRACKETS-by-TRIAD/craftable#132]
Hi
Any idea if this system supports Laravel V6?

**Comment by palypster** [comment]
Hi, we have already started to work on it. Can't tell the estimate when it will be ready. It has solid priority, so I hope soon :)

**Comment by palypster** [comment]
We are happy to announce we have prepared Laravel 6 support - currently we are working on the update of the documentation and we're done.
