### ISSUE TITLE
brackets/media v3.0.0 problem requiring only laravel-medialibrary ^7.0 and brings problems with spatie and mediacollections

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#133]
Following the information of cartable docs 

I tried to install laravel-medialibrary ^6.0 to use mediacollections I receive this error in the terminal:

brackets/media v3.0.0 requires spatie/laravel-medialibrary ^7.0

using laravel-medialibrary ^7.0 brings error to the use of mediacollections
stating that I need to include this inside the model:

use Spatie\MediaLibrary\HasMedia\HasMedia;

then the model looks like:

```
class Country extends Model implements HasMedia, HasMediaCollections, HasMediaConversions
...
```

and then I receive more errors:

```
"Declaration of App\Models\Countries::registerMediaConversions(?Spatie\MediaLibrary\Media $media = NULL) must be compatible with Spatie\MediaLibrary\HasMedia\H ▶"
```

any solution?

**Comment by SamuelT-ST** [comment]
This bug is now fixed in a new release https://github.com/BRACKETS-by-TRIAD/craftable/releases/tag/v4.0.1

**Comment by palypster** [comment]
@rapgithub I understand this one was resolved, correct?

**Comment by rapgithub** [comment]
I guess so!

**Comment by rapgithub** [comment]
but can you please update the last demo with the sample you have online for MediaCollections
because I am using the vastest Laravel and cartable and the media library documentation is outdated in the documentation! it does not work anymore and the documentation does not mentions the changes you need to do with   "laravel/framework": "^6.2", and         "brackets/craftable": "^5.0",

Please I will appreciate an update of the latest demo to download too see what changed for media library to add images to the models...

my composer.json

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2",
        "brackets/craftable": "^5.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^2.0"
    },
    "require-dev": {
        "brackets/admin-generator": "^5.0",
        "facade/ignition": "^1.4",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^8.0"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

thanks

**Comment by rapgithub** [comment]
I am using php 7.4 and using this documentation step by steps I find also this error:

<img width="1076" alt="Screenshot 2020-01-28 at 12 30 26" src="https://user-images.githubusercontent.com/11996194/73260404-1f25ed80-41ca-11ea-8292-29adda3eacf2.png">

<img width="877" alt="Screenshot 2020-01-28 at 12 31 54" src="https://user-images.githubusercontent.com/11996194/73260436-2f3dcd00-41ca-11ea-843e-ac7925724f62.png">


I think line 35 it is the issue! should I modify this line or it is an updated version of media-uploader.blade.php working with php 7.4 I guess it is php version but I do not know yet... 
https://www.getcraftable.com/docs/5.0/media

**Comment by palypster** [comment]
We will work on the update of a demo.

The last error you have mentioned was already fixed though. Are you sure you have the latest packages? Try running `composer update` please.
