### ISSUE TITLE
getThumbs200ForCollection('cover') undefined inside my form-elements.blade.php with lastest craftable and Laravel versions

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#135]
When using lastest craftable and lavarel version getThumbs200ForCollection is undefined:

```
<div class="card">
    @if($mode === 'edit')
        @include('brackets/admin-ui::admin.includes.media-uploader', [
            'mediaCollection' => $country->getMediaCollection('cover'),
            'media' => $country->getThumbs200ForCollection('cover'),
            'label' => 'Cover photo'
        ])
    @else
        @include('brackets/admin-ui::admin.includes.media-uploader', [
            'mediaCollection' => app(App\Models\Country::class)->getMediaCollection('cover'),
            'label' => 'Cover photo'
        ])
    @endif
</div>
```

how to fix this missing method with latest craftable?
I just need to know how to add now media for uploads for single or gallery options!

the doc online is outdated!
thanks

**Comment by rapgithub** [comment]
I think the media installation using Laravel lastest version with craftable 4 it is not updated!

https://docs.getcraftable.com/v4/#/media?id=installation

like: getThumbs200ForCollection undefined!

I followed the instructions here for the model changes 
https://docs.getcraftable.com/v4/#/upgrade-guide

but anyway there is errors to add media uploads to your models!

anyone knows the changes we need to make here as well for the form-elements.blade.php?

thanks

**Comment by rapgithub** [comment]
I think the solution is here https://github.com/BRACKETS-by-TRIAD/craftable/issues/140 it has to do with the model!

**Comment by SamuelT-ST** [comment]
This issue is resolved here: https://github.com/BRACKETS-by-TRIAD/craftable/issues/140
