### ISSUE TITLE
Is there a stable version?

### ISSUE THREAD

**Issue by cyruscode19** [BRACKETS-by-TRIAD/craftable#141]
![image](https://user-images.githubusercontent.com/46013707/64973920-73e15f80-d8de-11e9-8029-a9f529f3b8b3.png)

**Comment by cyruscode19** [comment]
![image](https://user-images.githubusercontent.com/46013707/64973868-5f04cc00-d8de-11e9-96a9-a32b61f83f2d.png)

**Comment by rapgithub** [comment]
check this, in my case I have:

npm -v 
npm 6.9.0

laravel -v
Laravel Installer 2.1.0

craftable -v
Craftable Installer 1.1.0

and inside my composer.json I have:

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "brackets/craftable": "^4.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "brackets/admin-generator": "^4.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
 
```

in case you still seeing this problem try to delete the package package-lock.json and composer.lock 
and then run:

npm install

and npm run dev

I hope it can help to you! the only problem I am having it is the media uploader not working anymore because the changes in the files and online it is still missing demo of the lastest updates for media upload using the lastest version of craftable and Laravel...

I hope craftable guys can update that soon!

**Comment by rapgithub** [comment]
Same issue with the same results as above! try to update Laravel to lastest version first and try again! I will be doing the same!

https://laravel.com/docs/6.x/upgrade

**Comment by rapgithub** [comment]
the only I am having now it is this at the end of craftable:

```
In DBALException.php line 172:
                                                                                                        
  An exception occurred while executing 'SELECT TABLE_NAME AS `Table`, NON_UNIQUE AS Non_Unique, INDEX  
  _NAME AS Key_name, SEQ_IN_INDEX AS Seq_in_index, COLUMN_NAME AS Column_Name, COLLATION AS Collation,  
   CARDINALITY AS Cardinality, SUB_PART AS Sub_Part, PACKED AS Packed, NULLABLE AS `Null`, INDEX_TYPE   
  AS Index_Type, COMMENT AS Comment FROM information_schema.STATISTICS WHERE TABLE_NAME = 'admin_users  
  ' AND TABLE_SCHEMA = 'craftable_tripsgenio' ORDER BY SEQ_IN_INDEX ASC':                               
                                                                                                        
  PDO::query(): MySQL server has gone away                                                              
                                                                                                        

In PDOConnection.php line 88:
                                            
  PDO::query(): MySQL server has gone away  
                                            

Craftable crafted! Craft something crafty ;)
```

**Comment by palypster** [comment]
Hey guys, today we have released new Craftable v5 where we have introduced Laravel 6 support, but dropped Laravel 5 support.

It looks like the old installer has a bug that incorrectly installs latest Laravel 6 on Craftable 4 - this was not our intention, we are going to debug it later.

But the easiest thing you can do is indeed to update your Craftable installer to latest 1.2.0 and then everything should work.

If you have an existing project with Craftable 4, upgrade is pretty straightforward - only check out the upgrade of Laravel 5.8 -> Laravel 6 and you are all set. We are about to publish new documentation tomorrow I hope, where this will be covered.

**Comment by rapgithub** [comment]
Is there any sample of the media upload available for the new version? I follow up all the recommended changes here https://docs.getcraftable.com/v3/#/media?id=media but it seems not to work properly after the changes applied:

many errors! for instance 

```
"Class App\Models\Post contains 11 abstract 
methods and must therefore be declared abstract or implement the remaining methods (Spatie\MediaLibrary\HasMedia\HasMedia::media,
 Spatie\MediaLibrary\HasMedia\HasMedia::addMedia,
 Spatie\MediaLibrary\HasMedia\HasMedia::copyMedia, ...) ◀"

```

anyway to fix them?
thanks

**Comment by rapgithub** [comment]
I think I found the bug:

 Brackets\AdvancedLogger\Formatters\LineWithHashFormatter::format(array $record)

change it from:

public function format(array $record)

to this:

public function format(array $record): string

: string was missing there!
:)

**Comment by palypster** [comment]
feel free to file a PR for that

**Comment by rapgithub** [comment]
regarding media upload for post table not yet finding where this error is this coming from exactly with the new craftable and Laravel versions and after making the changes for updates mentioned here:

https://docs.getcraftable.com/v4/#/upgrade-guide

```
"Class App\Models\Post contains 11 abstract 
methods and must therefore be declared abstract or implement the remaining methods (Spatie\MediaLibrary\HasMedia\HasMedia::media,
 Spatie\MediaLibrary\HasMedia\HasMedia::addMedia,
 Spatie\MediaLibrary\HasMedia\HasMedia::copyMedia, ...) ◀"
```

anyone knows the fix? 
also where is the change we need to make inside form-elements.blade 

before it was:

```    
@if($mode === 'edit')
        @include('brackets/admin-ui::admin.includes.media-uploader', [
            'mediaCollection' => $inspiration->getMediaCollection('cover'),
            'media' => $inspiration->getThumbs200ForCollection('cover'),
            'label' => 'Cover photo'
        ])
    @else
        @include('brackets/admin-ui::admin.includes.media-uploader', [
            'mediaCollection' => app(App\Models\Inspiration::class)->getMediaCollection('cover'),
            'label' => 'Cover photo'
        ])
    @endif
</div>
```

what are the changes to make here here for the media upload to work without errors with the craftable 5 and Laravel 6 updates?

**Comment by palypster** [comment]
@rapgithub please let's keep the issues clean. File new issues for each bug you find, now it's total mess, I'm not sure what the errors are. Can you please separate them?

Regarding #140 there is reply waiting for you to see. 

@cyruscode19  I'm closing this one (and file new one with original problem: Older installer is broken - installs incorrect Laravel version).

**Comment by palypster** [comment]
Original issue here  https://github.com/BRACKETS-by-TRIAD/craftable/issues/142
