### ISSUE TITLE
Older installer is broken

### ISSUE THREAD

**Issue by palypster** [BRACKETS-by-TRIAD/craftable#142]
~Installer 1.1.0 installs Laravel 6, it should install Laravel 5.8~
Installer 1.1.0 installs Laravel 5.8 (correct) and then it tries to install Craftable 5, but it should install Craftable 4 instead.

**Comment by dejwCake** [comment]
@palypster I do not think, that this was the case. The problem was that it installs Laravel 5.8 as it should, however tried to instal Craftable v5.

**Comment by palypster** [comment]
Correct, I will update original description.

**Comment by palypster** [comment]
Low impact, won't solve
