### ISSUE TITLE
how to generate the crud correctly for User detail tooltip relations? not working for me...

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#143]
I followed this guidelines here stating that CRUD including user-detail-tooltip component in your listing will be created as well:

https://getcraftable.com/docs/5.0/explore-generator#user-detail-tooltip

I added these lines to my migration table 

```
            $table->unsignedBigInteger('country_id');
            $table->foreign('country_id')->references('id')->on('countries')->onDelete('cascade');
            $table->unsignedBigInteger('city_id');
            $table->foreign('city_id')->references('id')->on('cities')->onDelete('cascade');
            $table->unsignedBigInteger('currency_id');
            $table->foreign('currency_id')->references('id')->on('currencies');

```

Complete table:

```
class CreatePlaces extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('places', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->jsonb('title');

            $table->unsignedBigInteger('country_id');
            $table->foreign('country_id')->references('id')->on('countries')->onDelete('cascade');
            $table->unsignedBigInteger('city_id');
            $table->foreign('city_id')->references('id')->on('cities')->onDelete('cascade');
            $table->unsignedBigInteger('currency_id');
            $table->foreign('currency_id')->references('id')->on('currencies');

            $table->date('published_at')->nullable();
            $table->boolean('enabled')->default(false);
            $table->timestamps();
        });


```

I have a country and city and currency table as well.

The migration of the table went well not problems 

php artisan migrate

but when creating the crud the User detail tooltip for the relational tables is not created...

php artisan admin:generate places

the generator does not generate the whole CRUD for the user-detail-tooltip component in my listing or create or edit blades files...

the fields created looks like here no multiselect created for them:

<img width="608" alt="Screenshot 2019-09-19 at 10 04 56" src="https://user-images.githubusercontent.com/11996194/65225181-f1ff5b00-dac4-11e9-8f52-6829795b20b7.png">

and in the listing it shows only the number of the country id or city...

what am I doing wrong?
I am using craftable 5 with Laravel 6

any ideas how to make it work?
thanks

**Comment by palypster** [comment]
Hey, this is maybe not written correctly in documentation, but tooltip generator only works if you use those exact column names, so:
`created_by_admin_user_id`
`updated_by_admin_user_id `

Then it  automatically "knows" the entity is related to the AdminUser model and it creates the tooltip. We will update it in the documentation.

Let us know if it works for you.

**Comment by rapgithub** [comment]
so in my case for country_id, city_id or currency_id how do I create this migration table for my relations to work?

I am lost here ... 

is it so?

            $table->unsignedBigInteger('created_by_admin_country_id');
            $table->foreign('created_by_admin_country_id')->references('id')->on('countries')->onDelete('cascade');

and I need also

            $table->unsignedBigInteger('updated_by_admin_country_id');
            $table->foreign('updated_by_admin_country_id')->references('id')->on('countries')->onDelete('cascade');

or...?
can you tell me how do I have to create the table in my case I have country_id, city_id and currency_id as relationship to country, city and currency tables? 

thanks

**Comment by palypster** [comment]
I see what you are trying to solve but unfortunately this is not supported. The features is really tied only to AdminUser, not any model. It's called "AdminUser tooltip" not "YourRelatedMode tooltip". 

We were thinking about adding better support for relationships, but once we started prototyping, more and more questions were rising and it was getting too complex.

This feature is really simple: AdminUser can see, who created/updated an article/post/country/..[any model] and when.

**Comment by rapgithub** [comment]
Got it so in my case I need to create it myself I see ... 

I will take a look at this table CreateArticlesWithRelationshipsTable and inside the code in ArticlesWithRelationships model and code to see how to make it work for my case using multiselect fields!

Yes it will be nice to have simple relationships generated by the CRUD as well I know it can be so complex but maybe it can be created generically for simple relations and from there anyone can prototype the final results!

thanks!
