### ISSUE TITLE
CRUD generator of post table

### ISSUE THREAD

**Issue by mauphung** [BRACKETS-by-TRIAD/craftable#144]
Hi,
I installed craftable on latestLaravel 6 version and generate CRUD post table. It's working OK but when I create a new post, it display the page but there are no form components in the display. I wonder if CRUD Generator generate the form in the latest version?

**Comment by palypster** [comment]
Yes, everything should be working. Maybe you forget to run `npm run dev` after the crud being generated?

**Comment by b4nghh** [comment]
I had the same problem.
Clear browser cache will solve it.
