### ISSUE TITLE
The Mix manifest does not exist

### ISSUE THREAD

**Issue by rbkkm** [BRACKETS-by-TRIAD/craftable#15]
The Mix manifest does not exist. (View: C:\wamp310\www\cft\vendor\brackets\admin-ui\resources\views\admin\partials\main-styles.blade.php) (View: C:\wamp310\www\cft\vendor\brackets\admin-ui\resources\views\admin\partials\main-styles.blade.php) (View: C:\wamp310\www\cft\vendor\brackets\admin-ui\resources\views\admin\partials\main-styles.blade.php)

C:\wamp310\www\cft\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php
 
        if ($manifestDirectory && ! Str::startsWith($manifestDirectory, '/')) {
            $manifestDirectory = "/{$manifestDirectory}";
        }
 
        if (file_exists(public_path($manifestDirectory.'/hot'))) {
            $url = file_get_contents(public_path($manifestDirectory.'/hot'));
 
            if (Str::startsWith($url, ['http://', 'https://'])) {
                return new HtmlString(Str::after($url, ':').$path);
            }
 
            return new HtmlString("//localhost:8080{$path}");
        }
 
        $manifestPath = public_path($manifestDirectory.'/mix-manifest.json');
 
        if (! isset($manifests[$manifestPath])) {
            if (! file_exists($manifestPath)) {
                throw new Exception('The Mix manifest does not exist.');
            }
 
            $manifests[$manifestPath] = json_decode(file_get_contents($manifestPath), true);
        }
 
        $manifest = $manifests[$manifestPath];
 
        if (! isset($manifest[$path])) {
            report(new Exception("Unable to locate Mix file: {$path}."));
 
            if (! app('config')->get('app.debug')) {
                return $path;
            }
        }

**Comment by palypster** [comment]
Probably duplicate to #12 

Can you paste here the output of the installation, was there any error? Mix manifest should be generated automatically during `craftable new` command.

**Comment by rbkkm** [comment]
npm 5.6.0

C:\wamp310\www\ltst> composer require brackets/craftable
Using version ^2.0 for brackets/craftable
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 20 installs, 0 updates, 0 removals
  - Installing spatie/temporary-directory (1.1.3): Loading from cache
  - Installing spatie/db-dumper (2.8.2): Loading from cache
  - Installing spatie/laravel-backup (5.2.1): Downloading (100%)
  - Installing spatie/laravel-permission (2.9.0): Downloading (100%)
  - Installing spatie/image-optimizer (1.0.11): Downloading (100%)
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing intervention/image (2.4.1): Loading from cache
  - Installing league/glide (1.2.2): Loading from cache
  - Installing spatie/image (1.4.1): Downloading (100%)
  - Installing spatie/pdf-to-image (1.2.2): Loading from cache
  - Installing spatie/laravel-medialibrary (6.6.9): Downloading (100%)
  - Installing brackets/media (v1.0.1): Loading from cache
  - Installing spatie/laravel-translatable (2.1.4): Downloading (100%)
  - Installing brackets/translatable (v1.0.0): Loading from cache
  - Installing brackets/admin-listing (v2.0.0): Loading from cache
  - Installing brackets/admin-ui (v2.0.0): Loading from cache
  - Installing brackets/admin-translations (v2.0.0): Loading from cache
  - Installing brackets/admin-auth (v2.0.0): Loading from cache
  - Installing brackets/craftable (v2.0.0): Loading from cache
spatie/laravel-backup suggests installing guzzlehttp/guzzle (Allows notifications to be sent via Slack)
intervention/image suggests installing ext-imagick (to use Imagick based image processing.)
intervention/image suggests installing intervention/imagecache (Caching extension for the Intervention Image library)
spatie/laravel-medialibrary suggests installing php-ffmpeg/php-ffmpeg (Required for generating video thumbnails)
spatie/laravel-medialibrary suggests installing league/flysystem-aws-s3-v3 (Required to use AWS S3 file storage)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: brackets/admin-auth
Discovered Package: brackets/admin-listing
Discovered Package: brackets/admin-translations
Discovered Package: brackets/admin-ui
Discovered Package: brackets/craftable
Discovered Package: brackets/media
Discovered Package: brackets/translatable
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/tinker
Discovered Package: spatie/laravel-backup
Discovered Package: spatie/laravel-medialibrary
Discovered Package: spatie/laravel-permission
Discovered Package: spatie/laravel-translatable
Package manifest generated successfully.

PS C:\wamp310\www\ltst> composer require --dev brackets/admin-generator
Using version ^2.0 for brackets/admin-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 6 installs, 0 updates, 0 removals
  - Installing doctrine/collections (v1.5.0): Loading from cache
  - Installing doctrine/cache (v1.7.1): Loading from cache
  - Installing doctrine/annotations (v1.6.0): Loading from cache
  - Installing doctrine/common (v2.8.1): Loading from cache
  - Installing doctrine/dbal (v2.6.3): Loading from cache
  - Installing brackets/admin-generator (v2.0.0): Loading from cache
doctrine/cache suggests installing alcaeus/mongo-php-adapter (Required to use legacy MongoDB driver)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Discovered Package: brackets/admin-auth
Discovered Package: brackets/admin-generator
Discovered Package: brackets/admin-listing
Discovered Package: brackets/admin-translations
Discovered Package: brackets/admin-ui
Discovered Package: brackets/craftable
Discovered Package: brackets/media
Discovered Package: brackets/translatable
Discovered Package: fideloper/proxy
Discovered Package: intervention/image
Discovered Package: laravel/tinker
Discovered Package: spatie/laravel-backup
Discovered Package: spatie/laravel-medialibrary
Discovered Package: spatie/laravel-permission
Discovered Package: spatie/laravel-translatable
Package manifest generated successfully.

**Comment by rbkkm** [comment]
PS C:\wamp310\www\ltst> php artisan craftable:install
Installing Craftable...
Copied File [\vendor\spatie\laravel-permission\database\migrations\create_permission_tables.php.stub] To [\database\migrations\2018_02_10_163445_create_permission_tables.php]
Publishing complete.
Copied File [\vendor\spatie\laravel-permission\config\permission.php] To [\config\permission.php]
Publishing complete.
Copied File [\vendor\spatie\laravel-backup\config\backup.php] To [\config\backup.php]
Copied Directory [\vendor\spatie\laravel-backup\resources\lang] To [\resources\lang\vendor\backup]
Publishing complete.
Copied File [\vendor\spatie\laravel-medialibrary\database\migrations\create_media_table.php.stub] To [\database\migrations\2018_02_10_163445_create_media_table.php]
Publishing complete.
Copied File [\vendor\brackets\media\install-stubs\config\media-collections.php] To [\config\media-collections.php]
Publishing complete.
Copied File [\vendor\brackets\craftable\install-stubs\database\migrations\fill_default_user_and_permissions.php] To [\database\migrations\2018_02_10_163450_fill_default_user_and_permissions.php]
Publishing complete.
Installing package brackets/admin-ui
Copied Directory [\vendor\brackets\admin-ui\install-stubs\resources\assets] To [\resources\assets\admin]
Copied Directory [\vendor\brackets\admin-ui\install-stubs\resources\views] To [\resources\views]
Publishing complete.
Webpack configuration updated
Changing package.json
package.json changed
Package brackets/admin-ui installed
Installing package brackets/admin-auth
Installing package brackets/admin-ui
Copied Directory [\vendor\brackets\admin-ui\install-stubs\resources\assets] To [\resources\assets\admin]
Copied Directory [\vendor\brackets\admin-ui\install-stubs\resources\views] To [\resources\views]
Publishing complete.
Changing package.json
package.json changed
Package brackets/admin-ui installed
Copied File [\vendor\brackets\admin-auth\install-stubs\config\admin-auth.php] To [\config\admin-auth.php]
Copied File [\vendor\brackets\admin-auth\install-stubs\database\migrations\modify_users_table.php] To [\database\migrations\2017_08_24_000000_modify_users_table.php]
Copied Directory [\vendor\brackets\admin-auth\install-stubs\resources\lang] To [\resources\lang\vendor\admin-auth]
Publishing complete.
Admin Auth assets registered
Migration table created successfully.
Migrating: 2014_10_12_000000_create_users_table
Migrated:  2014_10_12_000000_create_users_table
Migrating: 2014_10_12_100000_create_password_resets_table
Migrated:  2014_10_12_100000_create_password_resets_table
Migrating: 2016_09_29_094310_create_activations_table
Migrated:  2016_09_29_094310_create_activations_table
Migrating: 2017_08_24_000000_modify_users_table
Migrated:  2017_08_24_000000_modify_users_table
Migrating: 2018_02_10_163445_create_media_table
Migrated:  2018_02_10_163445_create_media_table
Migrating: 2018_02_10_163445_create_permission_tables
Migrated:  2018_02_10_163445_create_permission_tables
Migrating: 2018_02_10_163450_fill_default_user_and_permissions
Migrated:  2018_02_10_163450_fill_default_user_and_permissions
Package brackets/admin-auth installed
Nothing to migrate.
Deleting previous files finished.
Generating App\Models\User finished
Generating App\Http\Controllers\Admin\UsersController finished
Generating App\Http\Requests\Admin\User\IndexUser finished
Generating App\Http\Requests\Admin\User\StoreUser finished
Generating App\Http\Requests\Admin\User\UpdateUser finished
Generating App\Http\Requests\Admin\User\DestroyUser finished
Appending routes finished
Generating C:\wamp310\www\ltst\resources\views/admin/user/index.blade.php finished
Generating C:\wamp310\www\ltst\resources\assets/admin/js/user/Listing.js finished
Appending Listing to C:\wamp310\www\ltst\resources\assets/admin/js/user/index.js finished
Appending user/index.js to C:\wamp310\www\ltst\resources\assets/admin/js/index.js finished
Generating C:\wamp310\www\ltst\resources\views/admin/user/components/form-elements.blade.php finished
Generating C:\wamp310\www\ltst\resources\views/admin/user/create.blade.php finished
Generating C:\wamp310\www\ltst\resources\views/admin/user/edit.blade.php finished
Generating C:\wamp310\www\ltst\resources\assets/admin/js/user/Form.js finished
Appending Form to C:\wamp310\www\ltst\resources\assets/admin/js/user/index.js finished
Appending translations finished
Appending User model to ModelFactory finished
Generating whole user admin finished
Generating App\Http\Controllers\Admin\ProfileController finished
Appending routes finished
Generating C:\wamp310\www\ltst\resources\views/admin/profile/edit-profile.blade.php finished
Generating C:\wamp310\www\ltst\resources\assets/admin/js/profile/edit-profile/Form.js finished
Appending Form to C:\wamp310\www\ltst\resources\assets/admin/js/profile/edit-profile/index.js finished
Appending profile/edit-profile/index.js to C:\wamp310\www\ltst\resources\assets/admin/js/index.js finished
Generating C:\wamp310\www\ltst\resources\views/admin/profile/edit-password.blade.php finished
Generating C:\wamp310\www\ltst\resources\assets/admin/js/profile/edit-password/Form.js finished
Appending Form to C:\wamp310\www\ltst\resources\assets/admin/js/profile/edit-password/index.js finished
Appending profile/edit-password/index.js to C:\wamp310\www\ltst\resources\assets/admin/js/index.js finished
Generating whole admin "My Profile" finished
Installing package brackets/admin-translations
Installing package brackets/admin-ui
Copied Directory [\vendor\brackets\admin-ui\install-stubs\resources\assets] To [\resources\assets\admin]
Copied Directory [\vendor\brackets\admin-ui\install-stubs\resources\views] To [\resources\views]
Publishing complete.
Changing package.json
package.json changed
Package brackets/admin-ui installed
Copied File [\vendor\brackets\admin-translations\config\admin-translations.php] To [\config\admin-translations.php]
Copied File [\vendor\brackets\admin-translations\database\migrations\create_translations_table.php.stub] To [\database\migrations\2018_02_10_163445_create_translations_table.php]
Publishing complete.
Copied File [\vendor\brackets\translatable\install-stubs\config\translatable.php] To [\config\translatable.php]
Publishing complete.
Admin Translation assets registered
Migrating: 2018_02_10_163445_create_translations_table
Migrated:  2018_02_10_163445_create_translations_table
Package brackets/admin-translations installed
Scanning codebase and storing all translations
60 translations saved
Package brackets/admin-listing installed
Admin password is: jdyCHgkxuT
Craftable installed.

**Comment by rbkkm** [comment]
line 573 

C:\wamp310\www\ltst\vendor\laravel\framework\src\Illuminate\Foundation\helpers.php
 
        if ($manifestDirectory && ! Str::startsWith($manifestDirectory, '/')) {
            $manifestDirectory = "/{$manifestDirectory}";
        }
 
        if (file_exists(public_path($manifestDirectory.'/hot'))) {
            $url = file_get_contents(public_path($manifestDirectory.'/hot'));
 
            if (Str::startsWith($url, ['http://', 'https://'])) {
                return new HtmlString(Str::after($url, ':').$path);
            }
 
            return new HtmlString("//localhost:8080{$path}");
        }
 
        $manifestPath = public_path($manifestDirectory.'/mix-manifest.json');
 
        if (! isset($manifests[$manifestPath])) {
            if (! file_exists($manifestPath)) {
                throw new Exception('The Mix manifest does not exist.');
            }
 
            $manifests[$manifestPath] = json_decode(file_get_contents($manifestPath), true);
        }
 
        $manifest = $manifests[$manifestPath];
 
        if (! isset($manifest[$path])) {
            report(new Exception("Unable to locate Mix file: {$path}."));
 
            if (! app('config')->get('app.debug')) {
                return $path;
            }
        }

**Comment by rbkkm** [comment]
i runned

npm install
npm run dev

error is gone ,  but layout is not good

![schermopname 24](https://user-images.githubusercontent.com/35529692/36064420-0f79f580-0e8b-11e8-9875-742a120cc525.jpg)

**Comment by matejminar** [comment]
this seems to be a laravel-mix's windows specific issue - discussed [here](https://github.com/JeffreyWay/laravel-mix/issues/131)

installing cross-env globally should do the trick:
`npm i -g cross-env`
