### ISSUE TITLE
craftable: Reading Exif data is not supported by this PHP installation. Win10

### ISSUE THREAD

**Issue by Marek-Bernad** [BRACKETS-by-TRIAD/craftable#152]
During running commands stated here: https://github.com/BRACKETS-by-TRIAD/craftable/issues/11#issuecomment-361755342

For command:
`php artisan craftable:install`

I will get an error and the process failure:

> In ExifCommand.php line 22:
> Reading Exif data is not supported by this PHP installation.

From this moment, migrations and the DB are inconsistent, and there is a need to remove and create database again with running whole installation in a new fresh folder.

**In order to partially fix this issue, it is a need to uncomment php.ini lines in advance:**

```
extension=mbstring
extension=exif 
```

**Comment by palypster** [comment]
Thanks. Can you please update this in our docs?

**Comment by i3130002** [comment]
In my case environment path variable of my CLI was set to the wrong php. Test it using php --ini
