### ISSUE TITLE
craftable:init-env not working - FATAL:  role "root" does not exist on Win10

### ISSUE THREAD

**Issue by Marek-Bernad** [BRACKETS-by-TRIAD/craftable#153]
During running commands stated here: https://github.com/BRACKETS-by-TRIAD/craftable/issues/11#issuecomment-361755342

For command:
`php artisan craftable:init-env`

After successfull submit of all fields for DB connection the .env file still looks like follows and is not updated:
```
DB_CONNECTION=pgsql
DB_HOST=127.0.0.1
DB_PORT=5432
DB_DATABASE=laravel
DB_USERNAME=root
DB_PASSWORD=
```

**Therefore during next command run:**

`php artisan craftable:install`

it fails on bad DB configuration:

> In Connection.php line 665:
  SQLSTATE[08006] [7] FATAL:  role "root" does not exist (SQL: select * from information_schema.tables where table_schema = public and table_name = migrations and table_type = 'BASE TABLE')
> In PDOConnection.php line 31:
  SQLSTATE[08006] [7] FATAL:  role "root" does not exist
> In PDOConnection.php line 27:
  SQLSTATE[08006] [7] FATAL:  role "root" does not exist

And after this failure, migrations become inconsistent and you are about to rerun whole installation in new fresh folder. I am using PHP version of 7.3.7.

**The issue can be partially fixed by rewriting the .env file manually for now before craftable:install command run.**

**Comment by palypster** [comment]
This is probably duplicate to https://github.com/BRACKETS-by-TRIAD/craftable/issues/145 

On some windows platforms there is a problem with:
`php artisan craftable:init-env`

command which fails to prompt database credentials.

Easy workaround is to update your `.env` file manually and conitnue like you hjave proposed.

Let's add this to our docs as well.
