### ISSUE TITLE
Installer not working

### ISSUE THREAD

**Issue by miquelangeld** [BRACKETS-by-TRIAD/craftable#154]
When installer ask for database info fails finishing installation.
No matter what database name you give. The installer try to use laravel as database name:

In Connection.php line 665:
                                                                                                                                                                                           
  SQLSTATE[HY000] [1049] Unknown database 'laravel' (SQL: select * from information_schema.tables where table_schema = laravel and table_name = migrations and table_type = 'BASE TABLE')  
                                                                                                                                                                                           

In PDOConnection.php line 31:
                                                     
  SQLSTATE[HY000] [1049] Unknown database 'laravel'  
                                                     

In PDOConnection.php line 27:
                                                     
  SQLSTATE[HY000] [1049] Unknown database 'laravel'

**Comment by miquelangeld** [comment]
If I create a database named laravel then the installer seems to work. And create all tables in laravel database, not the one that I give to installer.

**Comment by palypster** [comment]
Maybe relates to https://github.com/BRACKETS-by-TRIAD/craftable/issues/145
