### ISSUE TITLE
Spatia permission cache bug - Solution

### ISSUE THREAD

**Issue by Faks** [BRACKETS-by-TRIAD/craftable#155]
Hi recently encountered an ugly bug with permissions 403 everywhere I started tracking it down and found out that spatie permissions package cache tends to on Laravel 6 to not update and get stuck, so in terminal php artisan cache:clear and permisions should load after and gates should work properly
P.S
Solum DeSignum.

**Comment by palypster** [comment]
Can you be  more specific, when exactly you  started to receive the 403? After what operation - installation? CRUD generation? or something  else?

**Comment by Faks** [comment]
after fresh crud generation.

**Comment by palypster** [comment]
Sorry, we are unable to reproduce this one. Have you found something out in the meantime?

**Comment by matalina** [comment]
I'm encountering the same problem.  I just installed Craftable into a clean laravel install.  Ran my migrations, and then ran admin:generate <tablename> and then ran npm run dev to compile it all together, and my new link gives me a 403.  The migration ran for the permissions and nothing has changed from the initial install.  Sadly the above clearing of cache didn't work in my case.

**Comment by palypster** [comment]
can you paste the complete output starting from `admin:generate` command? I want to check if generator generated migration file that attaches the permissions and if this migration really run or not.

**Comment by matalina** [comment]
I think this problem only occurs when the cache driver is set to file.    I think I changed mine to database and the problem went away, but I can't verify this at the moment as I don't yet have a migration to run on the database cache.  I might in a short while when I get further into feature set.

**Comment by codeurfou** [comment]
This issue is a real thing. I am facing troubles with permissions and editing default cache driver (to "array" or whatever) seems to fix the problem.
