### ISSUE TITLE
Can't install on Laravel 6.2 Project

### ISSUE THREAD

**Issue by bachilli** [BRACKETS-by-TRIAD/craftable#156]
I got this after running composer require:

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install brackets/craftable v5.0.0
    - Conclusion: remove laravel/framework v6.2.0
    - Conclusion: don't install laravel/framework v6.2.0
    - spatie/laravel-backup 6.0.0 requires illuminate/notifications ~5.7.0 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/notifications[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - spatie/laravel-backup 6.0.1 requires illuminate/notifications ~5.7.0 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/notifications[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - spatie/laravel-backup 6.0.2 requires illuminate/notifications ~5.7.0 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/notifications[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - spatie/laravel-backup 6.0.3 requires illuminate/notifications ~5.7.0 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/notifications[5.7.17, 5.7.18, 5.7.19, 5.7.x-dev, v5.7.0, v5.7.1, v5.7.10, v5.7.11, v5.7.15, v5.7.2, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28, v5.7.3, v5.7.4, v5.7.5, v5.7.6, v5.7.7, v5.7.8, v5.7.9].
    - spatie/laravel-backup 6.0.4 requires illuminate/support ~5.7.20 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.x-dev, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28].
    - spatie/laravel-backup 6.0.5 requires illuminate/support ~5.7.20 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.x-dev, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28].
    - spatie/laravel-backup 6.0.6 requires illuminate/support ~5.7.20 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.x-dev, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28].
    - spatie/laravel-backup 6.0.7 requires illuminate/support ~5.7.20 -> satisfiable by laravel/framework[5.7.x-dev], illuminate/support[5.7.x-dev, v5.7.20, v5.7.21, v5.7.22, v5.7.23, v5.7.26, v5.7.27, v5.7.28].
    - spatie/laravel-backup 6.1.0 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - spatie/laravel-backup 6.1.1 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - spatie/laravel-backup 6.1.2 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - spatie/laravel-backup 6.2.0 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - spatie/laravel-backup 6.2.1 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - spatie/laravel-backup 6.3.0 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - spatie/laravel-backup 6.3.1 requires illuminate/events ~5.8.0 -> satisfiable by illuminate/events[5.8.x-dev, v5.8.0, v5.8.11, v5.8.12, v5.8.14, v5.8.15, v5.8.17, v5.8.18, v5.8.19, v5.8.2, v5.8.20, v5.8.22, v5.8.24, v5.8.27, v5.8.28, v5.8.29, v5.8.3, v5.8.30, v5.8.31, v5.8.32, v5.8.33, v5.8.34, v5.8.35, v5.8.4, v5.8.8, v5.8.9].
    - Can only install one of: laravel/framework[5.7.x-dev, v6.2.0].
    - don't install illuminate/support 5.7.x-dev|don't install laravel/framework v6.2.0
    - don't install illuminate/support v5.7.20|don't install laravel/framework v6.2.0
    - don't install illuminate/support v5.7.21|don't install laravel/framework v6.2.0
    - don't install illuminate/support v5.7.22|don't install laravel/framework v6.2.0
    - don't install illuminate/support v5.7.23|don't install laravel/framework v6.2.0
    - don't install illuminate/support v5.7.26|don't install laravel/framework v6.2.0
    - don't install illuminate/support v5.7.27|don't install laravel/framework v6.2.0
    - don't install illuminate/support v5.7.28|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications 5.7.17|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications 5.7.18|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications 5.7.19|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications 5.7.x-dev|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.0|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.1|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.10|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.11|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.15|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.2|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.20|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.21|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.22|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.23|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.26|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.27|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.28|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.3|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.4|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.5|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.6|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.7|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.8|don't install laravel/framework v6.2.0
    - don't install illuminate/notifications v5.7.9|don't install laravel/framework v6.2.0
    - don't install illuminate/events 5.8.x-dev|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.0|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.11|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.12|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.14|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.15|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.17|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.18|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.19|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.2|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.20|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.22|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.24|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.27|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.28|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.29|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.3|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.30|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.31|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.32|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.33|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.34|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.35|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.4|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.8|don't install laravel/framework v6.2.0
    - don't install illuminate/events v5.8.9|don't install laravel/framework v6.2.0
    - Conclusion: don't install league/flysystem 1.0.46|install spatie/laravel-backup 6.0.0|install spatie/laravel-backup 6.0.1|install spatie/laravel-backup 6.0.2|install spatie/laravel-backup 6.0.3|install spatie/laravel-backup 6.0.4|install spatie/laravel-backup 6.0.5|install spatie/laravel-backup 6.0.6|install spatie/laravel-backup 6.0.7|install spatie/laravel-backup 6.1.0|install spatie/laravel-backup 6.1.1|install spatie/laravel-backup 6.1.2|install spatie/laravel-backup 6.2.0|install spatie/laravel-backup 6.2.1|install spatie/laravel-backup 6.3.0|install spatie/laravel-backup 6.3.1
    - Conclusion: don't install brackets/craftable v5.0.0|remove league/flysystem 1.0.46|install spatie/laravel-backup 6.0.0|install spatie/laravel-backup 6.0.1|install spatie/laravel-backup 6.0.2|install spatie/laravel-backup 6.0.3|install spatie/laravel-backup 6.0.4|install spatie/laravel-backup 6.0.5|install spatie/laravel-backup 6.0.6|install spatie/laravel-backup 6.0.7|install spatie/laravel-backup 6.1.0|install spatie/laravel-backup 6.1.1|install spatie/laravel-backup 6.1.2|install spatie/laravel-backup 6.2.0|install spatie/laravel-backup 6.2.1|install spatie/laravel-backup 6.3.0|install spatie/laravel-backup 6.3.1
    - Conclusion: don't install brackets/craftable v5.0.0|don't install league/flysystem 1.0.46|install spatie/laravel-backup 6.0.0|install spatie/laravel-backup 6.0.1|install spatie/laravel-backup 6.0.2|install spatie/laravel-backup 6.0.3|install spatie/laravel-backup 6.0.4|install spatie/laravel-backup 6.0.5|install spatie/laravel-backup 6.0.6|install spatie/laravel-backup 6.0.7|install spatie/laravel-backup 6.1.0|install spatie/laravel-backup 6.1.1|install spatie/laravel-backup 6.1.2|install spatie/laravel-backup 6.2.0|install spatie/laravel-backup 6.2.1|install spatie/laravel-backup 6.3.0|install spatie/laravel-backup 6.3.1
    - Installation request for laravel/framework (locked at v6.2.0, required as ^6.0) -> satisfiable by laravel/framework[v6.2.0].
    - Conclusion: don't install brackets/craftable v5.0.0|remove league/flysystem 1.0.46|install spatie/laravel-backup 6.0.0|install spatie/laravel-backup 6.0.1|install spatie/laravel-backup 6.0.2|install spatie/laravel-backup 6.0.3|install spatie/laravel-backup 6.0.4|install spatie/laravel-backup 6.0.5|install spatie/laravel-backup 6.0.6|install spatie/laravel-backup 6.0.7|install spatie/laravel-backup 6.1.0|install spatie/laravel-backup 6.1.1|install spatie/laravel-backup 6.1.2|install spatie/laravel-backup 6.2.0|install spatie/laravel-backup 6.2.1|install spatie/laravel-backup 6.3.0|install spatie/laravel-backup 6.3.1
    - Conclusion: don't install brackets/craftable v5.0.0|don't install league/flysystem 1.0.46|install spatie/laravel-backup 6.0.0|install spatie/laravel-backup 6.0.1|install spatie/laravel-backup 6.0.2|install spatie/laravel-backup 6.0.3|install spatie/laravel-backup 6.0.4|install spatie/laravel-backup 6.0.5|install spatie/laravel-backup 6.0.6|install spatie/laravel-backup 6.0.7|install spatie/laravel-backup 6.1.0|install spatie/laravel-backup 6.1.1|install spatie/laravel-backup 6.1.2|install spatie/laravel-backup 6.2.0|install spatie/laravel-backup 6.2.1|install spatie/laravel-backup 6.3.0|install spatie/laravel-backup 6.3.1
    - Installation request for brackets/craftable ^5.0 -> satisfiable by brackets/craftable[5.0.x-dev, v5.0.0].
    - Conclusion: remove league/flysystem 1.0.46|install spatie/laravel-backup 6.0.0|install spatie/laravel-backup 6.0.1|install spatie/laravel-backup 6.0.2|install spatie/laravel-backup 6.0.3|install spatie/laravel-backup 6.0.4|install spatie/laravel-backup 6.0.5|install spatie/laravel-backup 6.0.6|install spatie/laravel-backup 6.0.7|install spatie/laravel-backup 6.1.0|install spatie/laravel-backup 6.1.1|install spatie/laravel-backup 6.1.2|install spatie/laravel-backup 6.2.0|install spatie/laravel-backup 6.2.1|install spatie/laravel-backup 6.3.0|install spatie/laravel-backup 6.3.1
    - brackets/craftable 5.0.x-dev requires spatie/laravel-backup ^6.0 -> satisfiable by spatie/laravel-backup[6.0.0, 6.0.1, 6.0.2, 6.0.3, 6.0.4, 6.0.5, 6.0.6, 6.0.7, 6.1.0, 6.1.1, 6.1.2, 6.2.0, 6.2.1, 6.3.0, 6.3.1, 6.4.0, 6.4.1, 6.4.2, 6.5.0, 6.5.1, 6.6.0, 6.6.1].
    - spatie/laravel-backup 6.4.0 requires league/flysystem ^1.0.49 -> satisfiable by league/flysystem[1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.1.x-dev].
    - spatie/laravel-backup 6.4.1 requires league/flysystem ^1.0.49 -> satisfiable by league/flysystem[1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.1.x-dev].
    - spatie/laravel-backup 6.4.2 requires league/flysystem ^1.0.49 -> satisfiable by league/flysystem[1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.1.x-dev].
    - spatie/laravel-backup 6.5.0 requires league/flysystem ^1.0.49 -> satisfiable by league/flysystem[1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.1.x-dev].
    - spatie/laravel-backup 6.5.1 requires league/flysystem ^1.0.49 -> satisfiable by league/flysystem[1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.1.x-dev].
    - spatie/laravel-backup 6.6.0 requires league/flysystem ^1.0.49 -> satisfiable by league/flysystem[1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.1.x-dev].
    - spatie/laravel-backup 6.6.1 requires league/flysystem ^1.0.49 -> satisfiable by league/flysystem[1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.1.x-dev].
    - Can only install one of: league/flysystem[1.0.49, 1.0.46].
    - Can only install one of: league/flysystem[1.0.50, 1.0.46].
    - Can only install one of: league/flysystem[1.0.51, 1.0.46].
    - Can only install one of: league/flysystem[1.0.52, 1.0.46].
    - Can only install one of: league/flysystem[1.0.53, 1.0.46].
    - Can only install one of: league/flysystem[1.0.54, 1.0.46].
    - Can only install one of: league/flysystem[1.0.55, 1.0.46].
    - Can only install one of: league/flysystem[1.0.56, 1.0.46].
    - Can only install one of: league/flysystem[1.1.x-dev, 1.0.46].
    - Installation request for league/flysystem (locked at 1.0.46) -> satisfiable by league/flysystem[1.0.46].

Installation failed, reverting ./composer.json to its original content.

**Comment by palypster** [comment]
well, it looks like some package you are using is not ready for Laravel 6?

**Comment by bachilli** [comment]
@palypster No. It's a fresh Laravel 6 installation

**Comment by palypster** [comment]
It's fixed now
