### ISSUE TITLE
AdminListing:: make traslatable and search 

### ISSUE THREAD

**Issue by rewuxiin** [BRACKETS-by-TRIAD/craftable#158]
Hey. Great Craftable Solution.
However, it saddens me that there are no two solutions for languages ​​- storing in json and storing in a separate table **post** and **post_langs** or **post_translations**.

I use storage in a separate table, but now I don’t know how to use your

`AdminListing :: create (Post :: class) -> processRequestAndGet ();`

to get the list output for the language and for ajax search

**Comment by palypster** [comment]
You can use modifyQuery parameter to join post_langs or post_translations

**Comment by rewuxiin** [comment]
Thanks.
I read docs at page real https://getcraftable.com/docs/5.0/relations, I think examples will help me
