### ISSUE TITLE
Version 6 - Why Postgres 9.5+? Is it work with 9.2.24?

### ISSUE THREAD

**Issue by allanfreitas** [BRACKETS-by-TRIAD/craftable#159]
I'm with a client server, and I'm setting up a new laravel project with Craftable version 6.

Why Postgres 9.5+ is a requirement? Is it work with 9.2.24?

**Comment by palypster** [comment]
It's may not work properly on lower version, because Craftable uses JSON database types introduced in 9.5+.

**Comment by allanfreitas** [comment]
Thanks @palypster . I will use mysql for now.
