### ISSUE TITLE
change admin template

### ISSUE THREAD

**Issue by devakumetsu** [BRACKETS-by-TRIAD/craftable#160]
Hi, how can i change the admin template for onether one like `Materialize Pro`; without affecting the product update.
 i try with the boot method: 
        `$this->loadViewsFrom(__DIR__.'/resources/brackets/admin-ui/resources/views/admin/layout', 'brackets');`

and then recrate the default.blade and master.blade without success.

Can someone helpme with this?

Regards.-

**Comment by palypster** [comment]
See: https://laravel.com/docs/6.x/packages#views

So you don't need to call any method - just place new layout file in specific location:

`resources/views/vendor/brackets/admin-ui/resources/views/admin/layout/[blade_name].blade.php`
