### ISSUE TITLE
Property or method "isClickedAll" is not defined on the instance but referenced during render.

### ISSUE THREAD

**Issue by Trexology** [BRACKETS-by-TRIAD/craftable#161]
Hi I just upgraded from craftable v3 to v4, I tried to regenerated my old view using the artisan command but the vue component does not load.

there are quite a few [vue warn] in the inspect element

[Vue warn]: Property or method "isClickedAll" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

[Vue warn]: Property or method "isClickedAll" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

what am I missing? I already did view:clear and cache:clear

**Comment by Trexology** [comment]
I also realize the Tableview component only fail to load when there are data in my database...

**Comment by RichardDominik** [comment]
Hi, thanks for feedback. Try increase version number of "craftable" in package.json to ^2.1 and run npm install, we will update our upgrade guide.

**Comment by Trexology** [comment]
OH YES, it is working... thanks
