### ISSUE TITLE
 Cannot declare class CreateMediaTable, because the name is already in use

### ISSUE THREAD

**Issue by felipesmendes** [BRACKETS-by-TRIAD/craftable#164]
I'm trying to use craftable with laravel 6.0  and gotting this erro in the end of installation:

`Cannot declare class CreateMediaTable, because the name is already in use`

Its a new project with blank database.

Someone could please help me to solve it?

**Comment by palypster** [comment]
Somehow it get to the state, that in your project there is this class twice. Just remove one occurence.

**Comment by moesaid** [comment]
delete your migration files and clear your database 
`php artisan craftable:install`

**Comment by MaximilllianBuelow** [comment]
After the error occurred:
I coppied the thable "medias" and renamed it to "medias".
After that i removed all migrattion files and tables, except the "medias" table.

Then just start the installation again and it will run.

**Comment by lalang** [comment]
you have to add "Create" in the name of function like this:

class CreateCarouselTable extends Migration
{
......
}
