### ISSUE TITLE
admin:generate dont create classes with database columns

### ISSUE THREAD

**Issue by nickyapp** [BRACKETS-by-TRIAD/craftable#168]
Hi,
i have my table work_requests,
when i run php artisan admin:generate WorkRequests the command create the model fillable and controller methods empty, can anyone help me ?

obviously i got the columns in the migration file.
![image](https://user-images.githubusercontent.com/34491798/69593435-ed30b900-0fd7-11ea-9821-d0df808fac3b.png)

example

![image](https://user-images.githubusercontent.com/34491798/69593281-93c88a00-0fd7-11ea-84f3-2b166a4fc934.png)

**Comment by codeurfou** [comment]
Hello. What if you try `php artisan admin:generate work_requests` instead of `php artisan admin:generate WorkRequests` ?

**Comment by nickyapp** [comment]
> Hello. What if you try `php artisan admin:generate work_requests` instead of `php artisan admin:generate WorkRequests` ?
Solved
i written bad the admin:generate command.

always admin:generate "table_name"
