### ISSUE TITLE
Multiselect with object

### ISSUE THREAD

**Issue by oalencar** [BRACKETS-by-TRIAD/craftable#17]
Hi! 
First, i need to congratulate you for the awesome project.

I'm having trouble to use the multiselect to make relationships. I need use it with KEY => VALUE, but it's not working, even consulting the multiselect documentation. Can you help me?

**Comment by matejminar** [comment]
Hello, we actually got this implemented in user profile.
In Manage access, click to edit user and then the last form item is 'Roles' select.

Take a look inside
`resources/views/admin/user/components/form-elements.blade.php`
`app/Http/Controllers/Admin/UsersController.php@edit`
to see how it can be done.
