### ISSUE TITLE
is there any way i can modify layouts

### ISSUE THREAD

**Issue by motailab** [BRACKETS-by-TRIAD/craftable#170]
i can't see any proper documentation about modifying layouts, like footer, menu  etc. :)

**Comment by codeurfou** [comment]
Hello,

If I remember well what I did...

- I just copied files from `vendor/brackets/admin-ui/resources/*` to `resources/admin/*`and edit them.
- Maybe you gonna have to change path in all the `@include`s  into your new pasted files...

Keep me in touch !

**Comment by motailab** [comment]
Thank you :)

**Comment by palypster** [comment]
Laravel provide this concept of overriding the views of any vendor (package) including Craftable. Check out more info in the oficial docs: https://laravel.com/docs/6.x/packages#views (`Overriding Package Views`)

**Comment by elshobokshy** [comment]
@palypster what if we want to keep the same views format but just make minor changes ? Could you kindly explain how to properly and cleanly export all views and necessary vue files ?

**Comment by codeurfou** [comment]
Hello, As I told before, and as @palypster you have to copy templates in your resources directory and edit them.

> * I just copied files from `vendor/brackets/admin-ui/resources/*` to `resources/admin/*`and edit them.
> * Maybe you gonna have to change path in all the `@include`s  into your new pasted files...

**Comment by elshobokshy** [comment]
@codeurfou copying only `admin-ui/resources/admin/*` views files is not enough. As it doesn't contain, for example, the login form view as well as many others. I'd need to copy all resources in all folders to have a whole copy of all of the views?

**Comment by palypster** [comment]
@elshobokshy sorry, I think we don't know the answer, this is something we did not have in mind when we developed.

I can help you navigate though what packages have SOME frontend, it might help you with investigation:
- https://github.com/BRACKETS-by-TRIAD/admin-ui - contains basic layout view
- https://github.com/BRACKETS-by-TRIAD/craftable-frontend - contains basic vue components, mixins, basically whole JS & CSS
- https://github.com/BRACKETS-by-TRIAD/admin-auth - contains views related to the authentication (login, forgotten password, ...)
- https://github.com/BRACKETS-by-TRIAD/admin-translations - contains view related to the translation manager

**Comment by zhed** [comment]
in case someone in future search about this topic,
here is the way i solve it.

1. - Copy **admin** folder inside _vendor/brackets/admin-ui/resources/views/_
2. - Make folder **vendor/brackets/admin-ui** inside _resources/views/_
3. - Paste the copied *admin* folder inside *admin-ui* folder

![Screen Shot 2020-11-29 at 13 52 39](https://user-images.githubusercontent.com/3147098/100535296-326e7300-324a-11eb-8bc5-5f37e836abc7.png)

Happy override...
