### ISSUE TITLE
Call to a member function count() on null

### ISSUE THREAD

**Issue by prappo** [BRACKETS-by-TRIAD/craftable#171]
First of all, Thank you for making this awesome package. 
I followed this documentation https://getcraftable.com/docs/5.0/media to upload media but whenever I tried to save it got an error.
`Call to a member function count() on null`

![image](https://user-images.githubusercontent.com/3511421/70851303-a0951b00-1ebd-11ea-801f-9ef7d4a0fca7.png)

**Comment by palypster** [comment]
Hello, thank you.

Without the code we cannot help you. Anyway, I recommend you to investigate working demo:
https://demo.getcraftable.com/admin/posts
and its sources:
https://github.com/BRACKETS-by-TRIAD/craftable-demo

**Comment by TheGodFather05** [comment]
same problem for me. i think it has sth to do with the upgrade
here is my code 
      model:
`<?php

namespace App\Models;

use Brackets\Media\HasMedia\AutoProcessMediaTrait;
use Brackets\Media\HasMedia\HasMediaCollectionsTrait;
use Brackets\Media\HasMedia\ProcessMediaTrait;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\Conversion\Conversion;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\Models\Media;

class Logement extends Model implements HasMedia
{

    use HasMediaCollectionsTrait;
    use AutoProcessMediaTrait;
    use ProcessMediaTrait;

    protected $fillable = [
        'type_logement',
        'ville',
        'quartier',
        'nombre_chambres',
        'nombre_douches',
        'prix',
        'parking',
        'disponible',
        'description',
        'id_agent',
        'gallerie',

    ];


    protected $dates = [
        'created_at',
        'updated_at',

    ];

    protected $appends = ['resource_url'];

    /* ************************ ACCESSOR ************************* */

    public function getResourceUrlAttribute()
    {
        return url('/admin/logements/' . $this->getKey());
    }

    /**
     * Set the polymorphic relation.
     *
     * @return mixed
     */
    public function media()
    {
        // TODO: Implement media() method.
    }

    /**
     * Move a file to the medialibrary.
     *
     * @param string|\Symfony\Component\HttpFoundation\File\UploadedFile $file
     *
     * @return \Spatie\MediaLibrary\FileAdder\FileAdder
     */
    public function addMedia($file)
    {
        // TODO: Implement addMedia() method.
    }

    /**
     * Copy a file to the medialibrary.
     *
     * @param string|\Symfony\Component\HttpFoundation\File\UploadedFile $file
     *
     * @return \Spatie\MediaLibrary\FileAdder\FileAdder
     */
    public function copyMedia($file)
    {
        // TODO: Implement copyMedia() method.
    }

    /**
     * Determine if there is media in the given collection.
     *
     * @param $collectionMedia
     *
     * @return bool
     */
    public function hasMedia(string $collectionMedia = ''): bool
    {
        // TODO: Implement hasMedia() method.
    }

    /**
     * Get media collection by its collectionName.
     *
     * @param string $collectionName
     * @param array|callable $filters
     *
     * @return \Illuminate\Support\Collection
     */
    public function getMedia(string $collectionName = 'default', $filters = [])
    {
        // TODO: Implement getMedia() method.
    }

    /**
     * Remove all media in the given collection.
     *
     * @param string $collectionName
     */
    public function clearMediaCollection(string $collectionName = 'default')
    {
        // TODO: Implement clearMediaCollection() method.
    }

    /**
     * Remove all media in the given collection except some.
     *
     * @param string $collectionName
     * @param \Spatie\MediaLibrary\Media[]|\Illuminate\Support\Collection $excludedMedia
     *
     * @return string $collectionName
     */
    public function clearMediaCollectionExcept(string $collectionName = 'default', $excludedMedia = [])
    {
        // TODO: Implement clearMediaCollectionExcept() method.
    }

    /**
     * Determines if the media files should be preserved when the media object gets deleted.
     *
     * @return bool
     */
    public function shouldDeletePreservingMedia()
    {
        // TODO: Implement shouldDeletePreservingMedia() method.
    }

    /**
     * Cache the media on the object.
     *
     * @param string $collectionName
     *
     * @return mixed
     */
    public function loadMedia(string $collectionName)
    {
        // TODO: Implement loadMedia() method.
    }

    public function addMediaConversion(string $name): Conversion
    {
        // TODO: Implement addMediaConversion() method.
    }

    public function registerMediaConversions(Media $media = null)
    {
        // TODO: Implement registerMediaConversions() method.
    }

    public function registerMediaCollections()
    {
        // TODO: Implement registerMediaCollections() method.
        $this->addMediaCollection("gallerie")
            ->accepts('image/*')
            ->maxNumberOfFiles(20);
    }

    public function registerAllMediaConversions()
    {
        // TODO: Implement registerAllMediaConversions() method.
    }
}
`

     Controller:
`  $sanitized = $request->validated();
$logement = Logement::create($sanitized);`

**Comment by TheGodFather05** [comment]
i'm using version 5.1 of craftable

**Comment by TheGodFather05** [comment]
problem solved. in the model the only function i have to implement is the `registerMediaCollections()` function
