### ISSUE TITLE
how publish your views?

### ISSUE THREAD

**Issue by desarollomariscoselrey** [BRACKETS-by-TRIAD/craftable#173]
i mean i want to modify the headers and footer of the app.
but i dont know how to publish the blade files
can you help me?

**Comment by desarollomariscoselrey** [comment]
i found the solution 
`php artisan vendor:publish`

**Comment by amoradel** [comment]
> i found the solution `php artisan vendor: publish`

Hola @desarollomariscoselrey, recordas que provider utilizaste?

**Comment by timoransky** [comment]
Hu @amoradel, if you want to edit craftable layout files, you need to run `php artisan vendor:publish` and select `Brackets\AdminUI\AdminUIServiceProvider`. This will publish all `*.blade.php` files from craftable into `/resources/views/vendor/brackets/admin-ui/admin`.

**Comment by amoradel** [comment]
> Hi @amoradel, if you want to edit craftable layout files, you need to run `php artisan vendor:publish` and select `Brackets\AdminUI\AdminUIServiceProvider`. This will publish all `*.blade.php` files from craftable into `/resources/views/vendor/brackets/admin-ui/admin`.

Hi @timoransky, I need to edit the file login.blade.php in the directory vendor/brackets/admin-auth/resources/views/admin/auth/login.blade.php. Can I run any command to do this?

**Comment by amoradel** [comment]
Hi @timoransky, I have published the provider `Brackets\AdminAuth\AdminAuthServiceProvider`, but only the `lang` folder has been published.

![image](https://user-images.githubusercontent.com/10636860/207358348-a5a260bb-637f-4852-96de-3947c86101ef.png)
