### ISSUE TITLE
Unathorized typo?

### ISSUE THREAD

**Issue by willpower232** [BRACKETS-by-TRIAD/craftable#174]
I've just come across the mis-spelling of unauthorized in admin-auth.

https://github.com/BRACKETS-by-TRIAD/admin-auth/blob/7fba5cd2798e0e5598527b284b68a0493b83cdf1/src/Http/Middleware/CanAdmin.php#L48

Not major I know but I thought I would mention.

**Comment by RichardDominik** [comment]
Hi, thanks for your feedback. Issue is now resolved in latest admin-auth release.
