### ISSUE TITLE
Hell craftable

### ISSUE THREAD

**Issue by atta1234** [BRACKETS-by-TRIAD/craftable#178]
this is very nice admin panel,but it need more clear documentation ,may be few video about file uploading etc

**Comment by palypster** [comment]
Hello,

have you follow the documentation here:
https://www.getcraftable.com/docs/5.0/media

?

To sum up, you need to:

1. add to your eloquent model ability to attach media
1. define collections (and optionally conversions) on this eloquent model
1. add mediaCollections to your *-form.js
1. add media uploader to your blade form
