### ISSUE TITLE
Empty form element

### ISSUE THREAD

**Issue by mrsherlock88** [BRACKETS-by-TRIAD/craftable#180]
Hi Team,

After generate user ok, I add new migration table, all step is ok but when login and see the form does not have any input, there's only "Add" button.

I delete the `form-element.blade.php` then re-run `php artisan admin:generate:form game`, it said the form is successful created, other're exists, but the file is empty.

This is my migration:
```
       Schema::create('game', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->integer('grid_id');
            $table->string('type');
            $table->integer('hint_count');
            $table->date('start_game')->nullable();
            $table->text('current_puzzle')->nullable();
            $table->timestamps();
        });
```

My device: Windows Server 2019, Wamp 3.1.9 64bit, PHP 7.3.5.

**Comment by palypster** [comment]
Have you run `npm run dev` after generation?

Btw, you should name the tables in plural -> `games` (it may cause some problems if you don't).
