### ISSUE TITLE
Installing Craftable to the existing project is broken

### ISSUE THREAD

**Issue by MohammedAlkutrani** [BRACKETS-by-TRIAD/craftable#181]
while I'm trying to install to an existing project by this command 
`composer require brackets/craftable` 
I got an error that said `translation.loader` must be real object or string, and I fixed that by clearing project cache, but now I'm facing another one 

`SQLSTATE[42S02]: Base table or view not found: 1146 Table 'connect_store_admin.translations' doesn't exist (SQL: select * from `translations` where `namespace` = * and `group` = * and `translations`.`deleted_at` is null)`

thank you

**Comment by jeff-99** [comment]
@MohammedAlkutrani I'm having the same problem. How did you fix it ?

**Comment by MohammedAlkutrani** [comment]
@jeff-99 I didn’t fix it although I closed it because nobody answered me. However, it work fine after I installed it in a fresh project .

**Comment by elshobokshy** [comment]
Any idea if this is going to get fixed ? I was looking forward to install craftable.

**Comment by janbiasi** [comment]
Any updates on this one?

**Comment by waqasahmad008** [comment]
Any updates still getting same issue.

**Comment by ArcheeNic** [comment]
I do not know why this happens.
Necessary migration not running https://github.com/BRACKETS-by-TRIAD/admin-translations/blob/master/database/migrations/create_translations_table.php.stub

Solved the problem by manually creating this migration.

**Comment by Khalid3bdallah** [comment]
I have the same problem, why this issue was closed without a resolution?
