### ISSUE TITLE
How to create CRUD for 'standard' Laravel users

### ISSUE THREAD

**Issue by rabol** [BRACKETS-by-TRIAD/craftable#182]
Hi

I kind of like the separation of admin and normal users, but I would need to a wy to modify users in the admin panel, so I tried to generate a  CRUD for that

´´´
php artisan admin:generate Users
´´´

That does not work.

As Users is part of the standard Laravel I think a 'package' for managing 'normal' users would be great or a 'tutorial' in the documentation

**Comment by palypster** [comment]
Have you tried `php artisan admin:generate users` (with small `u`)?
