### ISSUE TITLE
IndexAdminUser authorize ?

### ISSUE THREAD

**Issue by elshobokshy** [BRACKETS-by-TRIAD/craftable#191]
Hello, 

Just wondering where are the `Gate::define` defined for the `Gate::allows('admin.XXX')` ?

@palypster any idea ? 
 
Thanks ! :)

**Comment by palypster** [comment]
We use https://github.com/spatie/laravel-permission so instead of gates we use permissions and they are defined in the database.

**Comment by elshobokshy** [comment]
@palypster would be awesome to have a doc where everything is explained lol, but I suppose you guys have other priorities ^^ Thanks for the reply!

**Comment by palypster** [comment]
Thank you. Actually, we had this documented in some previous versions of Craftable but it somehow disappeared. I reopen this as we need to include this in the current version of the documentation.

**Comment by fernando1419** [comment]
Please guys, could you please give us some documentation about roles and permissions using craftable?. I know you suggest using laravel-permissions, but I can't get it work whitin craftable.
I am really stuck at this point as I imagine other people are. Thanks a lot.

**Comment by elshobokshy** [comment]
@fernando1419 they're not suggesting to use that package, they're already using it. I overcame my problems by doing deep research and understanding everything by myself, unfortunately the project isn't active enough to offer help, you'd have to do it yourself :/ Take their project as a starting point and go from there

**Comment by fernando1419** [comment]
@elshobokshy Do you please have any code I can look into?, I stuck at this point, especially trying to use my own users table and not the default 'admin_users' the package provides. Thank you.

**Comment by palypster** [comment]
@fernando1419 Hi, I have replied you in the other issue you have created for your problem. Let's not overwhelm this issue with unrelated comments, ok?

About the delay in reactions - we are truly sorry, we're doing our best, but you must understand we also have other priorities.

**Comment by fernando1419** [comment]
I understand you have other priorities and I really appreciate that. I didn't realize I was "overwhelming" the issue, I was just asking for some help. Sorry about that.

**Comment by elshobokshy** [comment]
@fernando1419 I can't share code when I don't know how far you're at/what's your exact problem. Can you share with me? I'll try to help as much as I can to my knowledge.

**Comment by fernando1419** [comment]
@elshobokshy Hi, I've sent you an email, Did you receive it?. Thanks a lot.

**Comment by RichardDominik** [comment]
Hi, thanks for your feedback. Information was added to documentation.
