### ISSUE TITLE
Question: how to add a language?

### ISSUE THREAD

**Issue by realtebo** [BRACKETS-by-TRIAD/craftable#194]
I'm reading this page of the official doc: https://getcraftable.com/docs/5.0/translations 

It misses one important info: how to add a new language? I started from scratch and my craftable project is localized in English. How can I add Italian, for example?

**Comment by ludioao** [comment]
I faced same issue

**Comment by palypster** [comment]
It's very simple, just add a new locale within `config/translatable.php`

**Comment by RichardDominik** [comment]
Hi, thanks for your feedback. Information was added to documentation.
