### ISSUE TITLE
how to search on Eloquent Relationships with craftable?

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#196]
I need to search on eloquent relationships the name of the store, each store has many store boxes and each box is linked to a store id using store_id field.

My store box controller now:

```
    public function index(IndexStoreBox $request)
    {
        // create and AdminListing instance for a specific model and
        $data = AdminListing::create(Box::class)->processRequestAndGet(
            // pass the request with params
            $request,

            // set columns to query
            ['box_name','category_id', 'currency_id', 'id', ''store_id'],

            // set columns to searchIn
            ['store_id'],

            function ($query) use ($request) {

                $query->with(['store','category','currency']);

                if ($request->has('stores')) {
                    $query->whereIn('store_id', $request->get('stores'));
                }

                if ($request->has('categories')) {
                    $query->whereIn('category_id', $request->get('categories'));
                }

                if ($request->has('currencies')) {
                    $query->whereIn('currency_id', $request->get('currencies'));
                }

            }


        );

        if ($request->ajax()) {
            if ($request->has('bulk')) {
                return [
                    'bulkItems' => $data->pluck('id')
                ];
            }
            return ['data' => $data];
        }

        return view('admin.box.index', ['data' => $data]);
    }

```

If I search by the id of the store it shows the store without any problem, but I need to search by the name of the store not the id...

how can I search on eloquent relationship for the store name using typing the name of the store in the search instead of the id?

thanks for any tips!

**Comment by rapgithub** [comment]
I am using this link below for the doc information but there is no information regarding search on a relationed field:

https://www.getcraftable.com/docs/5.0/relations

any tip? thanks

**Comment by zulbil** [comment]
@rapgithub Did you find a solution for that ? I'm currently facing the same problem

**Comment by ryan-k-t** [comment]
I had the same sort of dilemma. What I did was add joins in the modifyQuery argument 

`$query->join('stores', 'stores.id', '=', 'store_boxes.store_id');`

and then added the relational fields to the searchIn array.
`
// set columns to searchIn
['store_id', 'stores.name'],
`

**Comment by palypster** [comment]
@RichardDominik can you please extend the example:
https://www.getcraftable.com/docs/5.0/relations
and show how to search in related models?

**Comment by RichardDominik** [comment]
Hi, information about searching in related models was added to the example in the documentation.
