### ISSUE TITLE
Laravel 5.6 support

### ISSUE THREAD

**Issue by paulhuisman** [BRACKETS-by-TRIAD/craftable#20]
Hi guys,

Great tool! Any idea when Laravel 5.6 will be supported?

**Comment by palypster** [comment]
Hey @paulhuisman, thank you. Our initial plan was to stay with the 5.5 version because its' a LTS version. Our ambition with the Craftable is to provide a very stable administration kit.

But we are reconsidering pros & cons this option as well. We'll let you know.

**Comment by palypster** [comment]
Hi Paul, I just want to let you know the discussion still continues and we are very open to keep two branches - one that stick to the LTS versions of laravel (currently 5.5 - this is what we require ourselves) and second that will always use the latest laravel (currently 5.6 - this is what community wants :P ). We are discussion how big overhead this is. Will let you know.

**Comment by Omegatcu** [comment]
Any news on this?

**Comment by palypster** [comment]
We're playing around with it, prototyping. Still work in progress.

**Comment by palypster** [comment]
Great news guys, Laravel 5.6 support was just introduced.
https://docs.getcraftable.com/v2/#/upgrade-guide?id=upgrade-laravel-55-gt-56

Thanks a lot for your patience.
