### ISSUE TITLE
Craftable after fresh installation laravel 6 not working 

### ISSUE THREAD

**Issue by jqr91** [BRACKETS-by-TRIAD/craftable#200]
Hi,
I installed craftable on clean install of laravel 6 but it doesn't work.
 
<img width="1270" alt="Schermata 2020-03-01 alle 11 09 47" src="https://user-images.githubusercontent.com/8181631/75623719-4139d380-5bad-11ea-8897-a74f5f6316e8.png">

does anyone know how to fix it?

Thanks

**Comment by francosalcedo** [comment]
execute command
npm run dev

**Comment by pooinfire** [comment]
hi, I'm having the same issue and npm run dev does not help. using Laravel 6.x . Any workaround or manual setup? Also I noticed the admin can be only loaded from ../public/admin/login ? couldnt that be the issue? Thanks

**Comment by palypster** [comment]
Yes, this is definitely the issue. You have to point your apache/ngnix server to te /public folder and not the root:
https://laravel.com/docs/7.x/installation#configuration

> After installing Laravel, you should configure your web server's document / web root to be the public directory.
