### ISSUE TITLE
Module build failed (admin.scss)

### ISSUE THREAD

**Issue by louisdj** [BRACKETS-by-TRIAD/craftable#201]
Hi

When I create a new project, during the npm run dev part of the installation, I receive the following error:
`98% after emitting SizeLimitsPlugin

 ERROR  Failed to compile with 7 errors                                                                                                                                                                                           8:51:47 AM

These relative modules were not found:

* ../../../node_modules/craftable/scss/img/correct.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/craftable/scss/img/envelope.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/craftable/scss/img/error.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/craftable/scss/img/lock.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/img/correct.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/img/error-triangle.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
* ../../../node_modules/img/error.png in ./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss
                                                                                    Asset      Size     Chunks             Chunk Names
                                                                             /css/app.css   0 bytes    /js/app  [emitted]  /js/app
                                                                             /js/admin.js  3.85 MiB  /js/admin  [emitted]  /js/admin
                                                                               /js/app.js   597 KiB    /js/app  [emitted]  /js/app
 fonts/vendor/@coreui/icons/CoreUI-Icons-Linear-Free.eot?089ab3c11c572362d088083c561cfa55  20.4 KiB             [emitted]
 fonts/vendor/@coreui/icons/CoreUI-Icons-Linear-Free.svg?4b57c6a5567c9ef09913983f82904faa  65.3 KiB             [emitted]
 fonts/vendor/@coreui/icons/CoreUI-Icons-Linear-Free.ttf?1bc3764815bb391a16771c42c6e460ec  20.2 KiB             [emitted]
fonts/vendor/@coreui/icons/CoreUI-Icons-Linear-Free.woff?0087dce419a7376eb06c837f740d31eb  20.3 KiB             [emitted]
       fonts/vendor/font-awesome/fontawesome-webfont.eot?674f50d287a8c48dc19ba404d20fe713   162 KiB             [emitted]
       fonts/vendor/font-awesome/fontawesome-webfont.svg?912ec66d7572ff821749319396470bde   434 KiB             [emitted]
       fonts/vendor/font-awesome/fontawesome-webfont.ttf?b06871f281fee6b241d60582ae9369b9   162 KiB             [emitted]
     fonts/vendor/font-awesome/fontawesome-webfont.woff2?af7ae505a9eed503f8b8e6982036873e  75.4 KiB             [emitted]
      fonts/vendor/font-awesome/fontawesome-webfont.woff?fee66e712a8a08eef5805a46892932ad  95.7 KiB             [emitted]
    fonts/vendor/simple-line-icons/Simple-Line-Icons.eot?f33df365d6d0255b586f2920355e94d7    53 KiB             [emitted]
    fonts/vendor/simple-line-icons/Simple-Line-Icons.svg?2fe2efe63441d830b1acd106c1fe8734   233 KiB             [emitted]
    fonts/vendor/simple-line-icons/Simple-Line-Icons.ttf?d2285965fe34b05465047401b8595dd0  52.8 KiB             [emitted]
  fonts/vendor/simple-line-icons/Simple-Line-Icons.woff2?0cb0b9c589c0624c9c78dd3d83e946f6  29.4 KiB             [emitted]
   fonts/vendor/simple-line-icons/Simple-Line-Icons.woff?78f07e2c2a535c26ef21d95e41bd7175  79.4 KiB             [emitted]
               images/vendor/trumbowyg/dist/ui/icons.svg?c5eb101fca1f32d184ac5e0d270e1af1  30.8 KiB             [emitted]

ERROR in ./resources/sass/admin/admin.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleNotFoundError: Module not found: Error: Can't resolve '../../../node_modules/craftable/scss/img/correct.png' in '<LOCAL_FOLDER>/resources/sass/admin'
    at <LOCAL_FOLDER>/node_modules/webpack/lib/Compilation.js:925:10
    at <LOCAL_FOLDER>/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at <LOCAL_FOLDER>/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at <LOCAL_FOLDER>/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at <LOCAL_FOLDER>/node_modules/neo-async/async.js:2830:7
    at <LOCAL_FOLDER>/node_modules/neo-async/async.js:6877:13
    at <LOCAL_FOLDER>/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<LOCAL_FOLDER>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<LOCAL_FOLDER>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<LOCAL_FOLDER>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<LOCAL_FOLDER>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<LOCAL_FOLDER>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<LOCAL_FOLDER>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (<LOCAL_FOLDER>/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
    at <LOCAL_FOLDER>/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
 @ ./resources/sass/admin/admin.scss

ERROR in ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss)
Module not found: Error: Can't resolve '../../../node_modules/craftable/scss/img/correct.png' in '<LOCAL_FOLDER>/resources/sass/admin'
 @ ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss) 7:398330-398393
 @ ./resources/sass/admin/admin.scss

ERROR in ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss)
Module not found: Error: Can't resolve '../../../node_modules/craftable/scss/img/envelope.png' in '<LOCAL_FOLDER>/resources/sass/admin'
 @ ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss) 7:399360-399424
 @ ./resources/sass/admin/admin.scss

ERROR in ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss)
Module not found: Error: Can't resolve '../../../node_modules/craftable/scss/img/error.png' in '<LOCAL_FOLDER>/resources/sass/admin'
 @ ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss) 7:398471-398532
 @ ./resources/sass/admin/admin.scss

ERROR in ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss)
Module not found: Error: Can't resolve '../../../node_modules/craftable/scss/img/lock.png' in '<LOCAL_FOLDER>/resources/sass/admin'
 @ ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss) 7:399512-399572
 @ ./resources/sass/admin/admin.scss

ERROR in ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss)
Module not found: Error: Can't resolve '../../../node_modules/img/correct.png' in '<LOCAL_FOLDER>/resources/sass/admin'
 @ ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss) 7:405708-405756 7:416514-416562
 @ ./resources/sass/admin/admin.scss

ERROR in ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss)
Module not found: Error: Can't resolve '../../../node_modules/img/error-triangle.png' in '<LOCAL_FOLDER>/resources/sass/admin'
 @ ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss) 7:419982-420037
 @ ./resources/sass/admin/admin.scss

ERROR in ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss)
Module not found: Error: Can't resolve '../../../node_modules/img/error.png' in '<LOCAL_FOLDER>/resources/sass/admin'
 @ ./resources/sass/admin/admin.scss (./node_modules/css-loader??ref--6-2!./node_modules/postcss-loader/src??postcss1!./node_modules/resolve-url-loader??ref--6-4!./node_modules/sass-loader/dist/cjs.js??ref--6-5!./resources/sass/admin/admin.scss) 7:405837-405883 7:416379-416425
 @ ./resources/sass/admin/admin.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/louis.dejaeger/.npm/_logs/2020-03-04T07_51_50_023Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/louis.dejaeger/.npm/_logs/2020-03-04T07_51_50_120Z-debug.log`

After this, when I try to boot the application, the home is working, but when I browse to the /admin/login I receive the following error:

`Facade\Ignition\Exceptions\ViewException
Unable to locate Mix file: /css/admin.css. (View: <LOCAL_FOLDER>/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php)
http://localhost:8000/admin/login`

I'm running on Mac OS Catalina.

**Comment by RichardDominik** [comment]
Hi, thanks for feedback. This issue is now fixed in craftable-frontend (npm version 2.1.8). Try to run `npm install craftable` to fix this issue.
