### ISSUE TITLE
Media not added to datatabase

### ISSUE THREAD

**Issue by elshobokshy** [BRACKETS-by-TRIAD/craftable#202]
Hello.

The media I upload are added to the folder, but when I submit the form the `media` table in the database is not being updated. I can't seem to guess why, even tho the model I created is similar to the ones that exists.

By that I mean : 

1) I created in the Form.js `mediaCollections: ['topics_gallery']`
2) I added the media collections in my blade form the same way that it's been added in the post model : 
```
@include('admin.includes.media-uploader', [
    'mediaCollection' => app(App\Models\Topics::class)->getMediaCollection('topics_gallery'),
    'label' => 'Ajoutez une photo'
])
```
etc etc

I'm trying to debug so I went ahead and printed out the request, but as it turns out the form isn't seeing the media in the request. What to do? How to properly debug this?

**Comment by reeouw** [comment]
the same with me! 
In the Post model it works fine, but when I created a new model (Product) and I debugged it turn out I can see the gallery from $request

**Comment by reeouw** [comment]
I just found the solution, just run 

[npm run dev](url)  

we need to compile it again after we add the `mediaCollections: ['gallery']` in Form.js :)

**Comment by elshobokshy** [comment]
@reeouw yes thank you!! I had npm run watch running but wasn't seeing the changes anyway, had to rerun it, thanks! :D
