### ISSUE TITLE
How to change upload disk to AWS S3

### ISSUE THREAD

**Issue by reeouw** [BRACKETS-by-TRIAD/craftable#203]
i was exploring about upload disk in the vendor folder, but I still can't get the upload disk config file.

Anyone know how to upload the media into AWS S3?

**Comment by palypster** [comment]
We use Spatie's package under the hood. Check out their docs:
https://docs.spatie.be/laravel-medialibrary/v7/working-with-media-collections/defining-media-collections/#using-a-specific-disk
