### ISSUE TITLE
Error 403 with new CRUD admin

### ISSUE THREAD

**Issue by tuxfamily** [BRACKETS-by-TRIAD/craftable#209]
Hello.

I'm giving a try to your promising project but... :)

I strictly followed the install guide, but I'm unable to enter the new created CRUD module.

I'm using the lastest version of everything and here it's what i've done:
- new craftable project
- login with the default admin
- new 'articles' table created directly in the DB (via PMA)
- executed `php artisan admin:generate articles`
- answered `yes`at the permissions prompt
- executed `npm run dev`
- tried to access the new module > error 403
- tried to logout and log-in again > error 403
- tried with a new user > error 403

I've tried several time, starting with a new project each time, and what I've noticed is that if I create the tables and modules **before** the first login, I can access the modules but once I have logged in, it's "too late", I got this error, no matter what I done.

I checked in the DB, the permissions are well created and assigned, so is there something to do in order to apply these news permissions?

Thanks.

**Comment by palypster** [comment]
May be related to https://github.com/BRACKETS-by-TRIAD/craftable/issues/155 Can you try to change the cache driver?

**Comment by tuxfamily** [comment]
Yes, confirmed, it's related.
Changing cache to `array` works, but `php artisan optimize:clear` or `php artisan cache:clear` has not effect.

**Comment by palypster** [comment]
One way or another, if there is a bug, it's related to https://github.com/spatie/laravel-permission so you need to create new issue there I think.
