### ISSUE TITLE
Add permissions to users or roles

### ISSUE THREAD

**Issue by emperorjm** [BRACKETS-by-TRIAD/craftable#21]
So I created a CRUD and generated the permission but I am unable to access the CRUD because I don't have the permission to do so and there are no screens which allow me to do so.

What do I need to do?

**Comment by emperorjm** [comment]
I had to run "**npm run dev**" which is actually in the documentation. Still I need to know how to add permissions to users and to roles.

**Comment by palypster** [comment]
Hello @emperorjm , did you used `admin:generate` command, correct? It should create a migration where all necessary permissions are created and attached to the admin role. You can adjust this migration to your needs. See more at https://docs.getcraftable.com/v2/#/admin-generator?id=usage

**Comment by emperorjm** [comment]
I thought there would have been screens where I could manage roles and permissions and assign permissions directly to users directly as an additional option to assigning roles.

**Comment by palypster** [comment]
I see, sorry, Craftable does not provide any admin tool, to manage permissions and roles. Although it is considered, it has low priority in our internal wish list. PR for this one is very welcome! :)

**Comment by rapgithub** [comment]
it will be nice if craftable can implement permission manager using  spatie/laravel-permission like it is already implemented with backpack:

here the link:
https://github.com/Laravel-Backpack/PermissionManager
