### ISSUE TITLE
Unable to accept multiple mime type media for mediacollection

### ISSUE THREAD

**Issue by devXbian** [BRACKETS-by-TRIAD/craftable#212]
Hi,
I wanted to upload attachments of multiple mime type, and  defined the accepted mimetypes in accept() method as provided in documentation:

 public function registerMediaCollections() {
        $this->addMediaCollection('bus_document')
            ->accepts('image/*','application/pdf')
            ->maxNumberOfFiles(1);
    }

This works fine but in media_uploader blade :

<media-upload
		ref="{{ $mediaCollection->getName() }}_uploader"
		:collection="'{{ $mediaCollection->getName() }}'"
		:url="'{{ route('brackets/media::upload') }}'"
		@if($mediaCollection->getMaxNumberOfFiles())
			:max-number-of-files="{{ $mediaCollection->getMaxNumberOfFiles() }}"
		@endif
		@if($mediaCollection->getMaxFileSize())
			:max-file-size-in-mb="{{ round(($mediaCollection->getMaxFileSize()/1024/1024), 2) }}"
		@endif
		@if($mediaCollection->getAcceptedFileTypes())
			:accepted-file-types="'{{ implode('', $mediaCollection->getAcceptedFileTypes()) }}'"
		@endif
		@if(isset($media) && $media->count() > 0)
			:uploaded-images="{{ $media->toJson() }}"
		@endif
></media-upload>

accepted-file-types value is coming wrong as the implode separator should be comma. which leads in no mime type acceptance, However if only one mime type is defined , it works perfectly.

If there is another solution to this, any assistance would be helpfull

Regards

**Comment by devXbian** [comment]
Any  response would be appreciated. its clearly a bug, however i solved it by myself putting comma with each mimetype while defining in the model, to make it work

**Comment by RichardDominik** [comment]
Hi, thanks for your feedback. Issue is now resolved in latest admin-ui release.
