### ISSUE TITLE
Labels are not auto generating

### ISSUE THREAD

**Issue by amit-viacon** [BRACKETS-by-TRIAD/craftable#215]
I have been using craftable on my new project and it was working fine. But now it is not generating labels for newly generated items. Labels are showing like, `user.bank_info.ac_no` and I would have to manually change this from translation.

I guess I have messed up some configuration. Thank you.

**Comment by palypster** [comment]
I think you have removed some special comment from the localisation file that is used as a placeholder for the generator. If it cannot find it, it won't insert the code.
