### ISSUE TITLE
Notification how?

### ISSUE THREAD

**Issue by Corespondent** [BRACKETS-by-TRIAD/craftable#218]
How i work with that Notification in Craftable? 

Possible to get Help? 

[https://i.imgur.com/HYsvsdj.png](url)

**Comment by palypster** [comment]
Sorry, not sure what do you mean. URL is not working.

**Comment by Corespondent** [comment]
I want to create a Notification, if i klick on a Button or something else. Its my first time that i working with Vue :D

**Comment by palypster** [comment]
Maybe you mean this?
https://www.getcraftable.com/docs/5.0/user-interface#notification

**Comment by Corespondent** [comment]
Yes, i mean that
