### ISSUE TITLE
Change upload language

### ISSUE THREAD

**Issue by elshobokshy** [BRACKETS-by-TRIAD/craftable#219]
Is there a way to change the default value language of "Drop files here to upload" to a different phrase/language? As well as the word "REMOVE" that shows up when we upload?

**Comment by palypster** [comment]
I think it might be related to this https://github.com/BRACKETS-by-TRIAD/craftable/issues/167

**Comment by elshobokshy** [comment]
@palypster so do you have an easy way of doing this? :)

**Comment by palypster** [comment]
Well, yeah, I guess you have already found out that it's a dropzone config:
https://github.com/rowanwins/vue-dropzone/issues/540

so I guess you have to override BaseForm element in the https://github.com/BRACKETS-by-TRIAD/craftable-frontend/blob/master/src/base-components/Form/BaseUpload.js

to add dropzone translate options:
https://www.dropzonejs.com/#configuration-options

**Comment by palypster** [comment]
But I agree, that in a perfect world, all the JS translations should also be translatable like suggested in #167. Let's close this one and leave 167 open.

**Comment by elshobokshy** [comment]
Yeah I was able to get it done by adding this inside the node modules, I'll have to extend the class tho as to not edit the package in itself. Adding this here just for reference. 
```
template: `<dropzone :id="collection" 
                       :url="url" 
                       :language="{
                              dictDefaultMessage: ' Glissez vos fichier ici.',
                              dictFallbackMessage: 'Votre navigateur ne prend pas en charge les téléchargements de fichiers par glisser-déposer.',
                              dictFallbackText: 'Veuillez utiliser le formulaire de secours ci-dessous pour charger vos fichiers.',
                              dictFileTooBig: 'Le fichier est trop volumineux ({{filesize}}MiB). Taille maximale du fichier autorisé: {{maxFilesize}}MiB.',
                              dictInvalidFileType: 'Vous ne pouvez pas charger les fichiers de ce type.',
                              dictResponseError: 'Le serveur a répondu avec le code {{statusCode}}.',
                              dictCancelUpload: 'Annuler le chargement',
                              dictCancelUploadConfirmation : 'Voulez-vous vraiment annuler ce chargement?',
                              dictRemoveFile: 'Supprimer',
                              dictMaxFilesExceeded : 'Vous ne pouvez plus charger de fichiers. Nombre maximum atteint.',
                           }"
                       v-bind:preview-template="template"
                       v-on:vdropzone-success="onSuccess"
                       v-on:vdropzone-error="onUploadError"
                       v-on:vdropzone-removed-file="onFileDelete"
                       v-on:vdropzone-file-added="onFileAdded"
                       :useFontAwesome="true" 
                       :ref="collection"
                       :maxNumberOfFiles="maxNumberOfFiles"
                       :maxFileSizeInMB="maxFileSizeInMb"
                       :acceptedFileTypes="acceptedFileTypes"
                       :thumbnailWidth="thumbnailWidth"
                       :headers="headers">
                
                <input type="hidden" name="collection" :value="collection">
            </dropzone>`,
```

**Comment by emretuna** [comment]
`import { BaseUpload } from "craftable";

Vue.component("media-upload", {
    mixins: [BaseUpload],
    template: `<dropzone :id="collection" 
                       :url="url" 
                       :language="{
                                dictDefaultMessage : 'Dosyaları yüklemek için buraya bırakın',
                                dictFallbackMessage : 'Tarayıcınız sürükle bırak dosya yüklemelerini desteklemiyor.',
                                dictFallbackText : 'Dosyalarınızı eski günlerdeki gibi yüklemek için lütfen aşağıdaki geri dönüş formunu kullanın.',
                                dictFileTooBig : 'Dosya çok büyük ({{filesize}}MiB). Maksimum Dosya Boyutu: {{maxFilesize}}MiB.',
                                dictInvalidFileType : 'Bu türdeki dosyaları yükleyemezsiniz.',
                                dictResponseError : 'Sunucu yanıt verdi {{statusCode}} kodu.',
                                dictCancelUpload : 'Yüklemeyi iptal et',
                                dictCancelUploadConfirmation : 'Bu yüklemeyi iptal etmek istediğinizden emin misiniz?',
                                dictRemoveFile : 'Dosyayı kaldır',
                                dictMaxFilesExceeded : 'Daha fazla dosya yükleyemezsiniz.',
                           }"
                       v-bind:preview-template="template"
                       v-on:vdropzone-success="onSuccess"
                       v-on:vdropzone-error="onUploadError"
                       v-on:vdropzone-removed-file="onFileDelete"
                       v-on:vdropzone-file-added="onFileAdded"
                       :useFontAwesome="true" 
                       :ref="collection"
                       :maxNumberOfFiles="maxNumberOfFiles"
                       :maxFileSizeInMB="maxFileSizeInMb"
                       :acceptedFileTypes="acceptedFileTypes"
                       :thumbnailWidth="thumbnailWidth"
                       :headers="headers">
                
                <input type="hidden" name="collection" :value="collection">
            </dropzone>`
});
`
Better way of usage might be updating admin/Form/AppUpload.js as above.
