### ISSUE TITLE
Relationship approach

### ISSUE THREAD

**Issue by oscaralencar** [BRACKETS-by-TRIAD/craftable#22]
What approach do you recommend about creating relationships? For example, if I use a field with id (post_id) the options of the select field show numbers, not text values. And if I change to show a text, the validation requires “integer values”. I’m being clear?

**Comment by loekiedepo** [comment]
+1

Used your package to create a tiny dashboard with some statistics about a sports team, but the "lack" of relationship support required me to hack around your code a lot. Probably would've been better off writing my own templates, models and controllers.

That said, nice package!

**Comment by oalencar** [comment]
I have a few changes and I reached on my goal. Thanks.

**Comment by oalencar** [comment]
@loekiedepo you can change this values using the accessors on Laravel. Check the documentation: [https://laravel.com/docs/5.6/eloquent-mutators#accessors-and-mutators].

**Comment by loekiedepo** [comment]
@oalencar Thanks! I know how to do it, and had already fixed it earlier. The problem for me was mostly in how this package decided to access data (i.e. the Request and AdminListing classes). These get in the way when you're dealing with relationships; I think there is room for improvement there.

**Comment by palypster** [comment]
Hey guys, thanks for your interest. Yes, there is definitely a room for an improvement. We have already mentioned something in https://github.com/BRACKETS-by-TRIAD/admin-generator/issues/14#issuecomment-371139327

To add a bit more - in AdminListing there is an option to modify a query for your own. This is the place, where you can inject any `with()` calls (or alternatively `join()`), so you can retrieve the data of related models. Also Request classes does not forbid you to structure the data yourself. Is this helpful?

We find current solution sufficient. Said that, improving relationships support is on our roadmap. Thank you.

**Comment by palypster** [comment]
One more thing, we will definitely update the docs and add an example, how to easily display a `title` column of a related model. It should be really easy.

**Comment by oalencar** [comment]
Thanks, Pavol!

But the AdminList is inside vendor of package, correctly? How can I modify it?

**Comment by loekiedepo** [comment]
> To add a bit more - in AdminListing there is an option to modify a query for your own. This is the place, where you can inject any with() calls (or alternatively join()), so you can retrieve the data of related models. Also Request classes does not forbid you to structure the data yourself. Is this helpful?

Thanks! This is helpful. I mainly had 2 problems/wishes:

1. The generated Request classes don't acount for foreign keys. So if you want to load related models into i.e. a  `multiselect`, you're screwed because the Request class expects integers where you give it arrays. Change this in the Request class and you suddenly can't save your model anymore, because you're putting an array into an int. This is quite easy to code around, but it's weird and I didn't expect it.
2. Intuitively, you would expect foreign key references to load models and not integers.

Sorry if this all sounds negative, it's certainly not!

**Comment by palypster** [comment]
@oalencar use https://docs.getcraftable.com/v2/#/admin-listing?id=additional-query-modification

**Comment by oalencar** [comment]
Thanks!!!
Sorry for didnt have seen it before. X)

**Comment by palypster** [comment]
@loekiedepo this is a very good point. We're definitely going to have a look at it.

**Comment by loekiedepo** [comment]
Just tag me if I can help with something!

**Comment by footniko** [comment]
Any updates on this?
Although it's possible to append the response with some relations, I can't find a way how we can search through the relational fields? Any workaround?

Btw, thanks for the great product!

**Comment by palypster** [comment]
@footniko sorry, this is not on our roadmap yet

But if you are asking how can you search in related models using AdminListing, then it can be done modifying the query yourself - you just need to add the right `join` to the query, and introduce new columns to search like `related_table_name.column`. Check out https://docs.getcraftable.com/v2/#/admin-listing?id=additional-query-modification

Let me know if that helped.

**Comment by footniko** [comment]
Was trying with **with** constrution before and it doesn't work, with **join** works perfectly, thanks!

**Comment by casper123** [comment]
> @footniko sorry, this is not on our roadmap yet
> 
> But if you are asking how can you search in related models using AdminListing, then it can be done modifying the query yourself - you just need to add the right `join` to the query, and introduce new columns to search like `related_table_name.column`. Check out https://docs.getcraftable.com/v2/#/admin-listing?id=additional-query-modification
> 
> Let me know if that helped.

Could you give any example?

**Comment by palypster** [comment]
Hey guys, I'm closing this one for now. We were thinking about adding the relationship support to generator, but we have postponed it for now as it raised too many questions to take into account.

You can still easily add relations into your models manually. Good examples can be found on our demo project: https://demo.getcraftable.com/admin/articles-with-relationships
