### ISSUE TITLE
Where is craftable password reset text?

### ISSUE THREAD

**Issue by elshobokshy** [BRACKETS-by-TRIAD/craftable#224]
Where is it can I find the layout that is used in the email reset situated?

```
Hello!

You are receiving this email because we received a password reset request for your account.

                                           BUTTON

If you did not request a password reset, no further action is required. 

Regards, 
Craftable
```

**Comment by alexmntr** [comment]
The text can be found in `vendor/brackets/admin-auth/src/Notifications/ResetPassword.php`. 

It is the same text as in `vendor/laravel/framework/src/Illuminate/Auth/Notifications/ResetPassword.php` btw. 

The email template seems to be Laravel's default and can be found in `vendor/laravel/framework/src/Illuminate/Notifications/resources/views/email.blade.php`

**Comment by palypster** [comment]
@RichardDominik please verify we don't have any text hard-coded in some blade files. If not, we can close this issue I think.
