### ISSUE TITLE
I can't upload and store on my model image

### ISSUE THREAD

**Issue by eng-mr-gohari** [BRACKETS-by-TRIAD/craftable#227]
hello I don't know how to upload image file.
When read the library for media, I can't understand how to make migration and related my model to media and insert data on database ...

**Comment by eng-mr-gohari** [comment]
@palypster Thanks a lot but how to use customize upload component such as jQuery file uploads !?

**Comment by verybigelephants** [comment]
when you upload a file to the server via any means you can process it manually by turining off the `AutoProcessMediaTrait` trait, like it says in the link and then attach it to any model that you'd like https://spatie.be/docs/laravel-medialibrary/v7/basic-usage/associating-files
