### ISSUE TITLE
Generator is not generating textarea for text type of columns but uses wysiwyg editor

### ISSUE THREAD

**Issue by JanciVd** [BRACKETS-by-TRIAD/craftable#228]
There is information in documentation that generator should generate textarea for any columns which are type of text: https://getcraftable.com/docs/5.0/explore-generator 

But it generates wysiwyg editor instead which is wrong - sometimes you just want to save plain text without html tags - for example for meta description. 

You can check it with this schema easily:
```
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('tests', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->text('excerpt');
            $table->timestamps();
        });
    }
```

**Comment by palypster** [comment]
@RichardDominik according to docs wysiwyg should be generated only if the column has a specific name:

> wysiwyg (when attribute name is one of: text, body, description)
date (for any date)

Can you fix it please?

**Comment by RichardDominik** [comment]
Hi, thanks for your feedback. Bug is now resolved in latest admin-generator release.
