### ISSUE TITLE
Migration media installation problem

### ISSUE THREAD

**Issue by hlo2109** [BRACKETS-by-TRIAD/craftable#231]
When I try to install by means of the command craftable new my_project, first it does not ask me for the data from the database, so I have to quickly edit the .env so that it finally loads the migrations.

The problem is the migrations because at the time of starting it sends an error that it does not find the means table since in the migration that they have this as an average and everything stops there, already after correcting everything back and I perform the manual migration but this It does not bring me the user key that is generated randomly and it does not complete the permissions.

**Comment by palypster** [comment]
Can you try this ?
https://github.com/BRACKETS-by-TRIAD/craftable/issues/145#issuecomment-535175118

and let me know if that helps?

**Comment by hlo2109** [comment]
Hello, thanks for answering, if it works, I will continue testing, but so far I have liked the system a lot
