### ISSUE TITLE
Database Migration fail with Installer when an empty password is used

### ISSUE THREAD

**Issue by pytesin** [BRACKETS-by-TRIAD/craftable#24]
https://github.com/BRACKETS-by-TRIAD/craftable/blob/f9c7a718b647b951018617682ee27775ce339fae/src/Console/Commands/CraftableInitializeEnv.php#L84

`$dbPassword = $this->ask('What is your database user password?', 'secret');`
-->
`$dbPassword = $this->ask('What is your database user password?', '');`

This would make it easier if no password at all is used, otherwise install will fail to migrate tables

**Comment by palypster** [comment]
I'm not even sure, if Laravel allows empty password for DB. In my opinion this is very nonstandard. Is there a good reason not to use password?
