### ISSUE TITLE
How to Rollback any Crud Generator operation.?

### ISSUE THREAD

**Issue by omaralwi** [BRACKETS-by-TRIAD/craftable#240]
First of all ,, Thank you for your aweasome work ,,
How to Rollback any Crud Generator operation.? I did not found that in documentation page.
I mean if Make crud generator name like (php artisan admin:generate --force categoreis) => I was Mean php artisan admin:generate --force categories.
I need to delete all categoreis files.?
How to Do That.?

Thank you very much ,,

**Comment by palypster** [comment]
Hi, thanks. There is no command to rollback. But if you're using GIT (and you always should!) then it's very easy of course.
