### ISSUE TITLE
Date format invalid when updating

### ISSUE THREAD

**Issue by jjclinton** [BRACKETS-by-TRIAD/craftable#242]
I get the following message when updating a date field: The date_finished must be in the format yyyy-MM-dd HH:mm:ss
On store it does work, but on update it doesn't.

I haven't changed anything in the files. In de v-model I see it has the date like this: "2020-07-21T00:00:00.000000Z" which is the incorrect format I guess.

When I re-click the date in the datepicker it does work. So I think the v-model is getting the wrong format out of the database. How can I solve this?

**Comment by palypster** [comment]
This is related to this:
https://laravel.com/docs/7.x/upgrade#date-serialization
as a temp fix you can change the date serialization on the model until we come with a proper fix on a FE side.
