### ISSUE TITLE
instalation stops with error : Cannot declare class CreateMediaTable, because the name is already in use

### ISSUE THREAD

**Issue by ajimatahari** [BRACKETS-by-TRIAD/craftable#25]
the last step : php artisan craftable:install give error : Cannot declare class CreateMediaTable, because the name is already in use ...

**Comment by palypster** [comment]
@ajimatahari are you sure it's a fresh installation? are you creating new craftable project using `craftable new` command?

**Comment by localhost8080** [comment]
I had the same issue;
it seems the artisan craftable:install copies 3 new migrations each time it is run

(date)_create_media_tables.php
(date)_create_permission_tables.php
(date)_create_translations_table.php

my solution was just to delete those 3 migrations and run the install again and it worked

**Comment by ajimatahari** [comment]
yes...fresh installation

**Comment by palypster** [comment]
@localhost8080 there was a check and if the class exists, it should not create this migration again. This check must had stopped working. We're look at it.

@ajimatahari as a temporary workaround follow localhost8080's proposal

**Comment by palypster** [comment]
Cannot reproduced now. Probably fixed already.

**Comment by vaishnavmhetre** [comment]
Still facing the error with an existing installation. Cannot create a fresh installation due to common Schema::defaultStringLength issue (occurs while creating a fresh installation using CLI command).

**Comment by palypster** [comment]
@vaishnavmhetre pls report as a new issue as long as it has nothing to do with this one.

**Comment by robbiek** [comment]
I also had this exact same issue

**Comment by Elshaden** [comment]
I had the same issue, resolved by deleting all Migrations because if you install again it will create fresh migrations with different names and date Time. that's where the duplication error comes from
just keep the default Laravel Migrations.
of course you have to drop all the tables if they were created in the db
