### ISSUE TITLE
Get relation information by relation id

### ISSUE THREAD

**Issue by vuongnguyen1996** [BRACKETS-by-TRIAD/craftable#250]
I have two tables:
- **categories**: name, status
- **posts**: title, category_id

In **post** listing (index function), I would like to show **category_name** instead of **category_id** as currently. Is there any look for me?

**Comment by palypster** [comment]
Isn't this article helpful?
https://www.getcraftable.com/docs/5.0/relations

let us know please, where we can improve it

**Comment by vuongnguyen1996** [comment]
Good to me. I missed it. Many thanks!

**Comment by GabagoolOverHere** [comment]
Hi, I read the documentation but I can't see how to do it.
If you guys could help that's be awesome, thanks :)

**Comment by palypster** [comment]
Just don't forget to eager load the relationships like said in the docs and it should work.

**Comment by GabagoolOverHere** [comment]
That's what I did but I have this in my index.blade.php :

`<td>@{{ item.id_societe }}</td>` and i don't know what i should replace it with
