### ISSUE TITLE
unauthenticated exception

### ISSUE THREAD

**Issue by dballari** [BRACKETS-by-TRIAD/craftable#255]
Hi,

In my opinion there is an error in line 24 of the admin-auth\src\Exceptions\Handler.php file in the unauthenticated function:

Instead of hardcoded url: $url = route('login');

I believe there shoud be the redirectTo() url: $url = $exception->redirectTo();

I have a multiple language app with two logins one for the admin and the other for frontoffice users.

The front office login form has a parameter for the locale.  The route is like this:

Route::group(['prefix' => '{locale}'], function() {
    Route::get('frontlogin', 'Auth\LoginController@showLoginForm')->name('frontlogin');
    Route::post('frontlogin', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('frontlogout');
...

if I do not modify the line of code that I mention, I cannot use the frontoffice login form because the exception redirects to a hardcoded named route.

If I rename my frontlogin route to 'login' then I get an error because the handler does not provide the locale parameter.

If I define the locale parameter as optional, then It does not work anyway because the login route gets redirected to the admin login route. (I do not know why).

Finally, I'm not able to move the unauthenticated function of the handler to the Add\Exceptions\Handler file which would be a solution.

So the only way I can solve it is by changing the mentioned file.

Could anyone help me please?

Thanks a lot and congratulations for having developed a great tool,

David

**Comment by dejwCake** [comment]
You are right, we should change it to use first redirect from exception and login only as a fallback. 

Can you please explain, why you cannot move unauthenticated method to your project Handler?

Thanks.

**Comment by dballari** [comment]
Sorry, my explanation is not very accurate: I can move the unauthenticated method to my project Handler, I did, but I do not get the desired result, the behaviour stays the same. Maybe I'm not doing it the right way, I no not know the mistake I'm making but I was not abel to solve it. I'll try again
