### ISSUE TITLE
Laravel 7.25 support

### ISSUE THREAD

**Issue by hanynasyr** [BRACKETS-by-TRIAD/craftable#256]
Problem 1
    - Conclusion: install brackets/media v4.0.0
    - Conclusion: remove laravel/framework v7.25.0
    - Installation request for symfony/console (locked at v5.1.3) -> satisfiable by symfony/console[v5.1.3].
    - Installation request for brackets/craftable 5.1.0 -> satisfiable by brackets/craftable[v5.1.0].
    - Installation request for symfony/process (locked at v5.1.3) -> satisfiable by symfony/process[v5.1.3].
    - Conclusion: don't install laravel/framework v7.25.0
    - brackets/media v4.0.0 requires illuminate/support ~6.0 -> satisfiable by laravel/framework[6.x-dev], illuminate/support[6.x-dev, v6.0.0, v6.0.1, v6.0.2, v6.0.3, v6.0.4, v6.1.0, v6.10.0, v6.11.0, v6.12.0, v6.13.0, v6.13.1, v6.14.0, v6.15.0, v6.15.1, v6.16.0, v6.17.0, v6.17.1, v6.18.0, v6.18.1, v6.18.10, v6.18.11, v6.18.12, v6.18.13, v6.18.14, v6.18.15, v6.18.16, v6.18.17, v6.18.18, v6.18.19, v6.18.2, v6.18.20, v6.18.21, v6.18.22, v6.18.23, v6.18.24, v6.18.25, v6.18.26, v6.18.27, v6.18.28, v6.18.29, v6.18.3, v6.18.30, v6.18.31, v6.18.32, v6.18.33, v6.18.34, v6.18.35, v6.18.4, v6.18.5, v6.18.6, v6.18.7, v6.18.8, v6.18.9, v6.2.0, v6.3.0, v6.4.1, v6.5.0, v6.5.1, v6.5.2, v6.6.0, v6.6.1, v6.6.2, v6.7.0, v6.8.0].

**Comment by RichardDominik** [comment]
@hanynasyr Hi, we are not able to reproduce it. Are you still facing the same issue ? If so, can you be more explicit ?

**Comment by hanynasyr** [comment]
Yes, I am still having the problem. I am using the "composer require brackets/craftable" command on an existing project. and this is the error I am getting. And here is a part of the composer.json file
"name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.25",
        "laravel/tinker": "^2.0"
    },
    "require-dev": {
        "facade/ignition": "^2.0",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^4.1",
        "phpunit/phpunit": "^8.5"
    },

**Comment by aqjw** [comment]
how to solve it? please
