### ISSUE TITLE
[QUESTION]Is it opssible to generate a page like user profile

### ISSUE THREAD

**Issue by hAbd0u** [BRACKETS-by-TRIAD/craftable#257]
As the title mentioned above, can we generate pages to acts just as RU?

**Comment by hAbd0u** [comment]
@palypster Currently the package generates a CRUD, the feature I am talking about is to generate pages, like wordpress do.

**Comment by mjubouri** [comment]
> Sorry, I don't understand the question. Can you be more specific?

There is a way to make a single page setting like a profile page, without listing just one page to change the data like setting page

**Comment by palypster** [comment]
Still not sure, but I try to write what I'm hearing from you. You have Eloquent model, but you always have exactly ONE instance of this model (only one record in the database table). Generator should generate only the Edit form, not the listing. Is this what you expect? If not, please attach some screenshots or something we can start from. Thank you.

**Comment by mjubouri** [comment]
> Still not sure, but I try to write what I'm hearing from you. You have Eloquent model, but you always have exactly ONE instance of this model (only one record in the database table). Generator should generate only the Edit form, not the listing. Is this what you expect? If not, please attach some screenshots or something we can start from. Thank you.

yes, that's what I need, Just one record without add new record and go directly to edit form without need to listing.

**Comment by palypster** [comment]
Current version of generator does not support such thing. But it's easy to remove listing from the controller and change the menu to navigate directly to the edit route, I think.

If you think this is something new Craftable Pro should support, don't hesitate to propose new feature in the questionnaire in the end of the page here:
https://getcraftable.com/pro

Thank you
