### ISSUE TITLE
Laravel Passport Boilerplate

### ISSUE THREAD

**Issue by thindery** [BRACKETS-by-TRIAD/craftable#26]
I use the Passport Boilerplate often and I am running into an issue where things aren't quite working correctly. I think it is because Laravel 5.5 and Passport 4.0 use Bootstrap 3, and Craftable is tied to Laravel 5.5, but Craftable is using Bootstrap 4.

It appears craftable also only uses bootstrap-sass not full bootstrap. So the .modal method, etc, does not work. 

Trying to copy in the new Passport 5.0 .vue components makes things visibly look better, however, not fulling functioning. Console errors about the modal, etc. (https://github.com/laravel/passport/tree/5.0/resources/assets/js/components) 

If I change my package.json and include bootstrap 4.0, and then
`import bootstrap from 'bootstrap';`
inside of the admin/js/bootstrap.js the modal errors go away and they do open up now.

However, I can't click on text inputs and the buttons inside of the modal do not work. It's as if the component is frozen or something.

Any suggestions on how to get craftable to play nicely with the passport components featuring bootstrap 4.0?

**Comment by Trexology** [comment]
I faced the exact same situation like @thindery ... manage to get the modal view to load up after require('bootstrap') in my admin.js..

Could not get passport vue component to submit or any mouse click event.

**Comment by palypster** [comment]
Craftable v3 is out. We would appreciate if this problem still occurs in the latest Craftable. We don't use Laravel Passport at all, can't test.
