### ISSUE TITLE
Send Reset password link is not working

### ISSUE THREAD

**Issue by im-denny** [BRACKETS-by-TRIAD/craftable#262]
Send password reset link is throwing 500.
![Screenshot 2020-08-25 at 2 17 07 PM](https://user-images.githubusercontent.com/29495934/91153539-f9b87e00-e6dd-11ea-960b-438cbac5c69d.png)

**Comment by RichardDominik** [comment]
Hi, thanks for your feedback. Issue is now resolved in Craftable demo project.
