### ISSUE TITLE
Craftable is awesome

### ISSUE THREAD

**Issue by codeurfou** [BRACKETS-by-TRIAD/craftable#267]
Hello guys.

Just a ticket to thank you for your amazing work ! 

I have now made maybe 5 or 6 projects with Craftable. Some of them for internal projects in a very big European Company.

Craftable is not yet perfect but I'm very grateful of what you guys have done. 

Keep the hard work !

**Comment by palypster** [comment]
Thank you very much <3

**Comment by palypster** [comment]
I'm gonna leave this "ticket" open for a bit, so we can enjoy it for a while 😜
