### ISSUE TITLE
how to add again register to the project?

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#268]
I installed craftable but I see there is no /register, is there a way to add it quickly with a command or do I have to add it manually? thanks

**Comment by palypster** [comment]
Manually. We have never experienced the case of self-registration into back-office/admin area.

But of course, you can use default Laravel scaffolding, or?

**Comment by rapgithub** [comment]
well I need self registration only for users! in my case the scenario it is membership area users that can register themselves to view the content!

**Comment by rapgithub** [comment]
admin area can stay the same!
