### ISSUE TITLE
How to show administrative roles and permissions from the administrator

### ISSUE THREAD

**Issue by hlo2109** [BRACKETS-by-TRIAD/craftable#269]
Hello, I did an installation but I can't find in the manual how to show the roles and permissions to manage them in the menu, you could help me with this thanks.

**Comment by julianovmartins** [comment]
Hello hlo2109,

This is relatively easy.

Run the commands:

```
php artisan admin:generate users
php artisan admin:generate roles
php artisan admin:generate permissions
```

Then change extends for the created `Role` and `Permission` models to:

Role:
```
use Spatie\Permission\Models\Role as SpatieRole;

class Role extends SpatieRole
```

Permission:
```
use Spatie\Permission\Models\Permission as SpatiePermission;

class Permission extends SpatiePermission
```

Add the `HasRoles` trait in the `User` model:

```
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable;
    use HasRoles;
```

Finally, follow this [tutorial](https://www.getcraftable.com/docs/5.0/relations) to implement the relations in the views.

**Comment by hlo2109** [comment]
Thank you very much for answering.

But this in case it is for the user table, but then it would be the same if I wanted to use the admin_user table which is the one that comes by default when installing craftable and in which I want to manage roles and permissions since they already come with the default tables.

**Comment by julianovmartins** [comment]
Exactly, instead create `User` *(model/Controller/views)* use the ` AdminUser` that already exists!

**Comment by hlo2109** [comment]
ok, thank you 👍
