### ISSUE TITLE
How to make model translatable (form view)

### ISSUE THREAD

**Issue by tmihetec** [BRACKETS-by-TRIAD/craftable#27]
Hi, how to make model translatable? 
i made, migration with i.e. name field as text,  migrated it, and artisan admin:generate post.
After that i npm run dev and added and (use)  HasTranslations trait on model, and set this "name" field to be in $translatable array. 
Still no translation variants in create form view.

(i guess same thing is with mediable - uploading images to model)

br and sorry if i am missing something obvious.

**Comment by palypster** [comment]
Hello, this is a bit tricky at the moment. You just need to use a `jsonb` type of column. Our generator automatically detects it as a translatable column and generate everything correctly. See more at:
https://docs.getcraftable.com/v2/#/admin-generator?id=usage

**Comment by tamr** [comment]
Nope, it didn't work. I'm looking for ways to implement the Translatable Articles. Where can I find the sources of demo.getcraftable.com to quickly check it out?

**Comment by palypster** [comment]
Sorry, it's not public but I'm pasting here the migration for the translatable model:

```
<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CreateTranslatableArticles extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('translatable_articles', function (Blueprint $table) {
            $table->increments('id');
            $table->jsonb('title');
            $table->jsonb('perex')->nullable();
            $table->date('published_at')->nullable();
            $table->boolean('enabled')->default(false);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::drop('translatable_articles');
    }
}

```

**Comment by tamr** [comment]
That's pretty sad. Maybe you can share the Vue components with us?

**Comment by palypster** [comment]
Can you please confirm, that you have created new migration with the `jsonb` column in it, then yoy have migrated it and *after* that you have run the `admin:generate` command for this migration and you are still missing the translations?

I'm guessing maybe you expect it works dynamically. Once you have generated the admin and then you make a change to the migration, it worn't work, sorry. You must re-generate it.

Is that it?
