### ISSUE TITLE
Tinymce rather than trumbowyg

### ISSUE THREAD

**Issue by elshobokshy** [BRACKETS-by-TRIAD/craftable#270]
It's just a suggestion, but tinymce v5 is a thousand times more powerful than trumbowyg, would you guys consider a migration? In my code, it took me literally 30 minutes to migrate, and tinymce has a lot of powerful and free plugins compared to trumbowyg.

**Comment by emretuna** [comment]
> It's just a suggestion, but tinymce v5 is a thousand times more powerful than trumbowyg, would you guys consider a migration? In my code, it took me literally 30 minutes to migrate, and tinymce has a lot of powerful and free plugins compared to trumbowyg.

Can you share the steps?I'm also trying to achieve this.
