### ISSUE TITLE
making qr

### ISSUE THREAD

**Issue by subtain-haider** [BRACKETS-by-TRIAD/craftable#275]
**Not an issue just a request if anyone can help me**

Hey maybe this is a stupid question but here it is

I have generated admin CRUD for "childrens"
CRUD is working fine as expectations but I need lil customization.

In the children table I have a column named as "Qr"
the right most column in the picture
https://i.imgur.com/ECnOFzh.png

I want to show a QR code using 'Qr' column, for this purpose am using this:
https://www.simplesoftware.io/#/docs/simple-qrcode

now according to its documentation I would use this to make a QR code :
`{!! QrCode::generate('Make me into a QrCode!'); !!}`
this generates a QR code which on scan will give the following info : "Make me into a QrCode!"

https://i.imgur.com/JHLoB9l.png
the above image is the code of my table

Now the problem is that I want @{{ item.qr}} to be placed inside this QrCode function, I want something like this:
`{!! QrCode::generate(' @{{ item.qr}} '); !!}`
so that it will make a QR code which on scan will provide the value present in @{{ item.qr}}
and the end result will be like this
resulted table: https://i.imgur.com/az8Q22c.png
code: https://i.imgur.com/LkSzOWW.png

Please someone help me on this, its been hours of searching google and using different ways but I am unable to figure out this problem
I hope I provided enough information.

**Comment by palypster** [comment]
Why calculating in in blade? Too complicated.

I would use the combination of Accessor:
https://laravel.com/docs/7.x/eloquent-mutators#accessors-and-mutators

and `appends`:
https://laravel.com/docs/7.x/eloquent-serialization#appending-values-to-json

**Comment by subtain-haider** [comment]
wow you are awesome, I didnt know this, THNKU SO MUCH
