### ISSUE TITLE
A few questions before using Craftable for a project

### ISSUE THREAD

**Issue by Benoit1980** [BRACKETS-by-TRIAD/craftable#279]
Hello,

I came here to write this post as I am not really understanding where else I can get any help as you have no forum.

A few questions cames to my mind:

-Is this using vue, if yes can I custom code any parts of the app easely? Because with Backpack and Nova it is not easy.
-If I need help and struggle with something, is there a place where we can post our questions(here???).
-Will you support Laravel 8, if yes, when?

Thanks.

**Comment by zhed** [comment]
i'm user of this package too,
let me help answer, 
1. yes, this package use vue. so far i think it was easy to customize.
2. when i struggle, i read this package's issue section, i got help from other users question
3. yes this package already support laravel 8, but still on vue 2, coreui 2 and veevalidate 2..
 hope the authors will upgrade the dependency JS Package too..
