### ISSUE TITLE
running php artisan craftable:install returns error

### ISSUE THREAD

**Issue by dfrey382** [BRACKETS-by-TRIAD/craftable#28]
running php artisan craftable:install returns error

php artisan craftable:install

  There are no commands defined in the "craftable" namespace.
![image](https://user-images.githubusercontent.com/28592665/38424208-f94805d2-39b8-11e8-8187-d87fd281eecf.png)

**Comment by palypster** [comment]
Hey @dfrey382, have you solved the problem already? If no, can you send us whole console output (of all steps), because we have absolutely no idea what this could mean. Also send us your php version and craftable version.

**Comment by dfrey382** [comment]
yes i did solve it, thanks though
Regards

Fredrick Boaz

Web Designer / Web Developer

Magik Themes
+254720728651 | boaz@magik.co.ke | www.magik.co.ke


Quality is never an accident; it is always the result of high intention,
sincere effort,
intelligent direction and skillful execution; it represents the wise choice
of many alternatives.

Willa A. Foster



THIS EMAIL, THE INFORMATION IN IT AND ANY ATTACHMENT(S) ARE ALL
CONFIDENTIAL AND MAY BE LEGALLY PRIVILEGED OR OTHERWISE PROTECTED FROM
DISCLOSURE. THE EMAIL IS INTENDED SOLELY FOR THE NAMED ADDRESSEE(S).  THE
OPINIONS THEREIN, EXPLICIT OR IMPLIED, ARE SOLELY THOSE OF THE AUTHOR, AND
DO NOT NECESSARILY REPRESENT THOSE OF EVOLVE MEDIA LIMITED. UNAUTHORIZED
DISCLOSURE, USE, DISSEMINATION OR COPYING (EITHER WHOLE OR PARTIAL) OF THIS
E-MAIL IS PROHIBITED. EMAILS ARE NOT SECURE AND MAY SUFFER ERRORS, VIRUSES,
DELAY, INTERCEPTION, AMENDMENT AND THEIR INTEGRITY CANNOT BE GUARANTEED.
EVOLVE MEDIA LIMITED DISCLAIMS ANY LIABILITY TO THE FULLEST EXTENT
PERMISSIBLE BY LAW FOR ANY CONSEQUENCES THAT MAY ARISE FROM THE CONTENTS OF
THIS EMAIL INCLUDING BUT NOT LIMITED TO PERSONAL OPINIONS, MALICIOUS AND/OR
DEFAMATORY INFORMATION AND DATA/CODES THAT MAY COMPROMISE OR DAMAGE THE
INTEGRITY OF THE RECIPIENT’S INFORMATION TECHNOLOGY SYSTEMS. IF YOU ARE NOT
THE INTENDED RECIPIENT, PLEASE INFORM THE SENDER IMMEDIATELY AND DELETE
THIS EMAIL FROM YOUR SYSTEM WITHOUT USING, SENDING OR STORING IT.

**Comment by sasivarnakumar** [comment]
how did you solve it..? I m facing same issue.

**Comment by sasivarnakumar** [comment]
Ha.. found..
`composer dump-autoload`
solved the issue.

**Comment by goursuhail** [comment]
when I fire this command  ( php artisan craftable:install ). given below issue comes up.


There are no commands defined in the "craftable" namespace.

How can I resolve this issue?

**Comment by paejan** [comment]
> Ha.. found..
> `composer dump-autoload`
> solved the issue.

still didnt work..

**Comment by paejan** [comment]
@dfrey382  
would you mind to share how you solve the problem..?

**Comment by paejan** [comment]
Got it.. maybe because previous composer fail to run completely.. 

i dont realize both of this command not done.. 

composer require brackets/craftable
composer require --dev brackets/admin-generator

got memory error.. solve the prob and recompose..

**Comment by muazzamazaz** [comment]
still having issue after running `composer dump-autoload` in Laravel 9
