### ISSUE TITLE
Problem with installation!

### ISSUE THREAD

**Issue by habe90** [BRACKETS-by-TRIAD/craftable#281]
$ php artisan craftable:install

  There are no commands defined in the "craftable" namespace.

Any advice?

**Comment by JackiGeduld** [comment]
Me too

**Comment by derJake** [comment]
Thirded.

**Comment by palypster** [comment]
Can you be more verbose - where are you trying to run this command? What are the steps you are executing before this command?

**Comment by palypster** [comment]
Can you confirm the problem occurs in the latest version of craftable as well?

**Comment by derJake** [comment]
The above commands still don't work for me. I've put the complete console output in a pastebin: https://pastebin.com/sAh049AX

**Comment by derJake** [comment]
Works on Debian 10, PHP 7.4.13
