### ISSUE TITLE
fix error for $locale contains dash

### ISSUE THREAD

**Issue by ray7551** [BRACKETS-by-TRIAD/craftable#284]
For json type column, the generated form-elements.blade will cause js error if $locale contains dash(eg: 'zh-CN', 'en-US')
![image](https://user-images.githubusercontent.com/1812388/98027417-99655b80-1e47-11eb-9825-a1c2d535a371.png)

So i tried to fix this: just use `[@{{$locale}}]` instead of `.@{{$locale}}`

[see my commit 1](https://github.com/BRACKETS-by-TRIAD/admin-generator/commit/80c2d13aab5b23d8f7388a86dfbae4337a4da350)
[see my commit 2](https://github.com/BRACKETS-by-TRIAD/admin-generator/commit/27498dbf02de26d62c569c7e48033b633e13aaf5)

If it's possible to accept my pull request?

**Comment by palypster** [comment]
Hey @ray7551 , yes please file a PR and we're most likely going to accept it. I don't think this breaks anything, so yes.
