### ISSUE TITLE
Installation Issue - 

### ISSUE THREAD

**Issue by Ravensborn** [BRACKETS-by-TRIAD/craftable#286]
No matter how many times I try to install I get the same error.
![image](https://user-images.githubusercontent.com/27031143/98595866-a2db4180-22e7-11eb-9d6a-6be71eee751a.png)
![image](https://user-images.githubusercontent.com/27031143/98596089-fc437080-22e7-11eb-95ef-8e9e4cb790b0.png)

**Comment by lukasplevko** [comment]
You'll need to run npm install && npm run dev
it usually runs automatically but sometimes fails for some reason

**Comment by Ravensborn** [comment]
> You'll need to run npm install && npm run dev
> it usually runs automatically but sometimes fails for some reason.
> They already discussed this issue in this threat, go check it out.
> 
> #15

I tried that many times it doesnt work.

**Comment by lukasplevko** [comment]
https://github.com/BRACKETS-by-TRIAD/craftable/issues/15#issuecomment-365880400
try npm i -g cross-env

**Comment by Ravensborn** [comment]
> [#15 (comment)](https://github.com/BRACKETS-by-TRIAD/craftable/issues/15#issuecomment-365880400)
> try npm i -g cross-env

I ran that followed by npm install && npm run dev
same error

![image](https://user-images.githubusercontent.com/27031143/98739146-e9996c00-23b9-11eb-837a-2c51999f103c.png)
