### ISSUE TITLE
Forgot Password default !

### ISSUE THREAD

**Issue by bozid95** [BRACKETS-by-TRIAD/craftable#288]
How add password to admin-user?
cz using factory(Brackets\AdminAuth\Models\User::class)->create(['email' => 'john@example.com', 'password' => bcrypt('password123')]);
not work..
factory(Brackets\AdminAuth\Models\User::class)->create(['email' => 'john@example.com', 'password' => bcrypt('password123')]);
PHP Error:  Class 'Brackets/AdminAuth/Models/User' not found in /home/widodo/Documents/PROJECTS/portfolio/vendor/laravel/legacy-factories/src/FactoryBuilder.php on line 295

**Comment by zhed** [comment]
i found my default password was hardcoded on **database/migrations** file **xxxx_xxxx_xx_xxxxxx_fill_default_admin_user_and_permissions.php**
search for keyword **protected $password**

**Comment by jferruzca** [comment]
I did this...
`php artisan tinker`

and generated a new password
`Hash::make('pass123456');`

and changed directly in the _admin_users_ table.
