### ISSUE TITLE
Migration error issue

### ISSUE THREAD

**Issue by dfrey382** [BRACKETS-by-TRIAD/craftable#29]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version fo
  r the right syntax to use near 'json not null, `custom_properties` json not null, `order_column` int unsigned nu' at line 1 (SQL: create table `media` (`id` int
  unsigned not null auto_increment primary key, `model_id` int unsigned not null, `model_type` varchar(255) not null, `collection_name` varchar(255) not null, `nam
  e` varchar(255) not null, `file_name` varchar(255) not null, `mime_type` varchar(255) null, `disk` varchar(255) not null, `size` int unsigned not null, `manipula
  tions` json not null, `custom_properties` json not null, `order_column` int unsigned null, `created_at` timestamp null, `updated_at` timestamp null) default char
  acter set utf8mb4 collate utf8mb4_unicode_ci)

![image](https://user-images.githubusercontent.com/28592665/38429092-1aaa7df6-39c6-11e8-9a9e-b3d291ad1ecd.png)

**Comment by palypster** [comment]
MariaDB is not supported, see https://docs.getcraftable.com/v2/#/craftable?id=requirements
