### ISSUE TITLE
[object Object] on translated model.

### ISSUE THREAD

**Issue by GonrasK** [BRACKETS-by-TRIAD/craftable#291]
After creating a model and generating an admin panel for it, I tried to create a translatable version of it, and it seems that after changing the locale in the profile settings, it *does* retrieve the right language and translates the model's columns, and the entry that is being saved looks like this in the database - 

```
{"en":"android","he":"אנדרואיד","ru":"андроид"}
```

When I'm accessing http://127.0.0.1:8000/admin/phones/1/edit (which responds to the above db entry), I get [object Object] in all of this model's fields (you can see in the attached screenshot) - 

<img width="472" alt="Screen Shot 2020-12-06 at 16 35 28" src="https://user-images.githubusercontent.com/30444072/101283069-10906580-37e1-11eb-888e-60e547e628fc.png">

In Vue's debugger, I can clearly see that i retrieves the whole model and its' name is indeed an Object which should be pointing to the right locale.
<img width="493" alt="Screen Shot 2020-12-06 at 16 37 06" src="https://user-images.githubusercontent.com/30444072/101283120-49c8d580-37e1-11eb-8fca-4810286fb950.png">

Am I missing something along the process?
Oh and btw - Is there a code for your live demo? Especially for this part - https://demo.getcraftable.com/admin/translatable-articles/1/edit - Where you can easily click on 'manage translations' and it will pop out the other available locales in the same window.

**Comment by GonrasK** [comment]
Oh, and one more thing, in /project/resources/views/admin/phones/components/form-elements.blade.php, in the first form's field - 

```
<div class="form-group row align-items-center" :class="{'has-danger': errors.has('name'), 'has-success': fields.name && fields.name.valid }">
    <label for="name" class="col-form-label text-md-right" :class="isFormLocalized ? 'col-md-4' : 'col-md-2'">{{ trans('admin.phones.columns.name') }}</label>
        <div :class="isFormLocalized ? 'col-md-4' : 'col-md-9 col-xl-8'">
        <input type="text" v-model="form.name" v-validate="'required'" @input="validate($event)" class="form-control" :class="{'form-control-danger': errors.has('name'), 'form-control-success': fields.name && fields.name.valid}" id="name" name="name" placeholder="{{ trans('admin.phones.columns.name') }}">
        <div v-if="errors.has('name')" class="form-control-feedback form-text" v-cloak>@{{ errors.first('name') }}</div>
    </div>
</div>
```

When I change the v-model to "form.name.ru" (for example), it does retrieve the russian version of the name. So I guess there's something missing there between the view and the controller.

**Comment by palypster** [comment]
I'm afraid the problem is, that you have changed the migration AFTER the crud was generated. The forms are not dynamic, so if you make some changes in the database structure, it's not going to be reflected in the generated CRUD.

Try to generate it once again and it should work.

**Comment by GonrasK** [comment]
well, i created this model/table and crud using this link - https://getcraftable.com/docs/6.0/crud-generator
and then I added the HasTranslation trait just like you explained here - https://getcraftable.com/docs/6.0/translatable
Did I miss something along the way?

**Comment by palypster** [comment]
That's weird. It looks like the default locale on model is not set or smtg. Can you try to call:
`$phone->setLocale('ru');`
in your controller and see if it helps?

**Comment by GonrasK** [comment]
It does help. And I even used the source of your demo (specifically - the form.elements.blade.php of the TranslatableArticle) - 

So, going from this automatically generated code (by craftable) - 

```

<div class="form-group row align-items-center" :class="{'has-danger': errors.has('name'), 'has-success': fields.name && fields.name.valid }">
    <label for="name" class="col-form-label text-md-right" :class="isFormLocalized ? 'col-md-4' : 'col-md-2'">{{ trans('admin.service.columns.name') }}</label>
        <div :class="isFormLocalized ? 'col-md-4' : 'col-md-9 col-xl-8'">
        <input type="text" v-model="form.name" v-validate="'required'" @input="validate($event)" class="form-control" :class="{'form-control-danger': errors.has('name'), 'form-control-success': fields.name && fields.name.valid}" id="name" name="name" placeholder="{{ trans('admin.service.columns.name') }}">
        <div v-if="errors.has('name')" class="form-control-feedback form-text" v-cloak>@{{ errors.first('name') }}</div>
    </div>
</div>
```

I took your code and changed it to -
```


<div class="row">
    @foreach($locales as $locale)
        <div class="col-md" v-show="shouldShowLangGroup('{{ $locale }}')" v-cloak>
            <div class="form-group row align-items-center" :class="{'has-danger': errors.has('name_{{ $locale }}'), 'has-success': this.fields.name_{{ $locale }} && this.fields.name_{{ $locale }}.valid }">
                <label for="name_{{ $locale }}" class="col-md-2 col-form-label text-md-right">{{ trans('admin.service.columns.name') }}</label>
                <div class="col-md-9" :class="{'col-xl-8': !isFormLocalized }">
                    <input type="text" v-model="form.name.{{ $locale }}" v-validate="'required'" @input="validate($event)" class="form-control" :class="{'form-control-danger': errors.has('name_{{ $locale }}'), 'form-control-success': this.fields.name_{{ $locale }} && this.fields.name_{{ $locale }}.valid }" id="name_{{ $locale }}" name="name_{{ $locale }}" placeholder="{{ trans('admin.service.columns.name') }}">
                    <div v-if="errors.has('name_{{ $locale }}')" class="form-control-feedback form-text" v-cloak>{{'{{'}} errors.first('name_{{ $locale }}') }}</div>
                </div>
            </div>
        </div>
    @endforeach
</div>
```

And Voila! The right fields are being retrieved now on the the edit and create pages.

![Screen Shot 2020-12-08 at 11 16 16](https://user-images.githubusercontent.com/30444072/101463999-ccb77080-3946-11eb-9d45-aac825bddfea.png)

But when I'm trying to save it, it give me an error message on the bottom right of the page.
![Screen Shot 2020-12-08 at 11 17 06](https://user-images.githubusercontent.com/30444072/101464112-ea84d580-3946-11eb-87f8-0d5f71ddc7cf.png)

So I guess there's some little tweak that i need to do with the controller or the model itself to *know* how to get this data.
But the problem is like you said - I probably didn't generate the model/crud correctly from the very first place.

What are the correct steps to create a translatable model and achieve this multiple-language view as I attached in the screenshot?

**Comment by GonrasK** [comment]
Oh, and of course I added all this part from your demo source code into form-elements.blade.php -

```
<div class="row form-inline" style="padding-bottom: 10px;" v-cloak>
    <div :class="{'col-xl-10 col-md-11 text-right': !isFormLocalized, 'col text-center': isFormLocalized, 'hidden': onSmallScreen }">
        <small>{{ trans('brackets/admin-ui::admin.forms.currently_editing_translation') }}<span v-if="!isFormLocalized && otherLocales.length > 1"> {{ trans('brackets/admin-ui::admin.forms.more_can_be_managed') }}</span>
            <span v-if="!isFormLocalized"> | <a href="#" @click.prevent="showLocalization">{{ trans('brackets/admin-ui::admin.forms.manage_translations') }}</a></span></small>
        <i class="localization-error" v-if="!isFormLocalized && showLocalizedValidationError"></i>
    </div>

    <div class="col text-center" :class="{'language-mobile': onSmallScreen, 'has-error': !isFormLocalized && showLocalizedValidationError}" v-if="isFormLocalized || onSmallScreen" v-cloak>
        <small>{{ trans('brackets/admin-ui::admin.forms.choose_translation_to_edit') }}
            <select class="form-control" v-model="currentLocale">
                <option :value="defaultLocale" v-if="onSmallScreen">@{{defaultLocale.toUpperCase()}}</option>
                <option v-for="locale in otherLocales" :value="locale">@{{locale.toUpperCase()}}</option>
            </select>
            <i class="localization-error" v-if="isFormLocalized && showLocalizedValidationError"></i>
            <span>|</span>
            <a href="#" @click.prevent="hideLocalization">Hide Translations</a>
        </small>
    </div>
</div>
```

**Comment by palypster** [comment]
Correct steps are:

1. create migration file with jsonb columns
2. run this migration
3. run admin:generate

As long as you use jsobn columns, generator will guess that you want to create translatable eloquent and will take care of everything.

I think what you did was:
1. create migration file without jsonb columns
2. run this migration
3. run admin:generate
4. changed columns in migration to jsonb columns
5. re-run the migration

but in this case the CRUD was already generated WITHOUT support for translatable models.

Let me know if that worked for you.

**Comment by GonrasK** [comment]
And here's how my model is constructed - 
```
<?php

namespace App\Models;
use Brackets\Translatable\Traits\HasTranslations;

use Illuminate\Database\Eloquent\Model;

class Phone extends Model
{
    use HasTranslations;

    protected $fillable = [
        'name',
        'slug',
        'description',
        'meta_title',
        'meta_description',
        'icon_class',
        'published_at',
        'enabled',

    ];

    protected $dates = [
        'published_at',
        'created_at',
        'updated_at',

    ];
    public $translatable = ['name','slug','description','meta_title','meta_description'];

    protected $appends = ['resource_url'];


    /* ************************ ACCESSOR ************************* */

    public function getResourceUrlAttribute()
    {
        return url('/admin/services/'.$this->getKey());
    }

}
```

**Comment by GonrasK** [comment]
Well, I followed your steps to create a new migration called 'general_service', here are the steps I followed -

1. ```php artisan make:migration create_general_services_table --create=general_services```
2. ```php artisan migrate```
3. ``` php artisan admin:generate general_services```

Everything was created successfully without any errors/warnings, but when I go to the admin panel to show the index (http://127.0.0.1:8000/admin/general-services) , it gives me a blank page (with the sidebar though), and the console error says - 
![Screen Shot 2020-12-08 at 11 53 55](https://user-images.githubusercontent.com/30444072/101468432-0f2f7c00-394c-11eb-979b-06782863f019.png)

**Comment by GonrasK** [comment]
Oh, and the migration looks like this - 

```
<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateGeneralServicesTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('general_services', function (Blueprint $table) {
            $table->id();
            $table->jsonb('name');
            $table->jsonb('slug');
            $table->jsonb('description');
            $table->jsonb('meta_title');
            $table->jsonb('meta_description');
            $table->string('icon_class');
            $table->date('published_at')->nullable();
            $table->boolean('enabled')->default(true);
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('general_services');
    }
}
```

**Comment by palypster** [comment]
I forgot the last step of course :)
4. npm run den

**Comment by GonrasK** [comment]
Great! Works like a charm. Thank you.

And by the way, are you going to address this security warning regarding axios?

![Screen Shot 2020-12-08 at 13 17 24](https://user-images.githubusercontent.com/30444072/101477308-b8c83a80-3957-11eb-8e0f-f43ae7000d39.png)
