### ISSUE TITLE
Styles and js file dont load

### ISSUE THREAD

**Issue by natan5000** [BRACKETS-by-TRIAD/craftable#292]
<img width="959" alt="Capture1" src="https://user-images.githubusercontent.com/53131837/101380213-d673a200-387a-11eb-8f0d-12d8a3509d56.PNG">

i'm beginner. I try install craftable in my proyect but i have this issues, the css and js style don't load. But when i use the code inspector and try add this ../../public to href to style load. But i don't know, what file change that. Thanks for yours support

<img width="954" alt="Capture5" src="https://user-images.githubusercontent.com/53131837/101380629-60bc0600-387b-11eb-825b-cb7c5169d26d.PNG">

**Comment by palypster** [comment]
sorry, this is related to you server configuration probbaly, I guess you are installing craftable on a subdirectory (i.e. `localhost/my-project`). Try change it on a domain with no directory (i.e. localhost) and it should help.
