### ISSUE TITLE
Translations issue on admin-auth template

### ISSUE THREAD

**Issue by gianni** [BRACKETS-by-TRIAD/craftable#294]
Hi,

In the admin auth pages (login, forgot password, reset password ..etc) are no more translated the labels even if are presents in the translations table.
All the labels, instead,  are correctly traslated  when the user is logged in the admin area.
I have already tried to clear views cache, but it doesn't fix the issue

Any idea about it?
Thanks

**Comment by gianni** [comment]
Is there a way usign artisan command to re-generate only the auth pages?
Using scan translations utility i doesn'tt find any label used in these pages ..so it isn't possibile to set the translation ..
![image](https://user-images.githubusercontent.com/14415/101834942-4d3ec280-3b3b-11eb-8d10-a7d27b4bdf86.png)

**Comment by palypster** [comment]
The problem actually lies elsewhere I think. When you log in, craftable uses User's locale. But when you are not, then it is using the default locale. You probably changed the default one and forgot to actually translate those. Or something like that. Let me know please if that helped.

**Comment by gianni** [comment]
Hi @palypster,
Thanks a lot for your answer.
Yes the problem was the locale that was different to EN. ;)
