### ISSUE TITLE
How to install craftable v5 and is it working with PHP 7.3 ?

### ISSUE THREAD

**Issue by mansourcodes** [BRACKETS-by-TRIAD/craftable#296]
I have tried to install craftable --lts on my PHP 7.3 server 

Using Method : 
`craftable new --lts my_project` 

that end me with these errors : 
<img width="849" alt="Screen Shot 2020-12-14 at 4 42 18 PM" src="https://user-images.githubusercontent.com/3064487/102088217-ace2e980-3e2b-11eb-9b95-73e17d55714a.png">

so how could I install craftable v5 that worked with PHP 7.2+ 
or pass this error

**Comment by palypster** [comment]
you are missing ext-zip on your system
