### ISSUE TITLE
Vue + Vuetify , Instead of Bootstrap + CoreUI

### ISSUE THREAD

**Issue by ravdeepsingh22** [BRACKETS-by-TRIAD/craftable#299]
Vue + Vuetify , Instead of Bootstrap + CoreUI would be an Awesome Enhancement that could make this generator super unique and popular as compared to other generators

**Comment by palypster** [comment]
relates to #301, #302 and #303

**Comment by palypster** [comment]
Sorry, we won't follow this one as long as we are working on a new Craftable Pro that will use VueJS3 & theme based on TailwindUI.
