### ISSUE TITLE
Brackets/illuminate conflict on new project 

### ISSUE THREAD

**Issue by steveijar** [BRACKETS-by-TRIAD/craftable#305]
I'm still getting the error mentioned in issue #290 

 Problem 1
    - Root composer.json requires brackets/craftable ^5.1 -> satisfiable by brackets/craftable[v5.1.0].
    - brackets/craftable v5.1.0 requires illuminate/support ^6.0|^7.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

Follwed the instructions, composer global update, then craftable new projectname (also tried lts cmd and that didn't help), but it still doesn't work for me!
Heres my composer global info!

PS F:\docker\laraadmin> composer global info
Changed current directory to C:/Users/steve/AppData/Roaming/Composer
brackets/craftable-installer     v2.0.1  Craftable application installer.
psr/container                    1.0.0   Common Container Interface (PHP FIG PSR-11)
symfony/console                  v5.2.1  Symfony Console Component
symfony/polyfill-ctype           v1.20.0 Symfony polyfill for ctype functions
symfony/polyfill-intl-grapheme   v1.20.0 Symfony polyfill for intl's grapheme_* functions
symfony/polyfill-intl-normalizer v1.20.0 Symfony polyfill for intl's Normalizer class and related ...
symfony/polyfill-mbstring        v1.20.0 Symfony polyfill for the Mbstring extension
symfony/polyfill-php73           v1.20.0 Symfony polyfill backporting some PHP 7.3+ features to lo...
symfony/polyfill-php80           v1.20.0 Symfony polyfill backporting some PHP 8.0+ features to lo...
symfony/process                  v5.2.1  Symfony Process Component
symfony/service-contracts        v2.2.0  Generic abstractions related to writing services
symfony/string                   v5.2.1  Symfony String component

Is there anything else I can try?

**Comment by bernietai** [comment]
+1, error is similar but different version: 

` 
Problem 1
    - Root composer.json requires brackets/admin-generator ^6.1 -> satisfiable by brackets/admin-generator[6.1.0].
    - brackets/admin-generator 6.1.0 requires illuminate/support ^8.0 -> found illuminate/support[v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
`

**Comment by palypster** [comment]
You guys have some package in your global composer that is in conflict with requirements of the one craftable installers uses. 

Can you paste here the composer.json of your global composer? On OSX I have it here:
```cat ~/.composer/composer.json```

**Comment by steveijar** [comment]
My composer file doesn't show much, I believe the codesniffer is for VS Code!

{
    "require": {
        "brackets/craftable-installer": "^2.0",
        "squizlabs/php_codesniffer": "^3.5"
    }
}

I did composer global show -i -t, if this is any more help?


brackets/craftable-installer v2.0.1 Craftable application installer.
├──ext-zip *
├──symfony/console ~3.0|~4.0|~5.0
│  ├──php >=7.2.5
│  ├──symfony/polyfill-mbstring ~1.0
│  │  └──php >=7.1
│  ├──symfony/polyfill-php73 ^1.8
│  │  └──php >=7.1
│  ├──symfony/polyfill-php80 ^1.15
│  │  └──php >=7.1
│  ├──symfony/service-contracts ^1.1|^2
│  │  ├──php >=7.2.5
│  │  └──psr/container ^1.0
│  │     └──php >=5.3.0
│  └──symfony/string ^5.1
│     ├──php >=7.2.5
│     ├──symfony/polyfill-ctype ~1.8
│     │  └──php >=7.1
│     ├──symfony/polyfill-intl-grapheme ~1.0
│     │  └──php >=7.1
│     ├──symfony/polyfill-intl-normalizer ~1.0
│     │  └──php >=7.1
│     ├──symfony/polyfill-mbstring ~1.0
│     │  └──php >=7.1
│     └──symfony/polyfill-php80 ~1.15
│        └──php >=7.1
└──symfony/process ~3.0|~4.0|~5.0
   ├──php >=7.2.5
   └──symfony/polyfill-php80 ^1.15
      └──php >=7.1
squizlabs/php_codesniffer 3.5.8 PHP_CodeSniffer tokenizes PHP, JavaScript and CSS files and detects violations of a defined set of coding standards.
├──ext-simplexml *
├──ext-tokenizer *
├──ext-xmlwriter *
└──php >=5.4.0

**Comment by palypster** [comment]
Can you please try to update your craftable installer once again, I have noticed we didn't really released the new version (my mistake). You should see v2.0.2:
https://github.com/BRACKETS-by-TRIAD/craftable-installer/releases/tag/v2.0.2

```
± % craftable -V 
Craftable Installer 2.0.2
```

and then try again please.

**Comment by s00ar** [comment]
> I'm still getting the error mentioned in issue #290
> 
> Problem 1 - Root composer.json requires brackets/craftable ^5.1 -> satisfiable by brackets/craftable[v5.1.0]. - brackets/craftable v5.1.0 requires illuminate/support ^6.0|^7.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.
> 
> Follwed the instructions, composer global update, then craftable new projectname (also tried lts cmd and that didn't help), but it still doesn't work for me! Heres my composer global info!
> 
> PS F:\docker\laraadmin> composer global info Changed current directory to C:/Users/steve/AppData/Roaming/Composer brackets/craftable-installer v2.0.1 Craftable application installer. psr/container 1.0.0 Common Container Interface (PHP FIG PSR-11) symfony/console v5.2.1 Symfony Console Component symfony/polyfill-ctype v1.20.0 Symfony polyfill for ctype functions symfony/polyfill-intl-grapheme v1.20.0 Symfony polyfill for intl's grapheme_* functions symfony/polyfill-intl-normalizer v1.20.0 Symfony polyfill for intl's Normalizer class and related ... symfony/polyfill-mbstring v1.20.0 Symfony polyfill for the Mbstring extension symfony/polyfill-php73 v1.20.0 Symfony polyfill backporting some PHP 7.3+ features to lo... symfony/polyfill-php80 v1.20.0 Symfony polyfill backporting some PHP 8.0+ features to lo... symfony/process v5.2.1 Symfony Process Component symfony/service-contracts v2.2.0 Generic abstractions related to writing services symfony/string v5.2.1 Symfony String component
> 
> Is there anything else I can try?

I've fixed it with 
composer global require "brackets/craftable-installer" --with-all-dependencies
