### ISSUE TITLE
After php artisan admin:generate vendor

### ISSUE THREAD

**Issue by mreading2020** [BRACKETS-by-TRIAD/craftable#307]
The menu shows and when I click it the page loads and immediately refreshes. Any help would be much appreciated

. 
I have attached a short vide
[screen-recording(1).zip](https://github.com/BRACKETS-by-TRIAD/craftable/files/5765682/screen-recording.1.zip)
o for you to review

**Comment by vuongnguyen1996** [comment]
It seems you missed this line in the document:
https://getcraftable.com/docs/7.0/crud-generator
```
Finally we need to re-compile all the assets:
npm run dev
```
