### ISSUE TITLE
Fresh install - npm run dev error

### ISSUE THREAD

**Issue by libarra-fusap** [BRACKETS-by-TRIAD/craftable#308]
Made a fresh install and got this error when running `npm run dev` :

```
> @ dev /var/www/html
> npm run development


> @ development /var/www/html
> mix

ERROR in ./node_modules/vue-quill-editor/src/editor.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|   <div class="quill-editor">
|     <slot name="toolbar"></slot>

webpack compiled with 1 error
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
```
I'm running the app using a Docker container

* PHP: 7.4.11
* PHP-CLI: 7.4.11
* Node: v12.20.1
* npm: 6.14.10

I got the same error installing Craftable with both global and manual approaches with composer. It seems to be a problem with `vue-quill-editor` package, which I found to be used at `resources/js/admin/admin.js` and seems to need an appropiate loader, like `vue-loader` for example.

How can I fix this? I didn't get this error on version 5.0. Thanks in advance and I'm sorry for my poor english.

**Comment by ibrahimyu** [comment]
New to craftable, same issue. I tried adding loader manually to webpack.mix.js, but nothing, same error.

**Comment by zigcBenx** [comment]
Is this issue fixed?
I just tried creating new app with **craftable** and still got the same error message after running `sail npm run dev`.

**Comment by Raymoneto** [comment]
npm install vue-quill-editor --save 

Install the quill-editor with the command above, and the issue will be fixed

**Comment by mflash123** [comment]
> npm install vue-quill-editor --save
> 
> Install the quill-editor with the command above, and the issue will be fixed

It fixed issue. But another bug started.
After success npm run dev, you cant access any page.
Error : 
`[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.`

**This is really amazing. Bad quality testing release!**

**Comment by MichaGodefroij** [comment]
@mflash123 This should be fixed when you change

`mix.js(['resources/js/admin/admin.js'], 'public/js').sass('resources/sass/admin/admin.scss', 'public/css')`

to

`mix.js(['resources/js/admin/admin.js'], 'public/js').sass('resources/sass/admin/admin.scss', 'public/css').vue();`

as done in commit [7f54535](https://github.com/BRACKETS-by-TRIAD/admin-ui/commit/7f54535b1e872d046f2566814b8e37414ea20dc3)

**Comment by RichardDominik** [comment]
Hey, we have published new release. Try to update the installer with: ```composer global update``` and then try again please.

**Comment by GonrasK** [comment]
hey. is there any explanation about the new release? anything we should consider before updating?

**Comment by palypster** [comment]
We have released bugfix to Craftable installation. If you already have Craftable installed, then this update does not affect you in no any way.

I'm closing this now, as I can confirm installation is not failing anymore. If it is still failing, please let us know and provide more information. Thank you.
