### ISSUE TITLE
stuck at Deleting previous files finished.

### ISSUE THREAD

**Issue by gopikiller** [BRACKETS-by-TRIAD/craftable#309]
I was trying to install craftable in my existing project by manual installation.

After running `php artisan craftable:install`

 stuck at `Deleting previous files finished.`

![IMG_20210117_081013](https://user-images.githubusercontent.com/31792031/104829628-994bf800-589b-11eb-93b4-802b9aeedaea.jpg)

I was waited more than 20min. But nothing happens

**Comment by palypster** [comment]
Interesting. Unfortunately, we cannot replicate this. Try to investigate it a bit deeper please.

**Comment by rbaffoe** [comment]
Same. Stuck on new install. PHP@7.4 on Mac.
<img width="574" alt="Screenshot 2021-05-15 at 22 23 00" src="https://user-images.githubusercontent.com/4161083/118378482-1da15400-b5cc-11eb-9d1a-d40d6540bb83.png">

**Comment by esorone** [comment]
I have the same issue, manual install and on a Mac
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/3120828/130293097-b8ceca87-c2a3-4064-8f0e-38f152d4d7d8.png">
