### ISSUE TITLE
Implementing user roles on edition and creation

### ISSUE THREAD

**Issue by makrosloro** [BRACKETS-by-TRIAD/craftable#310]
Hiya all,

Is there a way to implement more than Administrator role taking same admin guard?

I've added via migration 2 more Spatiel laravel roles and I'm getting into select on edition and creation form. When saving, user is created on admin_user table but model_has:roles table has anything...

Any clue to solve this?

**Comment by palypster** [comment]
We have a dozen of projects with different roles, everything works out of the box, you just create the roles in the database and everything should work smoothly.
