### ISSUE TITLE
Disable semantics on wysiwyg editor

### ISSUE THREAD

**Issue by GonrasK** [BRACKETS-by-TRIAD/craftable#311]
The way you configured the vue-trumbowyg editor forces my code to replace <div> tags with <p> tags (and all other bunch of html tags). This is easy to solve using some extra parameters on the admin.js file when calling the editor - 

```
jQuery.trumbowyg = {
    langs: {
        en: {
            viewHTML: 'View HTML',

            undo: 'Undo',
            redo: 'Redo',

            formatting: 'Formatting',
            p: 'Paragraph',
            blockquote: 'Quote',
            code: 'Code',
            header: 'Header',

            bold: 'Bold',
            italic: 'Italic',
            strikethrough: 'Strikethrough',
            underline: 'Underline',

            strong: 'Strong',
            em: 'Emphasis',
            del: 'Deleted',
            semantic: false,

            superscript: 'Superscript',
            subscript: 'Subscript',

            unorderedList: 'Unordered list',
            orderedList: 'Ordered list',

            insertImage: 'Insert Image',
            link: 'Link',
            createLink: 'Insert link',
            unlink: 'Remove link',

            justifyLeft: 'Align Left',
            justifyCenter: 'Align Center',
            justifyRight: 'Align Right',
            justifyFull: 'Align Justify',

            horizontalRule: 'Insert horizontal rule',
            removeformat: 'Remove format',

            fullscreen: 'Fullscreen',

            close: 'Close',

            submit: 'Confirm',
            reset: 'Cancel',

            required: 'Required',
            description: 'Description',
            title: 'Title',
            text: 'Text',
            target: 'Target',
            width: 'Width'
        }
    },
```

I can simply add the 'semantic: false' property there or exclude specific tags to be converted. But after running 'npm run dev' once again - it deletes all my changes to this file. How can I solve this?

* Leaving my specific use-case aside - it could be actually quite cool if you'd let us configure the wysiwyg by ourselves, or even inject a different type of editor besides trumbowyg.

**Comment by GonrasK** [comment]
hey guys..any response?
i can't really add any option to the ```mediaWysiwygConfig``` since every time i ```npm run dev``` it changes it back to its' default option.

**Comment by RichardDominik** [comment]
Hey, if you want to customize the editor, just follow the steps as described in documentation https://getcraftable.com/docs/7.0/user-interface#media-wysiwyg
