### ISSUE TITLE
Critical issue with laravel v.8 and craftable v.7 

### ISSUE THREAD

**Issue by mustafaabduljalil** [BRACKETS-by-TRIAD/craftable#312]
I can't open admin because there is syntax error in media file in vendor 
syntax error, unexpected '$conversion' (T_VARIABLE), expecting ',' or ')' ?!!

**Comment by palypster** [comment]
Can you attach some screen, URL, if this is on the first load of the homepage or login form or after the login - please, be more specific.

**Comment by mustafaabduljalil** [comment]
![carftable](https://user-images.githubusercontent.com/14807431/105361497-6b9be180-5c02-11eb-8e52-e336aa8760ac.png)

@palypster

**Comment by splatEric** [comment]
@mustafaabduljalil that screenshot doesn't include the line that has the syntax error ... but the path for the exception is pointing at vendor/spatie/laravel-medialibrary ... which suggests its further down the dependency tree rather than a craftable issue
