### ISSUE TITLE
Unable to create a new admin user.

### ISSUE THREAD

**Issue by Evanzsnr** [BRACKETS-by-TRIAD/craftable#315]
I had to reset my database because of some reason but now am unable to create a new admin user. How do I create one if I already  generated the crud for the admin?

**Comment by palypster** [comment]
just run migrations. There should be one migration that creates the default user. Password is hard-coded in that migration.

**Comment by humbertodomizi** [comment]
It is a very common problem, I created a user through a seeder, I even assigned it a role, but the only user that has access as administrator is the user with ID 1, so we cannot enter once we do migrate: fresh.
The user should be created with a seeder that we can modify for each project, then we could create a repository of a personal project, which can be easily edited.

Greetings
