### ISSUE TITLE
PHP8

### ISSUE THREAD

**Issue by jpogil** [BRACKETS-by-TRIAD/craftable#316]
Hi, 

I'm getting this when i'm trying to "composer install" with PHP8.
What should i do?

- Root composer.json requires brackets/craftable ^6.0 -> satisfiable by brackets/craftable[6.0.0].
- brackets/craftable 6.0.0 requires php ^7.4.0 -> your php version (8.0.2) does not satisfy that requirement.

Thanks in advance.

**Comment by palypster** [comment]
Craftable v6 does not support php8. Use v7 instead.
