### ISSUE TITLE
Login problem - docs

### ISSUE THREAD

**Issue by Heqma** [BRACKETS-by-TRIAD/craftable#317]
Can you tell me how can i test your cmsgenerator when just i cannot log in with THIS: "Password: use password from you clipboard"

**Comment by Heqma** [comment]
i changed email and password with bcrypt  generator and it still not working.. *_*

**Comment by palypster** [comment]
The default admin password is printed during installation, but also can be found in the generated migration file.

**Comment by landito82** [comment]
Where can I see those migration files? when I installed it didn't print the passwords too.
