### ISSUE TITLE
There are no commands defined in the "admin" namespace

### ISSUE THREAD

**Issue by systemshq** [BRACKETS-by-TRIAD/craftable#322]
Tried the following to generate a CRUD interface and am getting the following error:-

```
composer global require brackets/craftable-installer
craftable new lch
cd lch (make sure database config is ok)
php artisan admin:generate ActivityStatus

There are no commands defined in the "admin" namespace
```

**Comment by palypster** [comment]
Before using admin:generate, you have to actually install the craftable. 

https://www.getcraftable.com/docs/7.0/installation#new-project

From docs:
> and then follow the instructions in the following section.

but I guess it's not 100% clear to everyone, if you have missed it. We probably explicitly write there the install command.

`craftable install`

**Comment by systemshq** [comment]
If I do this then I get an error complaining about docker not working properly. Please advise.

```
$ craftable install

 Which services would you like to install? [mysql]:
  [0] mysql
  [1] pgsql
  [2] redis
  [3] memcached
  [4] meilisearch
  [5] mailhog
  [6] selenium
 > 0

Sail scaffolding installed successfully.
Docker is not running.
Crafting Craftable :) ...
Docker is not running.
Docker is not running.
Aborted.
```

**Comment by palypster** [comment]
Well, and do you have Docker running?

More info:
https://laravel.com/docs/8.x/sail#introduction

**Comment by palypster** [comment]
Try run:
`docker ps`

**Comment by systemshq** [comment]
```
peter@tiktok:/var/www/html/lch$ docker ps
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/json: dial unix /var/run/docker.sock: connect: permission denied
```

**Comment by palypster** [comment]
Yep, that's the problem. But this has nothing to do with Craftable, so I cannot help sorry. But once you got it working, Craftable installation should work smoothly.

**Comment by systemshq** [comment]
I've added myself to the docker group and I have also had to install docker-compose. I think the docs just need to mention that you need a basic docker and docker-compose install  and add yourself to the docker group then everything is ok. 

Many thanks for your help

**Comment by palypster** [comment]
We

**Comment by palypster** [comment]
Docker is mentioned indirectly (Sail is mentioned with the link to the docs to the Sail). But yeah, it could be written more user-friendly. We will have one more look into it.

**Comment by systemshq** [comment]
Many thanks for your quick response today. I've got something up and running now👍👍
