### ISSUE TITLE
Not compatible with Laravel 8

### ISSUE THREAD

**Issue by miguelfspinto** [BRACKETS-by-TRIAD/craftable#325]
I had the following error:

```
composer require brackets/craftable
Using version ^5.1 for brackets/craftable
./composer.json has been updated
Running composer update brackets/craftable
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires brackets/craftable ^5.1 -> satisfiable by brackets/craftable[v5.1.0].
    - brackets/craftable v5.1.0 requires illuminate/support ^6.0|^7.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but it conflicts with another require.


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by GauravG8** [comment]
I have faced the same issue too. Is craftable not supporting laravel 8?

**Comment by palypster** [comment]
Latest Craftable (v7) supports Laravel 8. Not sure why your composer chooses v5.1 instead, there must be something specific to your project.

**Comment by GauravG8** [comment]
I setup the project with a fresh laravel installer v4.2.4, composer v2.0.12 and php v7.4. Still got this error. Its in Windows 10 if that helps.

**Comment by palypster** [comment]
And what happens when you try to explicitly tell composer to instal v7?
`composer require brackets/craftable:7`
what error do you get?

**Comment by GauravG8** [comment]
Yes that seems to work. Was able to setup a project with craftable. Had previously tried `composer global require "brackets/craftable-installer=~7.0"`. But that threw an error.

`composer require brackets/craftable:7` worked perfectly. Thank you for your help.
