### ISSUE TITLE
CRUD Model edit button links to undefined

### ISSUE THREAD

**Issue by WalterWoshid** [BRACKETS-by-TRIAD/craftable#328]
I created a CRUD model with `php artisan admin:generate users` and it shows me the model successfully, but the edit button links to `admin/undefined/edit`

![See picture](https://i.imgur.com/wOoLlva.png)

**Comment by fahrim** [comment]
If you look at the web.php rotation and how the edit button works in the blade structure, I hope you can solve the problem.

**Comment by palypster** [comment]
ref #348

**Comment by X-NoRC** [comment]
I've run into this same problem where all my edit buttons link to '/admin/undefined/edit' rather than for example '/admin/servers/1/edit'.

**Comment by robertox85** [comment]
You must edit app/Models/User.php and add

` protected $appends = ['resource_url'];

    public function getResourceUrlAttribute()
    {
        // Assumendo che tu abbia una route nominata per la visualizzazione/modifica degli utenti
        return url('/admin/users/' . $this->getKey());
    }`

**Comment by robertox85** [comment]
@WalterWoshid You must edit app/Models/User.php and add the following code at the bottom

```php
protected $appends = ['resource_url'];
    public function getResourceUrlAttribute()
    {
        return url('/admin/users/' . $this->getKey());
    }
```
