### ISSUE TITLE
Not seeing how to disable pagination

### ISSUE THREAD

**Issue by givihuda** [BRACKETS-by-TRIAD/craftable#329]
So, I see in the Craftable 7 docs that pagination is on by default, and how to add pagination manually to get()... but I'm not seeing how to just disable it.

I notice in vendor/brackets/admin-listing/src/AdminListing.php function processRequestAndGet that request key 'bulk' can be passed as truthy (though I'm not sure what value should be passed... 1?), but our interface doesn't have a way to do this (nor should users have to type ?bulk=1 into the URL), and I'm maybe not familiar enough with Craftable or Laravel to see how this should be done (or if this is proper).

```
        // we want to attach pagination if bulk filter is disabled otherwise we want to select all data without pagination
        if (!$request->input('bulk')) {
            $this->attachPagination($request->input('page', 1), $request->input('per_page', $request->cookie('per_page', 10)));
        }
```

I'm sure there's a hundred hacky/improper ways to do this, but without there being a checkbox or something like that on the interface to disable pagination, I'm not sure how to make it happen, even if it's just for a certain Controller.

**Comment by givihuda** [comment]
Can I please get a developer response to this issue? I'm feeling like Craftable does not support their own product anymore, and the documentation is very minimal.

**Comment by palypster** [comment]
Hi, you should look at the `processRequestAndGet` method only as a quick helper. If you want to customize the listing, you should build it on your own (just like you build queries using laravel query builder).

Literally, you can copy&paste the code from the `processRequestAndGet` and delete the pagination, so smtg like this:

```
        // process all the basic stuff
        $this->attachOrdering($request->input('orderBy', $this->model->getKeyName()), $request->input('orderDirection', 'asc'))
            ->attachSearch($request->input('search', null), $searchIn);

        // execute query and get the results
        return $this->get($columns);
```
