### ISSUE TITLE
craftable new --lts craftable     The "--lts" option does not exist.

### ISSUE THREAD

**Issue by davegear** [BRACKETS-by-TRIAD/craftable#330]
I'm following the README.me, which mentions Craftable 6 (I thought 7 was the latest), and running suggested command `craftable new --lts craftable` (after `composer global require "brackets/craftable-installer"`) I get error "The "--lts" option does not exist." I even tried the command as copy-paste in case I mistyped. 

When I type `craftable`, it says:

```
Craftable Installer 2.0.4

Usage:
  command [options] [arguments]

Options:
  -h, --help            Display help for the given command. When no command is given display help for the list command
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```

I'm not seeing the options l, t, or s there... I'm confused.

Is the README.md out of date? Or am I supposed to be using an older version of the craftable command for this repo? The repo's last commit was Jan 4... Craftable's documentation is for version 7. https://getcraftable.com/docs/7.0/overview

I'm currently trying to learn it for a project I inherited, so I'm a little confused on why it isn't working.

**Comment by palypster** [comment]
Sorry, README is out of date. Please follow the docs:
https://getcraftable.com/docs/7.0/installation#installer

In v7 we dropped support for LTS Laravel versions, hence `--lts` flag is no longer supported.
