### ISSUE TITLE
Craftable install Aborted

### ISSUE THREAD

**Issue by sufyan568** [BRACKETS-by-TRIAD/craftable#331]
i am installing craftable 
composer global require brackets/craftable-installer
craftable new my_project
craftable install
installation aborted.
![image](https://user-images.githubusercontent.com/68376237/114562096-9e94c500-9c87-11eb-825f-3b0449610bd5.png)

how to fix this issue.

**Comment by palypster** [comment]
It's not clear from the screenshot, but my guess you are in the wrong directory.

`craftable new my_project` creates new directory `my_project`.

Can you please check?

**Comment by sufyan568** [comment]
**composer global require brackets/craftable-installer**
**craftable new my_project**
these commands run perfectly.
inside the **my_project**, run comond **Craftable install** then response is craftable install **aborted**

![image](https://user-images.githubusercontent.com/68376237/114659829-b6af2780-9d0d-11eb-9ce5-8739279392c9.png)

![image](https://user-images.githubusercontent.com/68376237/114659918-dba39a80-9d0d-11eb-8162-f9be19ada3bc.png)

**Comment by palypster** [comment]
Sorrym, I still don't see whole output and I still think you are in the wrong directory:

A) either you create new Craftable project, then:
- `craftable new my_project`
- `cd my_project` <----- this is the line I don't see in your screenshots
- `craftable install`

B) in the very last screenshot you are trying something completely different, you are requiring `brackets/craftable`, but that's something you use when you already have a Laravel project and tries to instal Cratable. So this is completely different approach. I'm not sure, which one you actually want to go for.

**Comment by palypster** [comment]
I've updated the docs, to be more explicit about this:
https://www.getcraftable.com/docs/7.0/installation#new-project

**Comment by hlo2109** [comment]
The same thing happens to me, I already checked all the versions of my development but it does not work for me
![cmd_3rGO5OyMPK](https://user-images.githubusercontent.com/9372840/115129930-3f4cf280-9fb0-11eb-88cb-21836f259809.png)

**Comment by palypster** [comment]
@hlo2109 do you have docker installed and running?

**Comment by hlo2109** [comment]
@palypster no, this system does not work normal without docker

**Comment by palypster** [comment]
https://www.getcraftable.com/docs/7.0/installation#requirements

`By default Craftable uses Docker for its installation. You should checkout out Laravel Sail for more information. If you don't want to use Docker/Sail, use --no-sail flag as described in the New Craftable project section.)`

**Comment by hlo2109** [comment]
In this way??

craftable new my_project
cd my_project
craftable install --no-sail

It doesn't work for me

**Comment by palypster** [comment]
Hmm, that should work. Weird. What's the output?

**Comment by hlo2109** [comment]
Hello, it worked for me: Or very strange, I had already launched the same command several times and it always came out aborted.

Thanks.

**Comment by sufyan568** [comment]
we run these commands are mentioned in documentation.
The issue is not fixed.
Aborted.

**Comment by sufyan568** [comment]
> Hmm, that should work. Weird. What's the output?

Aborted.

No other response.

**Comment by BayuZangetsu** [comment]
this is happen to me too.
I want to add Craftable into my existing project using `craftable install --no-sail` and the result is Aborted

**Comment by sufyan568** [comment]
kindly fix this issue Aborted

**Comment by palypster** [comment]
Believe me, I would gladly fix it, if I had a clue. It's hard to debug it, because it works for me, I see no "Aborted" in my local dev. So I think it's system specific and sorry I cannot afford to invest so much on it to debug several operating systems / environment setups.

You can check the sources of the craftable installer in:
`~/.composer/vendor/bin/craftable`
and/or in:
`~/.composer/vendor/brackets/craftable-installer`
and look what it does and debug step by step. If you find out something, I will definitely help to finish the fix.

**Comment by sufyan568** [comment]
ok i will check and debug the as per your given instructions. @palypster

**Comment by Evin89** [comment]
![image](https://user-images.githubusercontent.com/3153067/120217049-1454f000-c238-11eb-9750-a1645ec14c20.png)

Same error here.

**Comment by sufyan568** [comment]
try composer dump-autoload

**Comment by zero0n3** [comment]
here too. Update laravel package, open terminal (also as admin is the same):
craftable new my_project
cd my_project
craftable install --no-sail

after some seconds i get Aborted. Without any log or printed error. Tried with composer dump-autload but same result. Tried to launch more times install --no-sail but always i get Aborted.

**Comment by BayuZangetsu** [comment]
@palypster can you explain what is the difference result between command `craftable install` with `php artisan craftable:install` ?
because when I use `artisan` command it seem to be work, all asset migrated from `vendor` to `app` and then the app run. other issues using `artisan` command is several undefined code in controller

**Comment by palypster** [comment]
`craftable install` is just a wrapper around `php artisan craftable:install`, look:
https://github.com/BRACKETS-by-TRIAD/craftable-installer/blob/master/src/InstallCommand.php

so if `artisan craftable:install` works for you guys, you can safely use it.

Actually, we have it in our docs under section `Manual installation`:
https://www.getcraftable.com/docs/7.0/installation#manual-instalation

**Comment by zero0n3** [comment]
Guys I found the problem (i suppose it could be the same for you).
here the explenation:
1) craftable new my_project
**2) CREATE A NEW DB AND CONFIGURE IT INSIDE .ENV file inside my_project folder**
3) cd my_project
4 )craftable install

@palypster , in your documentation, it is not so clear that, after having created the project, it is ABSOLUTELY NECESSARY to modify the db inside the .env file before running the install command.
In manual installation it is explained much better.
I think this is the problem that generates the Aborted error for everyone.

**Comment by palypster** [comment]
Yes, I forget to mentioned that, sorry about that guys :-(

This is the reason why `craftable install` command actually tests this before installation, look:
https://github.com/BRACKETS-by-TRIAD/craftable-installer/blob/master/src/InstallCommand.php#L88

if DB is not set up correctly, installation will not continue.

**Comment by eduardo1055433** [comment]
Hello good night, I tried everything that is in the comments but nothing, I can not run it always comes out
![image](https://user-images.githubusercontent.com/48924310/124252628-c2c8ab00-daec-11eb-901b-a65e6677cf30.png)

**Comment by aquaswim** [comment]
here is my current solution:
just install it manually so you will find the error: 

for me it was my php installation doesn't have `ext-exif`
![image](https://user-images.githubusercontent.com/31547551/127300603-27a9b812-914d-43f9-ae3b-1ded6c50f950.png)

after enable the ext i can run `craftable install` without problem.
![image](https://user-images.githubusercontent.com/31547551/127301511-62cbe46d-dbad-4596-ad82-3e4309f2fbaa.png)


ps: i think adding verbose message will help, since running craftable install --verbose still not print anything.

**Comment by Errox** [comment]
As of today, the installer doesn't work when taking all the steps provided by the wiki. 

Either does it work given the solutions from this thread. Is there any solution on this bug yet?

**Comment by palypster** [comment]
@Errox have you read this comment?
https://github.com/BRACKETS-by-TRIAD/craftable/issues/331#issuecomment-853819210

**Comment by Errox** [comment]
> @Errox have you read this comment?
> https://github.com/BRACKETS-by-TRIAD/craftable/issues/331#issuecomment-853819210

Yes, I've read it, still got the same error. Verbose also doesn't provide much information.

**Comment by palypster** [comment]
Can you attach the whole output?

**Comment by YGBReda** [comment]
Hi,
i got the same problem,

so i used the manual installation and its work perfectly 
https://getcraftable.com/docs/7.0/installation#manual-instalation

**Comment by Pablo-hub44** [comment]
how enable the ext ??? 
craftable install --no-sail --verbose not works

**Comment by i2pacg** [comment]
make sure your database is ready and the .env file has the correct database name

**Comment by Kenneth-Inkum** [comment]
On laravel 9 it tries to install craftable 8 and fails either way. Why is there no documentation for craftable version 8.0?

**Comment by khaledminasr** [comment]
when trying to change the the db username and password in ENV file - and then run (craftable install) - this command rewrite the ENV file inside my project with the old values (sail - password), What I should do?

**Comment by palypster** [comment]
> when trying to change the the db username and password in ENV file - and then run (craftable install) - this command rewrite the ENV file inside my project with the old values (sail - password), What I should do?

This is standard behaviour of the Sail:
https://github.com/laravel/sail/blob/1.x/src/Console/InstallCommand.php#L139

If you prefer installing Craftable without Sail, try `--no sail` option:
`craftable install --no-sail`

**Comment by indygill** [comment]
For me on running Craftable 8 on Windows 11 it was php extensions that was causing the problem. Follow the manual install process and composer will let you know which dependencies are failing and why.

**Comment by zroussama** [comment]
> 

![Capture d’écran 2023-02-08 112734](https://user-images.githubusercontent.com/44536203/217504038-71fcde38-039a-4aee-a866-84365fcf3c44.jpg)
didn't work for me too

**Comment by palypster** [comment]
Please, try to install it manually like written in this comment:
https://github.com/BRACKETS-by-TRIAD/craftable/issues/331#issuecomment-853658164

**Comment by dnauroy** [comment]
Hi, I'm trying to install Craftable and here are the problems listed: 
<img width="602" alt="Capture" src="https://user-images.githubusercontent.com/6097264/218803000-95921118-c6bd-41ab-9128-740ed935833a.PNG">
Thanks a lot for your help.

**Comment by palypster** [comment]
@dnauroy is it a fresh laravel install? Paste also your composer.json file. It looks you have some conflicting packages installed already.

**Comment by dnauroy** [comment]
Hi @palypster, yes I have installed Laravel yesterday. Here is the composer.json file:

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.1",
        "guzzlehttp/guzzle": "^7.2",
        "laravel/framework": "^10.0",
        "laravel/sanctum": "^3.2",
        "laravel/tinker": "^2.8",
        "maatwebsite/excel": "^1.1",
        "psr/simple-cache": "2.0"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.0",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "branch-alias": {
            "dev-master": "10.x-dev"
        },
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}

**Comment by dnauroy** [comment]
Maybe the reason why the install fails is because I've installed Laravel 10 and in your doc it is mentioned that Craftable is compatible with Laravel 8...

**Comment by palypster** [comment]
Yes, we haven't released support for Laravel 10 yet. It is compatible with Laravel 9 (not 8) (https://getcraftable.com/docs/8.0/installation). We will release it later.

In the meantime you can try our premium version - [Craftable PRO](https://craftable.pro/), that has already support for Laravel 10.

**Comment by dnauroy** [comment]
Thanks, I will try. Because even with Laravel 9, I can't figure out why the installation process fails :/

<img width="624" alt="Capture" src="https://user-images.githubusercontent.com/6097264/219037757-193419ae-7c72-428b-8ccb-f45a74387ebf.PNG">

**Comment by lupoz** [comment]
If you are using Laravel 9, please make sure that you have downgraded psr/simple-cache to version 2.0 before requiring brackets/craftable:

`composer require psr/simple-cache:^2.0 maatwebsite/excel`

https://getcraftable.com/docs/8.0/installation#manual-instalation

**Comment by War10** [comment]
The steps to install with craftable from 0 are as follows:
1 Create the project: craftable new 'my project'
2. You edit the .env file, change the field values

DB_HOST=localhost
DB_DATABASE=laravel
DB_USERNAME= (you user)
DB_PASSWORD=( you password)

3. Open your app/Providers/AppServiceProvider.php file and inside the boot() method set a default string length:

use Illuminate\Support\Facades\Schema;

public function boot()
{
    Schema::defaultStringLength(191);
}
4. Instead of setting a limit on length I would propose the following, which has worked for me.

Inside:

    config/database.php

replace for  this line for mysql:

'engine' => 'InnoDB ROW_FORMAT=DYNAMIC',

5. Run the installation command:
craftable install --no-sail

**Comment by paullorosa** [comment]
try:
in .env file try:
 DB_HOST=localhost (work for me)
