### ISSUE TITLE
403 This action is unauthorized

### ISSUE THREAD

**Issue by frplc** [BRACKETS-by-TRIAD/craftable#333]
Thank you very much for your work, demo and docs looks very-very nice! 

But unfortunately appearing 403 page in /admin/posts/ 
(after fresh installation, as it described in the guide/video)

`craftable new my_project`

`craftable install --no-sail`

`php artisan make:migration create_posts`

`php artisan migrate`

`php artisan admin:generate --seed posts`

At the same time, sections /admin/admin-users, /admin/translations are available

Could you please tell, why it could be?

**Comment by palypster** [comment]
It's probably because generator generates also the migration that adds sufficient permissions and you probbaly didn't migrate it. Generator actually asks you if you want to migrate it, you maybe selected `No`?

**Comment by frplc** [comment]
Thanks, no, I've choose `yes` on those step

And the case was to make

`php artisan cache:clear`
