### ISSUE TITLE
 App\Models\User does not exist error on installation

### ISSUE THREAD

**Issue by ahmadkureshi** [BRACKETS-by-TRIAD/craftable#334]
Hello, i am trying to install craftable on my latest laravel application version 7.30.4 and my xampp PHP version is 7.2.7 but I am getting error on installation  which is 
In ActivationListener.php line 39:
                                                                                
  class_implements(): Class App\Models\User does not exist and could not be loaded
                                                                                

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

please help to fix this issue shall be thankful

**Comment by ryan-k-t** [comment]
I had a similar issue. I had to create a new directory called `Models` in the existing `app` directory and then copy the existing app\User.php model file that was generated by Laravel when I installed the Auth package and put it in the `app\Models` directory. Then in that Users file change the namespace from `App` to `App/Models`. Finally re-run `composer dump-autoload` and that should do it -- or at least it did for me :wink:

**Comment by ahmadkureshi** [comment]
I will try that. but I think that is not a good fix. but you said you run composer dump-autoload but the craftable installation for abort after the error how  can with just composer dump-autoload can have craftable installed on our project ?

**Comment by ryan-k-t** [comment]
Good question but honestly I don't remember the order in which I executed things --- maybe try moving the User model first then running the compser require statement to pull in craftable?

**Comment by ahmadkureshi** [comment]
ok sure mate let me try and I will share my experience here. but I hope there will be an official fix as this is like manually creating a directory which is not a good practice.
