### ISSUE TITLE
craftable: command not found when creating new project

### ISSUE THREAD

**Issue by heidy-miguel** [BRACKETS-by-TRIAD/craftable#335]
I am trying to create a new project on Ubuntu inside xampp htdocs, after I run the command composer **global require "brackets/craftable-installer"** successfully I get an error on the next step to create a new project: **craftable: command not found**

**Comment by ridha-benromdhane** [comment]
Hello,
I have the same problem, id you find the solution ?

Thanks

**Comment by palypster** [comment]
https://getcomposer.org/doc/03-cli.md#global

`Make sure your global vendor binaries directory is in your $PATH environment variable`
