### ISSUE TITLE
Generation doesn't working with table prefix

### ISSUE THREAD

**Issue by Paw-Tiger** [BRACKETS-by-TRIAD/craftable#339]
My **.env** file contain string
`
DB_PREFIX=bill_
`
My **config/database.php** 
`

            'prefix' => env('DB_PREFIX','bill_'),

`

I have problem in **vendor/brackets/admin-generator/src/Generate/Traits/Columns.php** on line **32**

`   'required' => boolval(Schema::getConnection()->getDoctrineColumn($tableName, $columnName)->getNotnull()),
`

to work around the problem, I replaced the line with this
`'required' => boolval(Schema::getConnection()->getDoctrineColumn("bill_".$tableName, $columnName)->getNotnull()),`

**Comment by palypster** [comment]
Sorry, currently we don't support database prefixes (I have to admit I didn't know the option). But feel free to open a PR for that, I'd accept that.

**Comment by palypster** [comment]
@timoransky maybe feature for a Pro version?
