### ISSUE TITLE
Override login and register forms

### ISSUE THREAD

**Issue by shareef1989** [BRACKETS-by-TRIAD/craftable#34]
How to change the login & register blades to fit with my project requirements.
Is there a way to publish them from the vendor ?

**Comment by palypster** [comment]
This one should be easy - check out https://laravel.com/docs/5.6/packages#views and "Overriding Package Views" section especially. So just place a login & registration blade in the correct directory and you will override craftable's default ones.

**Comment by edianogama** [comment]
@palypster 
How do that ? 
I tried it with laravel explanation, but didn't work for me.
Can you explain with more details ?
