### ISSUE TITLE
How to create a new admin user after fresh migration

### ISSUE THREAD

**Issue by sschuchlenz** [BRACKETS-by-TRIAD/craftable#341]
We have a dev environment with sqlite but on the production server, we use mySQL, therefore we have a fresh database when deploying the app.

How is it possible to create the initial admin user without the initial craftable install process? We tried

`factory(Brackets\AdminAuth\Models\User::class)->create(['email' => 'some_email', 'password' => bcrypt('some_pwd')]);`

but this does not work since the `User::class` is rejected.

Please advise.

**Comment by palypster** [comment]
You are using incorrect class name, it should be AdminUser, not User. Let me know if that worked.

**Comment by sschuchlenz** [comment]
@palypster thanks, that basically created the user (I took the code from the documentation, so I guess this needs fixing ;) )
The only thing is that my added AdminUser (which has the id of 2) is getting "Unauthorized" after login even when setting `forbidden` to 0 - what did I miss?

**Comment by palypster** [comment]
you need to attach the role to it


[BRACKETS]
Pavol Perdík
Managing Director
+421 910 120 009<tel:%20+421%20910%20120%20009>



On 9 Jun 2021, 17:30 +0200, Stefan Schuchlenz ***@***.***>, wrote:

@palypster<https://github.com/palypster> thanks, that basically created the user (I took the code from the documentation, so I guess this needs fixing ;) )
The only thing is that my added AdminUser (which has the id of 2) is getting "Unauthorized" after login even when setting forbidden to 0 - what did I miss?

**Comment by palypster** [comment]
You can get inspiration from the migration file, that populates the first AdminUser.
