### ISSUE TITLE
Enum generate support for  Laravel 8 migrations ?

### ISSUE THREAD

**Issue by akereachu** [BRACKETS-by-TRIAD/craftable#342]
I experienced this issue trying to use  php artisan admin:generate resources  on field, resource_type

Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL57Platform may not support it. 

I solved it using this post https://github.com/doctrine/dbal/issues/3161
but the craftable admin generator does not inherit the Laravel solution.

any ideas? thanks

**Comment by palypster** [comment]
Sorry, we don't support enums, we don't like them very much. We rather recommend the combination of string (varchar) and constrains
- http://komlenic.com/244/8-reasons-why-mysqls-enum-data-type-is-evil/
- https://medium.com/swlh/postgresql-3-ways-to-replace-enum-305861e089bc
