### ISSUE TITLE
Error calling laravel "trans" helper function

### ISSUE THREAD

**Issue by rstriquer** [BRACKETS-by-TRIAD/craftable#343]
**Describe the bug**
It seems to have a problem when we use another package that makes use of the laravel translator. But I couldn't determine if the problem was with the craftable or the other package.

The thing is, the migration hasn't been executed yet, so the table doesn't exist when it's called.

**To Reproduce**
composer create-project laravel/laravel example-app
cd example-app/
composer require biscolab/laravel-recaptcha:5.0.1
composer require brackets/craftable

**Expected behavior**
composer command crashes for "translator" table does not exists

**Screenshots**
![image](https://user-images.githubusercontent.com/669705/122508366-44daaf00-cfd8-11eb-9428-2183417e68e7.png)

**Environment:**
 - OS and server: Ubuntu 20.04
 - PHP version 8.0.7
 - Laravel version v8.47.0
 - Package version 7.0.0

**PS :)**
Thanks a lot

**Comment by palypster** [comment]
But the error says the connection is refused and not that the table is missing. Are you sure / can you re-check?

Also, what happens when you change the order and first require craftable and AFTER that you require biscolab/laravel-recaptcha? Does it work that way?

**Comment by rstriquer** [comment]
In this case it will say connection refused for i have not configure .env yet. If you spare time to configure database it will start report missing table.

Yes, if you change orders it will result in the problem as well. I first noticed this in an existing craftable generated personal project i have.

I have no idea if is it a craftable issue at all, I actually think its not, but i guess this should be a very very common issue, therefor I guess it would be of some use reporting it in here.

**Comment by palypster** [comment]
Have you sorted out?

**Comment by rstriquer** [comment]
No. I just reported the bug and don't plan on making any corrections. I'm not using craftable at the moment.

**Comment by palypster** [comment]
I'm gonna close this for now until somebody else confirms this problem. Because we're not even sure if it's related to Craftable at all. But thank you!
