### ISSUE TITLE
The documentation does not describe the function of sorting posts of the demo site

### ISSUE THREAD

**Issue by veniaminryadnov** [BRACKETS-by-TRIAD/craftable#347]
The documentation does not describe the function of sorting posts of the demo site

How generate button Sort posts?

**Comment by palypster** [comment]
@RichardDominik we probably forgot to document this package, right?
https://github.com/BRACKETS-by-TRIAD/admin-sortable

**Comment by veniaminryadnov** [comment]
Will the integration process be documented in the next update and add this useful feature by default?

**Comment by RichardDominik** [comment]
We are still working on it.
