### ISSUE TITLE
The POST method is not supported for this route

### ISSUE THREAD

**Issue by sschuchlenz** [BRACKETS-by-TRIAD/craftable#349]
When I try to save an edited record, I get a small toast-style notification (red, bottom right) with the message that the POST route is not supported, only GET and HEAD.

**Comment by palypster** [comment]
What route? Can you provide a screenshot and the output of the:
`php artisan route:list`

**Comment by RickZurc** [comment]
Getting the same problem

**Comment by palypster** [comment]
Same question then

**Comment by RickZurc** [comment]
I resolved mine by deleting all cache based files. Check your git ignore put all of your cache based files in there.
