### ISSUE TITLE
How to add language for admin? 

### ISSUE THREAD

**Issue by ArsenBespalov** [BRACKETS-by-TRIAD/craftable#35]
I don't understand what to do. In docs I didn't find this. I want add language and then deploy this to the server.

Thanks.

**Comment by palypster** [comment]
Hey, sorry this is our bad, that it's missing in the docs. Fortunately, this should be really easy, you just need to update the config `translatable`, there is only one key - array of available locales. And that's it. Let me know, if it helped.
