### ISSUE TITLE
vue-multiselect doesn't fill with database value on edit

### ISSUE THREAD

**Issue by andsigno82** [BRACKETS-by-TRIAD/craftable#350]
Hi there, 
I'm just about to give up with Craftable because of this issue.
I created a model named "Client", which belongs to AdminUsers. My purpose is to extend the standard AdminUser behavior, adding some extra info like Date of birth, sex, city etc. without altering original AdminUser code.
I followed your guide step-by-step
https://getcraftable.com/docs/7.0/relations#one-to-many-example

but I'm about to definitely quit and throw everything away switching back to vanilla laravel when coming to vue-multiselect component, which is unnecessarily complicated.

Database layer is OK, in fact I had no problem saving updated data, but when coming to edit page, the value in DB isn't showing up in ANY WAY.
This is my vue component
`<multiselect v-model="form.admin_user" v-validate="'required'" :class="{'form-control-danger': errors.has('admin_user_id'), 'form-control-success': fields.admin_user_id && fields.admin_user_id.valid}" name="admin_user_id" id="admin_user_id" label="full_name" placeholder="Choose..." :options="admin_users" track-by="id">
</multiselect>`

this is my index, rendered full_name instead of id without problems
![immagine](https://user-images.githubusercontent.com/1968847/126076856-b4fbca29-035a-4c8d-abad-a0b771b14f8d.png)

and this is my edit, at page load. note that the database value doesn't show up at all
![immagine](https://user-images.githubusercontent.com/1968847/126076885-add805d9-c987-465f-8618-4f08359a823d.png)

even if values and full_name are everything at their places (as previously told, I save data with no hassle):
![immagine](https://user-images.githubusercontent.com/1968847/126076904-3aaf2de7-bf5c-4e29-8e1a-0d9fbf15b004.png)

![immagine](https://user-images.githubusercontent.com/1968847/126076924-11fe7031-b304-498a-85f8-360fb5f284f9.png)

how the vue-multiselect component is intended to "preselect" the DB value? I also examined form-elements.blade.php coming packed with AdminUsers with the vue-multiselect of roles 
`<div class="form-group row align-items-center" :class="{'has-danger': errors.has('roles'), 'has-success': fields.roles && fields.roles.valid }"><label for="roles" class="col-form-label text-md-right" :class="isFormLocalized ? 'col-md-4' : 'col-md-3'">{{ trans('admin.admin-user.columns.roles') }}</label>
    <div :class="isFormLocalized ? 'col-md-4' : 'col-md-9 col-xl-7'"><multiselect v-model="form.roles" placeholder="{{ trans('brackets/admin-ui::admin.forms.select_options') }}" label="name" track-by="id" :options="{{ $roles->toJson() }}" :multiple="true" open-direction="bottom"></multiselect><div v-if="errors.has('roles')" class="form-control-feedback form-text" v-cloak>@{{ errors.first('roles') }}</div></div></div>`

Seems I'm doing nothing wrong, I'm just about to throw everything away... please help me

**Comment by mikzero** [comment]
Hi, in the guide does not indicate the phase of Serializing To Arrays. You need to create a function in your model that displays the relationship table. [https://laravel.com/docs/8.x/eloquent-serialization#serializing-to-json](https://laravel.com/docs/8.x/eloquent-serialization#serializing-to-json)

**Comment by andsigno82** [comment]
> 
> 
> Hi, in the guide does not indicate the phase of Serializing To Arrays. You need to create a function in your model that displays the relationship table. https://laravel.com/docs/8.x/eloquent-serialization#serializing-to-json

Hi mikzero, i added that, and just forgot to mention it. but, I already did that in this form:
`:options={{ $admins->toJson() }}` 
straight into <multiselect> component instead of actual `:options="admin_users"` 
`<multiselect v-model="form.admin_user" v-validate="'required'" :class="{'form-control-danger': errors.has('admin_user_id'), 'form-control-success': fields.admin_user_id && fields.admin_user_id.valid}" name="admin_user_id" id="admin_user_id" label="full_name" placeholder="Scegli..." :options="{{$admins->toJson()}}" track-by="id">
</multiselect>`
but with no results at all
![immagine](https://user-images.githubusercontent.com/1968847/126159536-0ce774bc-350c-470d-a84f-18ff47435058.png)
I'm just feeling hopeless about it... :-(

**Comment by andsigno82** [comment]
> 
> 
> Hi, in the guide does not indicate the phase of Serializing To Arrays. You need to create a function in your model that displays the relationship table. https://laravel.com/docs/8.x/eloquent-serialization#serializing-to-json

I did in the edit blade template
![immagine](https://user-images.githubusercontent.com/1968847/126159759-a0207832-021c-4a63-9164-b834d067f521.png)

**Comment by RichardDominik** [comment]
Hello @andsigno82 

From the screenshots you provided is not clear how your form object in client-form looks like. So:

1. Please make sure you are loading your AdminUser relationship for the Client on the edit page. (https://laravel.com/docs/8.x/eloquent-relationships#eager-loading-by-default) or you can load relations in your controller method (using load function).

2. Please look if data prop passed into client-form is later converted into form object. The value in vue-multiselect is preselected automatically based on the value in form.admin_user.

Let me know if you need more help.

**Comment by andsigno82** [comment]
@RichardDominik Many many thanks for your suggestions! they pointed me at right direction, as I used load function in controller and immediately worked! Of course, thanks all other users too for your time and patience!

However, my 2 cents: I think that this thing should deserve a better explanation in documentation 
here https://getcraftable.com/docs/7.0/relations#one-to-many-example
or (better, imho) here 
https://getcraftable.com/docs/7.0/user-interface#multiselect

Thanks again! <3
