### ISSUE TITLE
Displaying a switch on a column which is not named 'Enabled' 

### ISSUE THREAD

**Issue by GabagoolOverHere** [BRACKETS-by-TRIAD/craftable#352]
Hello,

I have a boolean property that I want to replace in the index with a switch. Do I have to rename it enabled, activated or is_published or can I use another method?

Thanks!

**Comment by palypster** [comment]
You can name it as you wish, but you have to code the switch manually. If you name it one of enabled, activated or is_published, the generator will generate the code for you. You can try it very easily - just create some HelloWorld model and see how does it work (and you can copy&paste the code).

**Comment by GabagoolOverHere** [comment]
allrighty, thanks!
