### ISSUE TITLE
php artisan craftable:install ignores db table prefix in config/database.php 

### ISSUE THREAD

**Issue by cbka** [BRACKETS-by-TRIAD/craftable#353]
`Installing package brackets/admin-auth
Copied Directory [\vendor\brackets\admin-auth\install-stubs\resources\lang] To [\resources\lang\vendor\admin-auth]
Publishing complete.
Publishing complete.
Nothing to migrate.
Package brackets/admin-auth installed
Nothing to migrate.
Deleting previous files finished.

In SchemaException.php line 86:

  There is no column with name 'id' on table 'admin_users'.

`

in Installer as long as not 
`'prefix' => '',`
in config/database.php

**Comment by palypster** [comment]
duplicate to https://github.com/BRACKETS-by-TRIAD/craftable/issues/339

**Comment by palypster** [comment]
We are working on the roadmap for our next version of craftable, where we may involve this feature.
