### ISSUE TITLE
Cannot find module DescriptionDataMatcherRulePlugin

### ISSUE THREAD

**Issue by palypster** [BRACKETS-by-TRIAD/craftable#358]
Craftable installation fails with:
```
[webpack-cli] Error: Cannot find module 'webpack/lib/rules/DescriptionDataMatcherRulePlugin'
```

**Comment by palypster** [comment]
Originally reported from #357

**Comment by timoransky** [comment]
Apparently upgrading `vue-loader` should fix this so I might try it tomorrow. Although, I have no idea what caused this issue in a first place.

**Comment by RichardDominik** [comment]
The issue was fixed in the latest release of admin-ui https://github.com/BRACKETS-by-TRIAD/admin-ui/releases/tag/v4.3.2 . For existing projects please install the newest version of vue-loader.
