### ISSUE TITLE
vue-multiselect label filled with loaded relation object field

### ISSUE THREAD

**Issue by andsigno82** [BRACKETS-by-TRIAD/craftable#359]
I load a relation in multiselect-controlled field, and I need to use the field of inner object relation as label. as you can see in the screenshot, i can use the "first" level of data as label without problems (birthplace for e.g.), but i can't access the nested one (full_name for e.g.)
![immagine](https://user-images.githubusercontent.com/1968847/131053797-786cfd2f-9573-470c-9aa6-6294f029bbda.png)
I already tried 
`label="admin_user.full_name"` without success
![immagine](https://user-images.githubusercontent.com/1968847/131053985-0c378e5e-d2b7-4b62-9c70-ef4d8c356ea0.png)
while `label="birthplace"` works with no hassle.
![immagine](https://user-images.githubusercontent.com/1968847/131054157-63755d5f-b826-469a-b601-0845d4f45798.png)
can somebody point me in the right direction? :-)

**Comment by palypster** [comment]
Have you tried appending it for the serialization?

https://laravel.com/docs/8.x/eloquent-serialization#appending-values-to-json

**Comment by andsigno82** [comment]
> 
> 
> Have you tried appending it for the serialization?
> 
> https://laravel.com/docs/8.x/eloquent-serialization#appending-values-to-json

This is exaclty what I ended up doing. so I'm using the best practice to do this, right?

**Comment by andsigno82** [comment]
if so, however, my 2 cents is that I could however use the nested values already loaded in the multiselect

**Comment by palypster** [comment]
Yes I think this is a good approach. You don't have to append it EVERYTIME (in the model using `$appends`), you can also append it at runtime directly in the blade using:
https://laravel.com/docs/8.x/eloquent-serialization#appending-at-run-time
