### ISSUE TITLE
Dropdown items in sidebar

### ISSUE THREAD

**Issue by enriconardo** [BRACKETS-by-TRIAD/craftable#36]
How can I add a dropdown item (with subitems) in the sidebar? I've tried to add markup and styles as described in coreui theme website but it doesn't work.

**Comment by palypster** [comment]
We are using sligthly modified javascript of the coreui and that may be a reason, why it is not working (probably we are missing the part handling the dropdown menu in sidebar). You could try to look up missing part of the coreui's JS and copy to project's JS and it should start working. Sorry for complications.

**Comment by enriconardo** [comment]
I've imported the following files in _admin.js_:
- 'popper.js';
- 'bootstrap-sass/assets/javascripts/bootstrap/dropdown';
- '@coreui/coreui/js/dist/sidebar';

Now it works as expected. Thank you.

**Comment by sebastianjung** [comment]
Was having the same problem. 

Don't you think it should be in the main javascript files of craftable as it will be used quite a lot when building an admin panel or may i be wrong about this?

Greetings and thanks for this awesome admin panel builder :) love it

**Comment by palypster** [comment]
@sebastianjung thank you for your support. Check out new Craftable 3.0 coming this week - I think it will solve this issue forever ;)

**Comment by sebastianjung** [comment]
uuh im excited! Is there any chance we get to see an api generator? Would fit awesomely into the while clean design of this package 😊
