### ISSUE TITLE
Avatar Image not show

### ISSUE THREAD

**Issue by mjubouri** [BRACKETS-by-TRIAD/craftable#361]
**There is a problem the images not showing.** 

![Screen Shot 2021-09-21 at 12 28 22 PM](https://user-images.githubusercontent.com/16868721/134147031-2a2d4fa0-c9d8-4bbc-af56-c02a09d8f81c.png)

**Comment by ginkgomzd** [comment]
I'm seeing this on a fresh install (sail).
The request is missing the APP_PORT.

**Comment by RichardDominik** [comment]
Hello, I cannot reproduce the reported issue on the fresh Craftable project (using Sail). I also tried to upload new images. Does uploading images in your project work ?

**Comment by ginkgomzd** [comment]
yes, I can edit and upload a new profile picture. However, all requests for profile photos do not include the APP_PORT and so fail.

e.g. http://localhost/media/2/conversions/dkONsHLcNW8GYf6SJdUYoL5YY63ZDiwdJcsr2euw-thumb_150.jpg

when it should be
http://localhost:8080/media/2/conversions/dkONsHLcNW8GYf6SJdUYoL5YY63ZDiwdJcsr2euw-thumb_150.jpg

Is this maybe a laravel core issue?

**Comment by RichardDominik** [comment]
@ginkgomzd Please check if your `APP_URL` key in .env file contains value `http://localhost:8080`. If not, please provide this change and let me know if this solution solves your problem.

**Comment by ginkgomzd** [comment]
great, I updated my .env to
``` shell
APP_PORT=8080
APP_URL=http://localhost:${APP_PORT}
```

This still smells buggy to me, all other requests are generated correctly...

**Comment by mjubouri** [comment]
its solved thanks
