### ISSUE TITLE
Auto populated form fields not being saved! Autocomplete google not working either!

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#363]
Very weird behaviour!

1) Auto populated form fields are not being saved! 

2) Autocomplete google not working either!

I tried to use autocomplete google with my Laravel craftable project and I see that auto populated form fields are not being saved with the populated value and not saved or are emptied before saved! also every field that has been auto populated with class selector values or using document.getElementById are overwritten if I change something in other form field!

Any way to fix this behaviour?

I do appreciate a reply! here my 

Autocomplete google not saving data: 

![Screen Recording 2021-09-23 at 15 22 45](https://user-images.githubusercontent.com/11996194/134515366-0ce52270-9be4-48cd-bcee-41e0a1ed980c.gif)

Filling a form field with a click action same issue, field is not being saved and if I input an entry in another form field that field is emptied! but typing inside the form field then the data is correctly saved. It is the same issue with autocomplete google above I think! Any fix?

![Screen Recording 2021-09-23 at 15 21 48](https://user-images.githubusercontent.com/11996194/134516618-697f0cb5-1726-479b-af8a-fa956871758c.gif)

Here the code:

```
<script>
google.maps.event.addDomListener(window, 'load', initialize);

function initialize() {
        var input = document.getElementById('autocomplete');
        var autocomplete = new google.maps.places.Autocomplete(input);

        autocomplete.addListener('place_changed', function() {
            var place = autocomplete.getPlace();
            document.getElementById('address').value = place.name;
            document.getElementById('city').value = place.address_components[2]['long_name'];
            document.getElementById('postal_code').value = place.address_components[7]['long_name'];
            document.getElementById('country_name').value = place.address_components[6]['long_name'];
            document.getElementById('country_code').value = place.address_components[6]['short_name'];
            document.getElementById('latitude').value = place.geometry['location'].lat();
            document.getElementById('longitude').value = place.geometry['location'].lng();
        }); 
}
</script>

```

**Comment by palypster** [comment]
Hey, I'm afraid you are cannot use DOM directly. You have to use VueJS as long as the whole Craftable is built with VueJS. in this example you need to update the state of the form model using `data()` function.

**Comment by rapgithub** [comment]
is there an example of using vueJS with google autocomplete what works with craftable? I guess I have to do that in the Form.js right?

any sample with google autocomplete?
thanks

**Comment by rapgithub** [comment]
I found this! 
https://github.com/olefirenko/vue-google-autocomplete

thanks!
