### ISSUE TITLE
how to make conditions work inside index.blade with craftable?

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#364]
I have a column called comments_count that need to have a different color icon in the index.blade depending of the comments_count column amount!

let us say:

if comments_count is ==  0 then red color icon if > 0 then green color icon

I have tried to use the @if... without success! I need something like @if (item.comments_count == 0)...

anyway to make conditions work inside index.blade with craftable?

this code below does not work and I have not seen any sample online regarding this topic...

My not working code below:

```
@if (item.comments_count == 0)
 <a class="btn btn-sm btn-danger">@{{ item.comments_count }} comments</a></div>
@else
 <a class="btn btn-sm btn-green">@{{ item.comments_count }} comments</a></div>
@endif
```

Any tips appreciated!
Thanks!

**Comment by palypster** [comment]
I think you're missing basic concepts of blade vs vue and you are trying to mix them together in an inapropriate way.

The line starting with @ is the blade, but you cannot use it like that. You have to use vue:
https://vuejs.org/v2/guide/class-and-style.html

so something like
```
<a class="btn btn-sm" v-bind:class="{ 'btn-danger': item.comments_count == 0, 'btn-green': item.comments_count > 0 }">@{{ item.comments_count }} comments</a></div>
```

(I'm not sure if my code is actually correct, but take it as a direction you should navigate to)

**Comment by rapgithub** [comment]
thanks for the tips! I got it!
