### ISSUE TITLE
Installation fails on composer error

### ISSUE THREAD

**Issue by timoransky** [BRACKETS-by-TRIAD/craftable#366]
Installation of new project fails at following error:

> Crafting Craftable :) ...
> Using version ^7.0 for brackets/craftable
> ./composer.json has been updated
> Running composer update brackets/craftable
> Loading composer repositories with package information
> Updating dependencies
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - brackets/craftable 7.0.x-dev is an alias of brackets/craftable dev-master and thus requires it to be installed too.
>     - brackets/craftable[dev-master, 7.0.0] require brackets/media ^6.0 -> satisfiable by brackets/media[6.0.0, 6.0.x-dev (alias of dev-master)].
>     - brackets/media 6.0.x-dev is an alias of brackets/media dev-master and thus requires it to be installed too.
>     - brackets/media[dev-master, 6.0.0] require spatie/laravel-medialibrary ^9.0 -> satisfiable by spatie/laravel-medialibrary[9.0.0, ..., 9.8.1].
>     - spatie/laravel-medialibrary[9.7.0, ..., 9.8.1] require spatie/image ^1.4 -> satisfiable by spatie/image[1.4.0, ..., v1.x-dev].
>     - spatie/laravel-medialibrary[9.0.0, ..., 9.6.4] require spatie/image ^1.4.0 -> satisfiable by spatie/image[1.4.0, ..., v1.x-dev].
>     - spatie/image[1.8.0, ..., v1.x-dev] require spatie/image-optimizer ^1.1 -> satisfiable by spatie/image-optimizer[1.1.0, ..., 1.4.0].
>     - spatie/image[1.7.7, ..., 1.8.1] require spatie/image-optimizer ^1.0 -> satisfiable by spatie/image-optimizer[1.0.0, ..., 1.4.0].
>     - spatie/image-optimizer[1.0.0, ..., 1.1.4] require php ^7.0 -> your php version (8.0.8) does not satisfy that requirement.
>     - spatie/image[1.4.0, ..., 1.7.6] require php ^7.0 -> your php version (8.0.8) does not satisfy that requirement.
>     - spatie/image-optimizer[1.1.5, ..., 1.2.1] require php ^7.2 -> your php version (8.0.8) does not satisfy that requirement.
>     - spatie/image-optimizer[1.3.0, ..., 1.4.0] require psr/log ^1.0 -> found psr/log[1.0.0, ..., 1.1.4] but the package is fixed to 2.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
>     - Root composer.json requires brackets/craftable ^7.0 -> satisfiable by brackets/craftable[7.0.0, 7.0.x-dev (alias of dev-master)].
> 
> Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
> 
> Installation failed, reverting ./composer.json and ./composer.lock to their original content.
> 
>                                                                
>   There are no commands defined in the "craftable" namespace.  
>                                                                
> 
> Aborted.

Installing project manually running following commands: [manual instalation](https://getcraftable.com/docs/7.0/installation#manual-instalation) does not solve the issue.
I managed to work around this by running `sail composer require brackets/craftable -W`  

Apparently this happens because of laravel/framework requireing psr/log version `^v1.0 || ^v2.0` since version [v8.62.0](https://github.com/laravel/framework/commit/3806a98df2a8ed2dff17a2f7b5a85524f78c4e6d#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34) but [spatie/image-optimizer](https://github.com/spatie/image-optimizer/blob/master/composer.json) requiring only version  `^v1.0`.

**Comment by Fredy452** [comment]
I couldn't find any solutions
