### ISSUE TITLE
Problem with de default Password (TIP)

### ISSUE THREAD

**Issue by humbertodomizi** [BRACKETS-by-TRIAD/craftable#376]
It is a very common problem, I created a user through a seeder, I even assigned it a role, but the only user that has access as administrator is the user with ID 1, so we cannot enter once we do migrate: fresh.

When you reinstall craftable with craftable: install, it stops showing you the recently generated password.

In my opinion, the user should be created with a seeder that we can modify for each project, then we could create a repository of a personal project, which can be easily edited.

If you change the internal method, for a seeder, I think it would be easier.

Greetings

**Comment by humbertodomizi** [comment]
Maybe yes, if you ask me about how I would solve it, maybe you could use Spatie within the Craftable service, as a role tool, configure those roles, and configure the app / Providers / AuthServerProviders.php file so that when someone registers with the address "admin@admin.com" Have superadmin permissions. 

Then the user of the project, would deliver the work with that address as an administration account with the password that the developer chooses.

Here's the AuthServiceProvider.php config according to Spatie's documentation:

![image](https://user-images.githubusercontent.com/86383744/144935341-03915ada-8d86-469c-8384-c509e19d10dc.png)

**Comment by Pablo-hub44** [comment]
not works , i create , php artisan cratable:install blabla
and then it isnt the password
