### ISSUE TITLE
Change upload request timeout

### ISSUE THREAD

**Issue by gustmg** [BRACKETS-by-TRIAD/craftable#386]
Hello there! First of all, thank you for share this awesome package. I've been working with it since a couple of weeks and it's really helpful.

I'm having a trouble when I try to upload large files. I've tried with video files with ~15MB and works perfectly, but when I try to upload a very large video file (~700MB), the `upload` request always get cancelled after 30 seconds.

Is there a specific file where I can change or set that config? I'm assuming that the problem can be resolved by setting up some `timeout` param in the request handler, but I can't find in which file set the config.

Thanks in advance!

**Comment by hemal-digiflux** [comment]
Same issue
