### ISSUE TITLE
media-upload in a vue component

### ISSUE THREAD

**Issue by boehmli** [BRACKETS-by-TRIAD/craftable#39]
I use the media-upload component in a vue component as follows:
`media-upload(ref="image_uploader" collection="image" url="/upload" :max-number-of-files=1 accepted-file-types="image/*")`
I extended my Model by implementing  HasMediaCollections and HasMediaConversions as it is explained in the documentary. 
Image is saved in the storage folder, image Collection is send to the Models create method, no errors. but the Image dosnt get an entry in the media table.
Have I skipped something?

**Comment by boehmli** [comment]
solved with other media media libary

**Comment by palypster** [comment]
Sorry we were not helpful. Glad you solved it differently.
