### ISSUE TITLE
Install problem on existing project

### ISSUE THREAD

**Issue by robman70** [BRACKETS-by-TRIAD/craftable#397]
Hi,
I tried to add CRAFTABLE to an existing project pretty empty: just created using the 'laravel new' command.

When I try to add CRAFTABLE using 'composer require brackets/craftable', I see the error reported at the bottom.

Do I accept the downgrade of all these packages and also switch to php 7.x???

Can anyone help me?

Thanks,
Roberto

---------------------------------

Using version ^8.0 for brackets/craftable
./composer.json has been updated
Running composer update brackets/craftable
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpoffice/phpspreadsheet[1.18.0, ..., 1.22.0] require psr/simple-cache ^1.0 -> found psr/simple-cache[1.0.0, 1.0.1] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure 
you list it as an argument for the update command.
    - phpoffice/phpspreadsheet 1.23.0 requires psr/simple-cache ^1.0 || ^2.0 -> found psr/simple-cache[1.0.0, 1.0.1, 2.0.0, 2.x-dev] but the package is fixed to 3.0.0 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.
    - maatwebsite/excel[3.1.0, ..., 3.1.25] require php ^7.0 -> your php version (8.1.6) does not satisfy that requirement.
    - maatwebsite/excel[3.1.26, ..., 3.1.35] require illuminate/support 5.8.*|^6.0|^7.0|^8.0 -> found illuminate/support[v5.8.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but these were not loaded, likely because it conflicts with another require.
    - brackets/craftable[8.0.0, ..., 8.0.x-dev] require maatwebsite/excel ^3.1 -> satisfiable by maatwebsite/excel[3.1.0, ..., 3.1.x-dev].
    - maatwebsite/excel[3.1.36, ..., 3.1.x-dev] require phpoffice/phpspreadsheet ^1.18 -> satisfiable by phpoffice/phpspreadsheet[1.18.0, ..., 1.23.0].
    - Root composer.json requires brackets/craftable ^8.0 -> satisfiable by brackets/craftable[8.0.0, 8.0.x-dev].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
You can also try re-running composer require with an explicit version constraint, e.g. "composer require brackets/craftable:*" to figure out if any version is installable, or "composer require brackets/craftable:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by zulbil** [comment]
@robman70 I'm running to the same problem also. 
Try to run `composer update --with-all-dependencies `

**Comment by robman70** [comment]
@zulbil Thank you, I'll try
