### ISSUE TITLE
Empty Translations tab

### ISSUE THREAD

**Issue by NSpehler** [BRACKETS-by-TRIAD/craftable#40]
Hello there,

My translations are not showing anymore in the Translations tab. I'm not sure how to debug this, as there is not error in the console and in my logs.

I ran `php artisan admin-translations:scan-and-save` which returned `343 translations saved`. Also, all translations are correctly showing in my `translations` table.

Did you ever encounter this issue?

Let me know should you need any additional information.

Thanks for your help,
Nicolas

<img width="1117" alt="screenshot 2018-07-05 13 00 52" src="https://user-images.githubusercontent.com/379186/42319929-d78e985c-8053-11e8-8a29-542bf2bb31c9.png">

**Comment by palypster** [comment]
This is most likely a javascript error in your code that stops execution of the Vue component of a translations listing. Can you please double check there is no error in the console?

**Comment by NSpehler** [comment]
I just installed Vue Dev Tools, and here's the error that showed up:

`admin.js:6152 [Vue warn]: Unknown custom element: <translation-listing> - did you register the component correctly? For recursive components, make sure to provide the "name" option.` in `admin.js:6152`

Thanks for your help!

**Comment by matejminar** [comment]
Probably you have done this already, but just to make sure - does the problem still exists if you run 
`npm run dev`?

**Comment by NSpehler** [comment]
Yes, unfortunately 😞

**Comment by matejminar** [comment]
It looks like an issue with loading our Vue translation component from node_modules.
It is located in node_modules/craftable/assets/js/translation/Listing.js

Can you copy the code out of it and register it somewhere on your app to make sure it solves the problem?

**Comment by NSpehler** [comment]
That's exactly what I tried, in my `app.js` file without luck... (the relative path is correct, I triple-checked)

```
require('./bootstrap');

window.Vue = require('vue');

Vue.component('translation-listing', require('../../../node_modules/craftable/assets/js/translation/Listing.js'));

/**
 * Next, we will create a fresh Vue application instance and attach it to
 * the page. Then, you may begin adding components to this application
 * or customize the JavaScript scaffolding to fit your unique needs.
 */

const app = new Vue({
    el: '#app'
});

**Comment by matejminar** [comment]
app.js is not loaded in admin, it is meant to be used in public facing part of your app...

It is enough to load it like this in resources/assets/admin/js/admin.js:
`import { TranslationListing } from 'craftable';`

Altough it should be already loaded by default inside resources/assets/admin/js/app-components/bootstrap.js

**Comment by matejminar** [comment]
I wonder, does translation listing works if you make fresh craftable installation?

**Comment by NSpehler** [comment]
Yes it does when I create a new Craftable project, and I have no idea why...

Also tried `composer remove brackets/craftable` and then `composer require brackets/craftable` without luck. The same error keeps coming up:

<img width="908" alt="screenshot 2018-07-08 21 43 38" src="https://user-images.githubusercontent.com/379186/42423279-1fc3d456-82f8-11e8-95db-3e3fbd498d88.png">

**Comment by palypster** [comment]
If it is working on a fresh install, then it means the registration of the component is incorrect in your project. You can of course check your previous commits and find the last one it was still working and see what change is causing it. What do you say?

**Comment by NSpehler** [comment]
Good idea, only my `package.json` had changed, because I ran `npm upgrade`. And so a package was probably in conflict with Vue, which caused the error. Thanks a lot for your help!
