### ISSUE TITLE
Problem install  craftable - vite

### ISSUE THREAD

**Issue by hlo2109** [BRACKETS-by-TRIAD/craftable#400]
Hello, I have tried to start a new project but when I try to use it, it installs laravel with vite, I would like to know if there is any way to install laravel without this new plugin that does not allow the installation of this package to proceed.

Thank you very much in advance.

**Comment by palypster** [comment]
We'll dive into it and see what we can do.

**Comment by rapgithub** [comment]
thanks!

**Comment by rapgithub** [comment]
I hope to hear some good news and updates of craftable with vite.js soon in future! thanks

**Comment by stringsam** [comment]
This problem has been fixed in the last release of the admin-ui package -> https://github.com/BRACKETS-by-TRIAD/admin-ui/releases/tag/v4.4.1
