### ISSUE TITLE
ERROR : Can't install at all

### ISSUE THREAD

**Issue by DaBourz** [BRACKETS-by-TRIAD/craftable#404]
Tried Craftable, no way to install it, never works. PHP8 Laravel9 on 2 different machines, fresh install, fresh Laravel 9, tried with the installer, manual install, never worked, had a lot of different errors, from crash, hang, dependencies, sail not sail ? etc ???? did someone tested this ?

**Comment by palypster** [comment]
I'm sad for your poop experience with Craftable.

If you still want to give it a shot, please attach the error output (let's not mix all different approaches, choose one way and let's debug it).

**Comment by DaBourz** [comment]
![Annotation 2022-09-28 145541](https://user-images.githubusercontent.com/1420288/192784150-9d259d0f-6dc0-4ea6-a753-99edd4f1490c.png)

**Comment by DaBourz** [comment]
C:\xampp80\htdocs\my_project>craftable install --no-sail
Crafting Craftable :) ...
Aborted.

**Comment by DaBourz** [comment]
Yep, the manual install also fails... It doesn't support Laravel 8 anymore, supporting 9 apparatly broke the L8 version. So it is only Laravel 9 from now on. But manual install fails also....

**Comment by DaBourz** [comment]
composer create-project laravel/laravel example-app
cd example-app
composer require brackets/craftable

![Annotation 2022-09-28 150459](https://user-images.githubusercontent.com/1420288/192786309-f56baa32-22cf-42ae-833b-d8bae58316f4.png)

**Comment by DaBourz** [comment]
Looks like it's this :

https://pullanswer.com/questions/bug-compatible-error-with-psr-simplecache-cacheinterface-get

You probably need to change the MaatWebSite\Excel lib version.....

**Comment by stringsam** [comment]
This issue is connected with the maatwebsite/excel package. It requires psr/simple-cache 2.0, however, Laravel 9 installs the newest version. Therefore you have to downgrade psr/simple-cache manually before Craftable installation using `composer require psr/simple-cache:^2.0 maatwebsite/excel` .

**Comment by palypster** [comment]
Installing Craftable using standard way, via installer, should work and I can confirm it works on our environment (using Sail). So it has something to do with the platform (Windows) you're using. Try installing it on a linux server.

@DaBourz what @stringsam has said is true when installing it manual way (means first installing empty Laravel app and then requiring craftable) - you need to downgrade the psr/simple-cache before installing. Please try it and let us know.
