### ISSUE TITLE
error after php artisan craftable:install

### ISSUE THREAD

**Issue by kenmdavids** [BRACKETS-by-TRIAD/craftable#41]
craftable installs successfully but cant run any artisan commands, like config:cache, serve etc
it returns error
In ClassLoader.php line 444:

  include(C:\wamp\www\craft\vendor\composer/../../app/User.php): failed to open stream: No such file or directory

**Comment by palypster** [comment]
Craftable installation defaulty deletes the `app/User.php` model and generates new one in `app/Models/User.php`. I guess the error has something to do with it. Can you check?

**Comment by kenmdavids** [comment]
Yes, apparently that is what happens, do i need to copy `app/Models/User.php` back to `app/User.php`, when i do that it returns this 
`In ActivationListener.php line 21:

  class_implements(): Class App\User does not exist and could not be loaded`

**Comment by kenmdavids** [comment]
Hello @palypster , my issue has never been resolved, you assigned @dejwCake  but no reply yet. 
am running PHP 7.1.9
I have tried using both methods of installation
`craftable new my_project`
and
`composer require brackets/craftable
composer require --dev brackets/admin-generator`
`php artisan craftable:install`
but still i have this error
`C:\wamp\www\selfstudy\vendor\brackets\admin-auth\src\Listeners\ActivationListener.php
 
namespace Brackets\AdminAuth\Listeners;
 
use Brackets\AdminAuth\Facades\Activation;
use Brackets\AdminAuth\Services\ActivationService;
use Illuminate\Events\Dispatcher;
use Illuminate\Support\Facades\Config;
use Illuminate\Support\Facades\Schema;
 
class ActivationListener
{
    /**
     * Register the listeners for the subscriber.
     *
     * @param Illuminate\Events\Dispatcher|Dispatcher $events
     */
    public function subscribe(Dispatcher $events)
    {
        $userClass = Activation::broker()->getUserModelClass();
        $interfaces = class_implements($userClass);
        if(($interfaces && in_array(\Brackets\AdminAuth\Contracts\Auth\CanActivate::class, $interfaces))) {
            $events->listen(
                'eloquent.created: ' . $userClass,
                ActivationService::class
            );
        }
 
        //TODO listen on user edit and if email has changed, deactivate user and send email again
    }
}
 
Arguments
"class_implements(): Class App\User does not exist and could not be loaded"`
what should I do?
Do i change \vendor\composer\autoload_classmap?
what do i need to do
Any help will be appreciated

**Comment by palypster** [comment]
Hey @kenmdavids, sorry for late answer, we've been busy during this summer.

Can you really confirm, that this happens on a fresh craftable install using `craftable new my_project`? because I have thought before, it is happening on your existing project that you have added craftable into. That would make some sense. But if it is happening to you on a fresh install, then something's wrong, because we are not experiencing this issue. Can you please double-check?

**Comment by kenmdavids** [comment]
Hey @palypster , I truly understand, i tried both options i first installed it using `craftable new my_project` and it brought the `In ClassLoader.php line 444:` error, i tried it on existing projects using laravel 5.5 and laravel 5.6 respectively but the error still occured, i cleared cache, npm, reinstalled composer, changed my path to php7.1.9, but still got the same error.. I wonder what else am not doing right

**Comment by palypster** [comment]
Sorry @kenmdavids, I cannot reproduce it. `craftable new project_name` works just fine for me, I've just tested it, no errors. I'm afraid unless you will be even more explicit, or I cannot help :-(

**Comment by palypster** [comment]
We are working on a docker environment designed just for Craftable. I think it will cover things up. Stay tuned.

**Comment by kenmdavids** [comment]
@palypster Hello, I managed to install craftable successfully through this method  ```
craftable new --no-install project_name
php artisan craftable:init-env
php artisan craftable:install
npm install
npm run dev
```, 
the reply below was actually the issue, I put User.php in the app folder and I renamed the namespace

> Craftable installation defaulty deletes the `app/User.php` model and generates new one in `app/Models/User.php`. I guess the error has something to do with it. Can you check?

However now when i login through admin it returns unauthorized error
```
 public function handle($request, Closure $next)
    {
        if ( Auth::check() && Auth::user()->can('admin') )
        {
            return $next($request);
        }
 
        if (!Auth::check()) {
            return redirect()->guest('/admin/login');
        } else {
            throw new UnauthorizedException('Unathorized');
        }
    }
```
on` …\vendor\brackets\admin-auth\src\Http\Middleware\Admin.php:30`

**Comment by palypster** [comment]
Hey @kenmdavids, this week we have release Craftable v3. We have introduced completely separate model and guard for authentication inside Craftable. From now on Laravel's default frontend authentication (using default App/Model) is left intact.
