### ISSUE TITLE
14 Warnings about slash-div when runing npm

### ISSUE THREAD

**Issue by arieltoledo** [BRACKETS-by-TRIAD/craftable#414]
Hi Folks, whenver I execute npm run craftable-dev, 14 Warning shows ups in console with the same message:

```
_: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div(2em, 14) or calc(2em / 14)

More info and automated migrator: https://sass-lang.com/d/slash-div_
```
Any package I need to update ?

Thanks.

**Comment by timoransky** [comment]
Hi! Thank you for reporting this, we are aware of these warning but haven't got time to fix them up. There is nothing you need to do, everything should work as it is for now.
