### ISSUE TITLE
Not compatible with Laravel 9 (with Vite)

### ISSUE THREAD

**Issue by code-reflex** [BRACKETS-by-TRIAD/craftable#415]
Facing this issue with laravel 9 (which now uses vite):

Mix manifest not found at: /home/santosh/projects/laravel/test/public/mix-manifest.json (View: /home/santosh/projects/laravel/test/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php) (View: /home/santosh/projects/laravel/test/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php) (View: /home/santosh/projects/laravel/test/vendor/brackets/admin-ui/resources/views/admin/partials/main-styles.blade.php)

**Comment by ntsbstn** [comment]
Try this : 
`npm run craftable-prod`
