### ISSUE TITLE
WHAT IS THE PASSWORD???????

### ISSUE THREAD

**Issue by chordsandcodes** [BRACKETS-by-TRIAD/craftable#417]
I had 3 attempts to install craftable because the first 2 failed due to my .env file. I succeed on my 3rd attempt, the last printed text on my terminal was "craftable installed" but I CAN'T LOG IN administrator@brackets.sk and craftableinstalled or craftable installed. pleaseeeeeeeee. how is this so difficult??????

**Comment by timoransky** [comment]
Hi @chordsandcodes
please check `FillDefaultAdminUserAndPermissions` migration in your project, there should a generated password on the line 44.

**Comment by chordsandcodes** [comment]
thank you!
