### ISSUE TITLE
How to add admin user from cli?

### ISSUE THREAD

**Issue by ArsenBespalov** [BRACKETS-by-TRIAD/craftable#42]
Command `craftable:install` doesn't success complete, after deployment to production server, but admin user has been created, however generated password doesn't show in console, because `craftable:install` failed complete.

**Comment by palypster** [comment]
Please paste here full console output of `craftable:install`

**Comment by palypster** [comment]
Anyway, check out the database migrations, there is one that is responsible for inserting default admin user and generated password is there in a plain-text form.

**Comment by ArsenBespalov** [comment]
![screen shot 2018-07-20 at 15 48 05](https://user-images.githubusercontent.com/929121/42990112-5728f710-8c34-11e8-8080-3f3856e1c08f.png)

**Comment by ArsenBespalov** [comment]
Of course, I drop this database, but this is not correct it seems to me.

**Comment by palypster** [comment]
You've written that you get the error after deploying to production server. Note that you should not run `craftable:install` more than once per project. So if you run this on your local environemnt, commit and then publish the code to the production, you just need to do regular laravel stuff like: `composer install`, `artisan migrate`, ... Multiple `craftable:install` runs may cause these errors.
