### ISSUE TITLE
Problem installing Craftable Installer globally

### ISSUE THREAD

**Issue by DirkRobbertse313** [BRACKETS-by-TRIAD/craftable#422]
Hi Im treying to install Craftable Globally but im getting this error Cannot use brackets/craftable-installer's latest version v2.1.0 as it requires ext-zip, might be a problem on my side buit cant seem to find the issue. Andy advise ?

In PackageDiscoveryTrait.php line 317:

  Package brackets/craftable-installer has requirements incompatible with your PHP version, PHP extensions and Composer version:  
    - brackets/craftable-installer v2.1.0 requires ext-zip * but it is not present.

**Comment by palypster** [comment]
This has noting to with installing craftable, but with installing the craftable installer. You need to ensure you have all the requirements of the installer - i your case, you are missing the `zip` extenstion.

**Comment by palypster** [comment]
Note, that you don't need to use craftable installer at all. Feel free to install craftable manually (means without installer, if you are having a problem) using the [manual installation](https://getcraftable.com/docs/8.0/installation#manual-instalation).
