### ISSUE TITLE
TinyMCE editor

### ISSUE THREAD

**Issue by devilstars** [BRACKETS-by-TRIAD/craftable#43]
Hello!

Is it possible to use tinyMCE instead of current wysiwyg editor?

**Comment by palypster** [comment]
Sorry, currently we support only these two wysiwyg editors:

1. https://docs.getcraftable.com/v2/#/admin-ui?id=wysiwyg
2. https://docs.getcraftable.com/v2/#/admin-ui?id=media-wysiwyg

We are not planning to add support for TinyMCE at the moment.
