### ISSUE TITLE
Keep having SQLSTATE[42S02]: Base table or view not found: 1146 Table *.translation doesn't exist 

### ISSUE THREAD

**Issue by raymondugv** [BRACKETS-by-TRIAD/craftable#45]
Hi there, I just keep having this ERROR message when trying to access localhost/admin/login

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'kienhoanh_cp.translations' doesn't exist (SQL: select * from `translations` where `namespace` = brackets/admin-auth and `group` = admin and `translations`.`deleted_at` is null) (View: D:\For GIT\kienhoanh-cp\vendor\brackets\admin-auth\resources\views\admin\auth\login.blade.php)

Then I tend to create Translation table, but I don't know how many column is it!?.

Please help me.

Here some images about my case
![image](https://user-images.githubusercontent.com/21214764/44379441-21454080-a530-11e8-8bc2-45e9c4c724c5.png)

there is no table called translation on migration folder
![image](https://user-images.githubusercontent.com/21214764/44379483-58b3ed00-a530-11e8-8afc-1f38ac42d72b.png)

**Comment by palypster** [comment]
Craftable installation must have failed. Can you please provide whole output of `craftable new`?

**Comment by palypster** [comment]
I assume, you maybe did not install it correctly,. You have to create an empty database before running `craftable new` command. The command will ask for a credentials into the database. We have just updated the docs to be more explicit about it.

**Comment by rasimaliyev** [comment]
The same issue. 
P.S. the database was empty

`SQLSTATE[HY000]: General error: 2036 (SQL: select * from `translations` where `namespace` = brackets/admin-auth and `group` = admin and `translations`.`deleted_at` is null) (View: /var/www/rasim/data/www/domain.com/acdjcdnchbsdjf/megacrud/vendor/brackets/admin-auth/resources/views/admin/auth/login.blade.php)`

**Comment by ighmouraceneb** [comment]
I have the same issue. 
someone has the solution.

Facade\Ignition\Exceptions\ViewException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'laravel.translations' doesn't exist (SQL: select * from `translations` where `namespace` = * and `group` = * and `translations`.`deleted_at` is null) (View: C:\laragon\www\my_craftable\vendor\brackets\admin-auth\resources\views\admin\auth\login.blade.php)

**Comment by palypster** [comment]
Guys, try to follow steps here and let me know if it helped:
https://github.com/BRACKETS-by-TRIAD/craftable/issues/145

**Comment by djpolmd** [comment]
Hello all, 
  I have the same Issue
My new laravel project, on initializing with the composer, has failed after craftable install.
My os is Ubuntu  18 LTE,  and the composer has: 
 "require": {
        "php": "^7.2",
        "brackets/craftable": "^5.0",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.2",
        "laravel/tinker": "^1.0"
    }, 
after install and npm run,  call Once installed, navigate my browser to "/admin/login" I'v got : 

Facade\Ignition\Exceptions\ViewException
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'base_one.translations' doesn't exist (SQL: select * from `translations` where `namespace` = * and `group` = * and `translations`.`deleted_at` is null) (View: /home/sammy/rentacot_new/vendor/brackets/admin-auth/resources/views/admin/auth/login.blade.php)

**Comment by nayi10** [comment]
I had the same issue. I had to manually run `php artisan admin-translations:install` for the problem to solve.

**Comment by bibhorbaral** [comment]
Manually running php artisan admin-translations:install worked for me as well.

**Comment by lucemio** [comment]
I also get this kind of error. 

Base table or view not found: 1146 Table 'test.translations' doesn't exist (SQL: select * from `translations` where `key` LIKE *::*.% and exists (select * from `translation_translations` where `translations`.`id` = `translation_translations`.`translation_id` and `locale` = en)

I run the php artisan admin-translations:install but has error "There are no commands defined in the "admin-translations" namespace."

any help is appreciated.

**Comment by hillaryomondi** [comment]
I solved the error by including the --no-install command as follows:

 composer require --dev brackets/admin-generator  --no-install

**Comment by cbka** [comment]
> I had the same issue. I had to manually run `php artisan admin-translations:install` for the problem to solve.

you should add this to your docs... #

**Comment by wemo2022** [comment]
Total BS ..2 hrs of google and forums to get past 4 separate install errors of witch each took a "workaround" from another forum contributor only to be stood up at the login with no way to regen the password  ...total waste

**Comment by palypster** [comment]
Sorry, to hear that. Password is printed during installation (of course, if it fails, then probably it is not :( ). BUT! the admin password is also generated into one of the migrations files, so you can easily copy it.

About the problems with the installation - we didn't experience the problems with the installation, it was always working for us. If you had trouble AND managed to overcome them, we (and others) would be very thankful if you could share the knowledge. We would be happy to publish it in some FAQ section, with you mentioning it.

Cheers
Pali
