### ISSUE TITLE
pgsql check missed in ModifyUsersTable@down 

### ISSUE THREAD

**Issue by UksusoFF** [BRACKETS-by-TRIAD/craftable#46]
I'm getting this error when ```php artisan migrate:refresh```
``` 
SQLSTATE[42000]: Syntax error or access violation: 1091 Can't DROP 'users_email_null_deleted_at'; check that column/key exists (SQL: alter table `users` drop index `users_email_null_deleted_at`)  
```

**Comment by palypster** [comment]
We will check it out soon. But until, as a work-around, you can always use `artisan migrate:fresh` instead, which should do the trick.

**Comment by palypster** [comment]
@UksusoFF did it help?

**Comment by UksusoFF** [comment]
@palypster Yep. But I mean that we need same check in rollback: https://github.com/BRACKETS-by-TRIAD/admin-auth/blob/master/install-stubs/database/migrations/modify_users_table.php#L57

**Comment by palypster** [comment]
Perfect, you saved us some time. We'll fix that soon.

**Comment by DrzikFilip** [comment]
This one was fixed on Dec 10, 2018 in admin-auth.

**Comment by UksusoFF** [comment]
https://github.com/BRACKETS-by-TRIAD/admin-auth/commit/0e1eb924c42c7bae3c503571fd31a63889cb046b
