### ISSUE TITLE
Feature Request:  Generate Repository Classes

### ISSUE THREAD

**Issue by eddielee394** [BRACKETS-by-TRIAD/craftable#48]
Would be nice to be able to use the generator to also optionally generate repository & interface classes for a model.

**Comment by palypster** [comment]
We were considering that, but we have decided not to force using any patterns. So this is by design. Maybe in the future releases we will reconsider this.

**Comment by WrongWay** [comment]
Maybe creation of generators? :)

**Comment by palypster** [comment]
Sorry, it looks this is not the pattern we would like to support in the near future.
