### ISSUE TITLE
Media uploader with PDF

### ISSUE THREAD

**Issue by miquelangeld** [BRACKETS-by-TRIAD/craftable#51]
Hi and thanks in advance, I created a model with a collection to store pdf files

```
        $this->addMediaCollection('public_attachments')
            ->accepts('pdf/*');
```
In the uploader I can see  that the acceptedFiletypes variable in vue is "pdf/*"
But when I select the pdf file the uploader warns me "you can't upload files of this type"

Thanks.

**Comment by palypster** [comment]
I think you have to use standard MIME types, so for PDF it's `application/pdf`. Can try out?

**Comment by miquelangeld** [comment]
Hi! Using the MIME type works perfectly. Thanks and sorry for the delay.
