### ISSUE TITLE
Routes not working when installation is in sub folder

### ISSUE THREAD

**Issue by FreddyCrugger** [BRACKETS-by-TRIAD/craftable#52]
Hello,

I have installed correctly Craftable (Installer 1.0.9) in a sub folder as:
https://mywebsite.com/management/

The commands(I am on windows 10) were:
Create database and save details
```
composer global require "brackets/craftable-installer"
craftable new --no-install project_name
php artisan craftable:init-env
php artisan craftable:install
npm install
npm run dev
```

Datatabase and .ENV have both been set up. I added the APP_URL as:
`https://mywebsite.com/management/`

Now when I try to go to:
`https://mywebsite.com/management/admin/login`

I get the page error:
```
Not Found
The requested URL /management/admin/login was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
```

Any idea what I have to do to get it to work?

Thank you,

**Comment by palypster** [comment]
What do you get when you hit `https://mywebsite.com/management` ?

**Comment by FreddyCrugger** [comment]
Sorry I have now moved to voyager, I was experiencing too many issues with your script sorry.

**Comment by palypster** [comment]
It's okay, no prob. I was just checking, if it was even an Craftable issue or it was that your web server was misconfigured.

**Comment by FreddyCrugger** [comment]
I have never worked out what caused the issue to be honest, spent all night last night on this without luck :-(

Thanks again for your great support and good luck with your product, it seems really promising.
