### ISSUE TITLE
Generated table default sort

### ISSUE THREAD

**Issue by Akiciel** [BRACKETS-by-TRIAD/craftable#53]
can i change default sort key, direction? cant find that with opened manual

**Comment by palypster** [comment]
You mean in AdminListing?

**Comment by elshobokshy** [comment]
@palypster is this still not possible 2 years later? I want to make the default sort by `published_at` field

**Comment by elshobokshy** [comment]
So I had to update the package to get what I need. Can't you guys add this to the current code? 

I did this : 

```
$data = AdminListing::create(Topics::class)
->processRequestAndGet(
    $request, 
    ['id', 'title', 'published_at', 'enabled', 'position', 'admin_user_id'],
    ['id', 'title', 'wysiwyg'],
    function ($query) use ($request) {}, 
    null,
    ['orderBy'=>'published_at', 'orderDirection'=>'desc'] <---- Added a 6th param containing the information I need to sort by
);
```

And in the admin listing class where `processRequestAndGet` exists : 

```
public function processRequestAndGet(Request $request, array $columns = ['*'], $searchIn = null, callable $modifyQuery = null, $locale = null, $options = [])
{
    // If the options array is filled we use the information coming from it, else we use the default values
    !isset($options['orderBy']) ? $orderBy = $this->model->getKeyName() : $orderBy = $options['orderBy'];
    !isset($options['orderDirection']) ? $orderDirection = 'asc' : $orderDirection = $options['orderDirection'];
    // process all the basic stuff
    $this->attachOrdering($request->input('orderBy', $orderBy), $request->input('orderDirection', $orderDirection))
        ->attachSearch($request->input('search', null), $searchIn);
}
```

I'm sure there's a better way to do this so we'd not modify the package by itself, you can extend the class or something, but I exported the whole project outside vendor so this does the trick for me.

**Comment by diegodeluca** [comment]
It's still not working

**Comment by palypster** [comment]
Guys, please read this comment:
https://github.com/BRACKETS-by-TRIAD/craftable/issues/416#issuecomment-1407459455
forget about the _processRequestAndGet_ method, it is really just a shortcut that not have to be used in all cases.

**Comment by diegodeluca** [comment]
Don't know where is my fault but it doesn't work.
