### ISSUE TITLE
Broken installation after #4

### ISSUE THREAD

**Issue by palypster** [BRACKETS-by-TRIAD/craftable#6]
This breaks installation
https://github.com/BRACKETS-by-TRIAD/craftable/pull/4/files

because .env variables does not reload after the change. `cache:clear` may fix the problem. If not, then we must manually update the config (not in file, just in memory, for the current installation run).

**Comment by dejwCake** [comment]
This issue is fixed in latest releases of packages craftable-installer and craftable.
