### ISSUE TITLE
Wysiwyg insert image options do not work

### ISSUE THREAD

**Issue by JoshKisb** [BRACKETS-by-TRIAD/craftable#60]
Created a fresh project using craftable installer v1.0.9 
Craftable version: 1.2.8

The insert image options does not insert any images into the wysiwyg. Tried insert image, upload and base64. For upload i see the image is uploaded to the server but it is not shown in the wysiwyg
The dialog simply slides away and it is done with nothing shown
i believe this is a bug

**Comment by JoshKisb** [comment]
Appears to be a trumbowyg issue. will just replace it with tinymce

**Comment by pathardepavan** [comment]
I am facing the same issue..Is there any solution ?
