### ISSUE TITLE
Include basic UI for permission and role?

### ISSUE THREAD

**Issue by Trexology** [BRACKETS-by-TRIAD/craftable#64]
Not really an issue, is more of a feature request? It will be good to include a Simple UI to manage roles and permission in this package.

**Comment by palypster** [comment]
Hey @Trexology, thanks for your proposal. I have good news for you - this is already on our roadmap and we have already started to work on it. We plan to release Craftable v3.0 that would include this feature approx. in January 2019.

**Comment by palypster** [comment]
If you would like to get ocasional email about our ongoing work and our plans, signup here https://www.getcraftable.com/

We send no more than 1 newsletter per month or two.

**Comment by umangapathak999** [comment]
php artisan admin:generate permissions
php artisan admin:generate roles

Am stucked on generation of role_has_permissions for not having big increment id. Would help a lot if this gets added as it would provide complete roles and permissions management.

**Comment by Margeth** [comment]
> 

I have the same issue, did you found a solution for it?
