### ISSUE TITLE
A more flexible "Admin" Middleware?

### ISSUE THREAD

**Issue by Trexology** [BRACKETS-by-TRIAD/craftable#65]
The current Admin middleware is kinda too rigid. It only checks for a hardcoded "admin" permission. I did another Middleware which allows more flexible controlling of permission checking. 

> namespace App\Http\Middleware;
> 
> use Closure;
> use Illuminate\Auth\AuthenticationException;
> use Illuminate\Support\Facades\Auth;
> use Illuminate\Validation\UnauthorizedException;
> 
> class Permission
> {
>     /**
>      * Handle an incoming request.
>      *
>      * @param  \Illuminate\Http\Request  $request
>      * @param  \Closure  $next
>      * @return mixed
>      */
>     public function handle($request, Closure $next, $permission)
>     {
>       if (!Auth::check()) {
>           return redirect()->guest('/admin/login');
>       }
>       elseif (Auth::user()->can($permission)) {
>         return $next($request);
>       }
>       else {
>           abort(403, 'You are not authorized to access this page');
>           // throw new UnauthorizedException('Unauthorized');
>       }
>     }
> }

So with the above middleware (i named it as `permit`) you can protect routes like:

`Route::middleware(['permit:admin.post'])->group(function () { ....`

`Route::middleware(['permit:admin.location'])->group(function () { ....`

Maybe you guys can consider including this part as your default Middleware??
Btw I love this package, thank for creating this packages and releasing it for free. Cheers!

**Comment by palypster** [comment]
Hey @Trexology , we're very glad you like Craftable.

Thanks for your proposal. We are about to release `admin-auth` v2 that will introduce separate guards. We will consider your proposal and maybe we will add it to upcoming release. I can say, that our thinking was that all the authorization should be done in the dedicated Request class generated for every action. Your proposal kind of bypass this so I'm not sure if I like it. The `admin` permission was more like "If I have the access to the backoffice at all", but the concrete permission for concrete action should be checked in the Request. On the other hand I understand your proposal required less code to write and it might be cleaner in some cases. We will consider it.

**Comment by Trexology** [comment]
Actually, i just realize my middleware is not required at all. There is already a similar middleware included in laravel 5.7

'can' => \Illuminate\Auth\Middleware\Authorize::class,

[https://laravel.com/docs/5.7/authorization#via-middleware](url)
