### ISSUE TITLE
Assets not working in subfolder

### ISSUE THREAD

**Issue by mendizalea** [BRACKETS-by-TRIAD/craftable#66]
Hi, I install all ok but I have problems with assets.

I install in subfolder (www.example.com/craftable) and when I access to www.example.com/craftable/admin/login the js, css are linked to root directory:

Load from www.example.com/buid/admin/css/app.css and the right one should be www.example.com/craftable/buid/admin/css/app.css

**Comment by mendizalea** [comment]
Hello, thank you.

Yes but not. Before it did not show the icons and now yes, but it still does not load the css and js.

**After installation**
![01](https://user-images.githubusercontent.com/4532871/49282669-09b31780-f490-11e8-8555-14068fe485ec.JPG)

**After change main-styles.blade.php & main-bottom-scripts.blade.php**
```
<script src="{{ **asset**('/build/admin/js/admin.js') }}"></script>
<link href="{{ **asset**('/build/admin/css/app.css') }}" rel="stylesheet">
```
![02](https://user-images.githubusercontent.com/4532871/49282793-4e3eb300-f490-11e8-9a51-d0745058291c.JPG)

**After laravel mix change with the changes of the previous step**
`mix.setResourceRoot('/craftable/');`
![03](https://user-images.githubusercontent.com/4532871/49282854-73332600-f490-11e8-8bdd-d073b39d5b3d.JPG)

With the previous step but without changing the blade **template**
![01](https://user-images.githubusercontent.com/4532871/49283121-2b60ce80-f491-11e8-957c-cfa959f0f776.JPG)

**Comment by palypster** [comment]
I guess if you install any web project to a subfolder, you need to use <base> tag. Try to override Craftable's default layout markup and add this tag with your subfolder suffix and I think it's gonna work.
