### ISSUE TITLE
How to change "/admin" route name

### ISSUE THREAD

**Issue by fauzie** [BRACKETS-by-TRIAD/craftable#76]
Just trying craftable today,
Is there any short way to change `admin` slug name to any name?
The `/admin` is too predictable and not save for production site.

**Comment by palypster** [comment]
Sorry, this is not easily possible - unless you disable all the routes and then write down your own.

But if you need the administration not to be visible for outside world, then maybe you can disable it via `.htaccess` or you could completely separate an administration area as a separate application.
