### ISSUE TITLE
Cannot create property 'scope' on string

### ISSUE THREAD

**Issue by footniko** [BRACKETS-by-TRIAD/craftable#78]
It seems it doesn't recognize server's validation errors properly:
![image](https://user-images.githubusercontent.com/1759971/51549011-32450580-1e72-11e9-88a5-5e198120939d.png)
![image](https://user-images.githubusercontent.com/1759971/51549131-7801ce00-1e72-11e9-8e6f-ca3075dda105.png)
![image](https://user-images.githubusercontent.com/1759971/51549075-54d71e80-1e72-11e9-97c3-5acc237138e4.png)

Any thoughts?

**Comment by footniko** [comment]
The problem seems to be with the new versions of vee-validate. Installing **vee-validate** strictly with **2.0.9** version solved the issue.

**Comment by palypster** [comment]
@matejminar can you have a look? should we downgrade vee-validate or?

**Comment by matejminar** [comment]
Craftable v3 is out. We could lock the version of vee-validate on v2.

**Comment by matejminar** [comment]
We have locked the vee-validate version to 2.0.9 in Craftable v2, so everything should work now.

If you have the chance, we recommend you to upgrade to Craftable v3, where this is not an issue.
https://docs.getcraftable.com/v3/#/upgrade-guide

Thank you.
