### ISSUE TITLE
Errors after: npm run development

### ISSUE THREAD

**Issue by maxi032** [BRACKETS-by-TRIAD/craftable#8]
First, I want to thank you for this great admin app
I have npm vnode -v5.5.1
           node 6.10.3 on XAMPP

After I do: npm run development It processses 45% and then I get an error like
<pre>
<code>ERROR in ./resources/assets/admin/js/profile/edit-password/Form.js
Module not found: Error: Can't resolve '../components/Form/AppForm' in 'C:\xampp\htdocs\testingcraftable\resources\assets\admin\js\profile\edit-password'
resolve '../components/Form/AppForm' in 'C:\xampp\htdocs\testingcraftable\resources\assets\admin\js\profile\edit-password'
  using description file: C:\xampp\htdocs\testingcraftable\package.json (relative path: ./resources/assets/admin/js/profile/edit-password)
    Field 'browser' doesn't contain a valid alias configuration
</code>
</pre>
To enable more detailed error messagess add --display-error-details in package.json at the end of line 5

**Comment by Wipsly** [comment]
I have the same error.

**Comment by matejminar** [comment]
Hey, we have made a major overhaul of the frontend assets in the latest release and moved base components(along with other frontend stuff) into npm package. Please check it out and give us info if your problem still persists.

**Comment by maxi032** [comment]
Tryed again:
$ npm run development

> @ development C:\wamp64\www\blogcraftable
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress                                                                                                                                                                                                --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting ERROR  Failed to compile with 18 errors12:16:07                                                                                                                                                                                                                  
These dependencies were not found:

* craftable in ./resources/assets/admin/js/admin.js, ./resources/assets/admin/js                                                                                                                                                                                               /app-components/bootstrap.js and 3 others
* craftable/coreui in ./resources/assets/admin/js/admin.js
* flatpickr/dist/flatpickr.css in ./resources/assets/admin/js/admin.js
* moment in ./resources/assets/admin/js/bootstrap.js
* vee-validate in ./resources/assets/admin/js/admin.js
* vue-cookie in ./resources/assets/admin/js/admin.js
* vue-flatpickr-component in ./resources/assets/admin/js/admin.js
* vue-js-modal in ./resources/assets/admin/js/admin.js
* vue-multiselect in ./resources/assets/admin/js/admin.js
* vue-multiselect/dist/vue-multiselect.min.css in ./resources/assets/admin/js/ad                                                                                                                                                                                               min.js
* vue-notification in ./resources/assets/admin/js/admin.js
* vue-quill-editor in ./resources/assets/admin/js/admin.js

**Comment by matejminar** [comment]
Are you trying it on existing project, or have you run `craftable new myProjectName` today? Do you have craftable version 2.0?

**Comment by maxi032** [comment]
yes, I used craftable new project today... after that: npm install and: npm run development

**Comment by matejminar** [comment]
can you show me contents of your package.json and webpack.mix.js please?

**Comment by maxi032** [comment]
package.json:
`
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules\/webpack\/bin\/webpack.js --progress --hide-modules --config=node_modules\/laravel-mix\/setup\/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules\/webpack\/bin\/webpack.js --watch --progress --hide-modules --config=node_modules\/laravel-mix\/setup\/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules\/webpack-dev-server\/bin\/webpack-dev-server.js --inline --hot --config=node_modules\/laravel-mix\/setup\/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules\/webpack\/bin\/webpack.js --no-progress --hide-modules --config=node_modules\/laravel-mix\/setup\/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.17",
        "bootstrap-sass": "^3.3.7",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-mix": "^1.0",
        "lodash": "^4.17.4",
        "vue": "^2.5.7",
        "craftable": "^1.0.0"
    }
}`

**Comment by maxi032** [comment]
Update: I have decided to give it another try on Homestead and it worked so it doesn't work as expected on windows (wamp)
In my Homestead box I have node v8.0 and npm v5.0
Before getting it to work I had the following issue:
<pre>npm install </pre> could not find the lodash package so I deleted the folder node_modules entirely and then tried with yarn:
<pre>yarn install</pre>
Installation went without problems. Then: <pre>npm run dev</pre> compiled all the assets

**Comment by matejminar** [comment]
ok, nice! glad that you could make it work.. we will test it on some windows machines seeing it is a windows specific problem
