### ISSUE TITLE
Eloquent Samples any sample for media or standard?

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#80]
I installed every and I am trying to a create the CRUD for a media or standard db table and not working... I wonder if you have the samples of the migration DB  tables for media or standard crud available to check what I am doing wrong?
 
I see the eloquent samples of CRUD online in your demo... can you post this samples of migration tables as well?

thanks

**Comment by palypster** [comment]
Media are not in the migration table. There is a table media that saves the media for any eloquent models. I recommend you to check out our docs for media usage: https://docs.getcraftable.com/v3/#/media?id=basic-usage

**Comment by palypster** [comment]
We have published the code for the demo project here:
https://github.com/BRACKETS-by-TRIAD/craftable-demo

**Comment by palypster** [comment]
@rapgithub was it helpful?

**Comment by rapgithub** [comment]
yes thanks

**Comment by rapgithub** [comment]
I installed everything but I do not see a media sample...

is there any eloquent samples with media like in your demo to upload media files?


see screenshots:

<img width="760" alt="Screenshot 2019-03-13 at 00 30 33" src="https://user-images.githubusercontent.com/11996194/54243156-a1acac80-4527-11e9-9ebd-579751ae24ed.png">

<img width="997" alt="Screenshot 2019-03-13 at 00 30 42" src="https://user-images.githubusercontent.com/11996194/54243161-a5403380-4527-11e9-9243-77c9d897c2f1.png">

thanks
