### ISSUE TITLE
media-upload: need to add media upload to posts or articles... missing samples, explanation not clear :(

### ISSUE THREAD

**Issue by rapgithub** [BRACKETS-by-TRIAD/craftable#84]
I want to add media uploads to articles and posts but reading this, where I am supposed to put the code explained here below?

https://docs.getcraftable.com/v2/#/admin-ui?id=media-upload

1)
where am I supposed to add this code below, in which file and where? is it inside migrations when I create the table or inside the resources/admin/post for posts or resources/admin/article for articles ?

Sorry, but It is not clear for me this information.

```
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\Interfaces\HasMediaConversions;
use Spatie\MediaLibrary\Media;

use Brackets\Media\HasMedia\HasMediaCollections;
use Brackets\Media\HasMedia\HasMediaCollectionsTrait;
use Brackets\Media\HasMedia\HasMediaThumbsTrait;

class Post extends Model implements HasMediaCollections, HasMediaConversions {

    use HasMediaCollectionsTrait;
    use HasMediaThumbsTrait;

    public function registerMediaCollections()
    {
        $this->addMediaCollection('gallery')
             ->accepts('image/*');

        $this->addMediaCollection('secret_file')
             ->private()
             ->accepts('pdf/*');
    }

    public function registerMediaConversions(Media $media = null)
    {
        $this->autoRegisterThumb200();

        $this->addMediaConversion('detail_hd')
            ->width(1920)
            ->height(1080)
            ->performOnCollections('gallery');
    }
```

2)

then it says the explanation this below:

"Then you must define your media collections in your Form."

So I went here to resources/js/admin/app-components/Form/AppForm.js

Sorry again not clear where I have to add this code below:

```
import AppForm from '../app-components/Form/AppForm';

Vue.component('post-form', {
    mixins: [AppForm],
    data: function() {
        return {
            form: {
                //your regular form inputs
                title:  this.getLocalizedFormDefaults(),
                perex:  this.getLocalizedFormDefaults()
            },
            mediaCollections: ['gallery', 'secret_file']
        }
    }

});
```

3)
Then it continues 

"Now you can finally include our media uploader component and you're good to go."

where do I have to add the media uploader component, inside which file? 
index.blade.php edit.blade.php?

where do I need to put this code?

```
 @include('brackets/admin-ui::admin.includes.media-uploader', [
                            'mediaCollection' => app(App\Models\Post::class)->getMediaCollection('gallery'),
                            'label' => 'Gallery'
                        ])
```

4)
 Then it says

"Optionally, you can pass the 'media' parameter, to show already uploaded media (usually used within edit.blade.php)."

At least one clear thing here, it says that you have to add it inside edit.bade.php but when I added this code at the top of the file or inside a html tag I get some errors about function getMediaCollection...

so where am I supposed to add this code?

```
@include('brackets/admin-ui::admin.includes.media-uploader', [
                            'mediaCollection' => app(App\Models\Post::class)->getMediaCollection('gallery'),
                            'media' => $post->getThumbs200ForCollection('gallery'),
                            'label' => 'Gallery'
                        ])
```

the error:

<img width="1234" alt="Screenshot 2019-03-13 at 12 50 40" src="https://user-images.githubusercontent.com/11996194/54276855-9e98d700-458e-11e9-8fab-85bbfaf5bae9.png">

for simplicity, is there a full sample available of posts or articles with media upload to use to migrate and generate the crud? that will be helpful! 

thank you for helping with this!
regards

**Comment by palypster** [comment]
Hey, we're aware the docs are quite brief. That's why we are working on new documentation which will be ready in couple of weeks I hope. Till then you can try to look on our demo project and its source code:
https://demo.getcraftable.com/admin/login
https://github.com/BRACKETS-by-TRIAD/craftable-demo

**Comment by rapgithub** [comment]
thank I hope the docs will be soon online!! thanks for taking care!!

**Comment by rapgithub** [comment]
still not finding any sample for media upload for posts and etc...
can you please post the migration table structure you use for media upload for posts?
I receive a lot of error on my side...

thanks

**Comment by palypster** [comment]
I'm sorry we haven't published updated docs yet. We're currently working on it again (after some pause).

Let me navigate you - you should definitely investigate these files and I think you should be able to sort it all out then:
https://demo.getcraftable.com/admin/posts
https://github.com/BRACKETS-by-TRIAD/craftable-demo/blob/master/database/migrations/2019_01_30_084955_create_posts.php
https://github.com/BRACKETS-by-TRIAD/craftable-demo/blob/master/app/Models/Post.php
https://github.com/BRACKETS-by-TRIAD/craftable-demo/tree/master/resources/views/admin/post
https://github.com/BRACKETS-by-TRIAD/craftable-demo/blob/master/resources/js/admin/post/Form.js

**Comment by rapgithub** [comment]
thanks for the links I will investigate them now... but it will be nice to have a clear sample of the post with media upload because there is no sample for this in the demo, and also I have tried the documentation and ended up having lot of errors on my side, a clear sample of media upload for post will be helpful indeed! thanks!

**Comment by rapgithub** [comment]
thank you

**Comment by palypster** [comment]
Not sure what do you mean, there is sample media upload, look:
<img width="1357" alt="Screenshot 2019-06-13 at 09 57 36" src="https://user-images.githubusercontent.com/2362237/59414400-ba945a80-8dc1-11e9-88ea-e2fe49700b55.png">

**Comment by rapgithub** [comment]
In my case there is no samples of media upload below published at:

the only code that has the complete demos are online at demo.craftable.com the download demo does not have a sample of this only posts without media upload.

here screenshot of the POSTS...

<img width="1085" alt="Screenshot 2019-06-13 at 10 28 42" src="https://user-images.githubusercontent.com/11996194/59416638-13fe8880-8dc6-11e9-9763-219869c5f095.png">

**Comment by rapgithub** [comment]
where can I get the samples of the migrations tables and resources of your demo online? thanks

**Comment by rapgithub** [comment]
where is the complete demo online as shown in your screenshot with samples of media upload? I have download many times the demo online but does not have those samples included.
thanks

**Comment by palypster** [comment]
Sorry, I can't help, I'm not sure what is the question. The sources of the demo are here:
https://github.com/BRACKETS-by-TRIAD/craftable-demo

Were you able to sort it out in the meantime?
