### ISSUE TITLE
Datatables

### ISSUE THREAD

**Issue by kenmdavids** [BRACKETS-by-TRIAD/craftable#86]
If one's table has more than 16 columns, how can they make the datatable responsive, or how do I modify the datatable settings to hide some columns?
![trackerdatatable](https://user-images.githubusercontent.com/10721732/54760194-9ed54a00-4c00-11e9-9dcf-1e52bdbf91af.jpg)

Thanks

**Comment by palypster** [comment]
We usually delete the unnecessary columns and leave only really important ones. This simplifies the listing tables for admin users a lot.

To hide columns I would recommend check the CoreUI docs, where I hope you can find how to control different UI elements:
https://coreui.io/docs
