### ISSUE TITLE
Unique ID for edit

### ISSUE THREAD

**Issue by aptgorizia** [BRACKETS-by-TRIAD/craftable#87]
Hello, 
after successufl setup and migration and CRUD generation
ine the listing screen ( index view ) in  the edit item link there is no id for edit and it generate an error until i adde manually the variable ID in the url in view

so the generated Link is : 

`<a class="btn btn-sm btn-spinner btn-info" :href="item.resource_url + '/edit'" title="{{ trans('brackets/admin-ui::admin.btn.edit') }}" role="button"><i class="fa fa-edit"></i></a>`

i change it manually to : 
`<a class="btn btn-sm btn-spinner btn-info" :href="item.resource_url **+ '/' +item.ID +**  '/edit'" title="{{ trans('brackets/admin-ui::admin.btn.edit') }}" role="button"><i class="fa fa-edit"></i></a>`
                                                      

Same issue in Deleting action

**Comment by aptgorizia** [comment]
Update  : the issue was the name of column it must be id not ID 
to be considered as unique primary the name must bi id 
thanks

**Comment by palypster** [comment]
ID should be already part of the `item.resource_url`. Maybe there is something broken in your Model code? It's working for me on demo project, i.e.:
https://github.com/BRACKETS-by-TRIAD/craftable-demo/blob/master/app/Models/Article.php

What is your model returning in `getResourceUrlAttribute()` method?

**Comment by aptgorizia** [comment]
sorry it was cuz i didn't name the unique field id it was named ID ( uppercase )
