### ISSUE TITLE
upload bug

### ISSUE THREAD

**Issue by aptgorizia** [BRACKETS-by-TRIAD/craftable#89]
Hello i follow the exampe for post i define a field with upload option

but i get only an empty field

 where i can't drop files and i  can't see the cloud icon

![image](https://user-images.githubusercontent.com/31996545/54885417-c8e27280-4e73-11e9-9513-0a399e3e4b7b.png)

second issue, how can i change upload folder to definer my own folder not the media folder

**Comment by aptgorizia** [comment]
i got an error on my console 

[Vue warn]: Error in mounted hook: "Error: No URL provided."

**Comment by kolinko-ant** [comment]
I have the same issue. How to solve this error?

**Comment by kolinko-ant** [comment]
I solved it. For me the reason was that I also had "logo" column in table. But as I understand now all media files are stored in separate table and they should not be part of your main entity table.

Great product by the way!
