### ISSUE TITLE
Problem with the date

### ISSUE THREAD

**Issue by hotgeart** [BRACKETS-by-TRIAD/craftable#90]
When I tried the example on my local I've a problem with date-fns: 

    admin.js:96300 [Vue warn]: Error in v-on handler: "RangeError: `options.awareOfUnicodeTokens` must be set to `true` to use `YYYY` token; see: https://git.io/fxCyr"

    found in

    ---> <NewsForm>
        <Root>
    warn @ admin.js:96300
    logError @ admin.js:97559
    globalHandleError @ admin.js:97554
    handleError @ admin.js:97514
    invokeWithErrorHandling @ admin.js:97537
    invoker @ admin.js:97854
    original._wrapper @ admin.js:103207
    admin.js:97563 RangeError: `options.awareOfUnicodeTokens` must be set to `true` to use `YYYY` token; see: https://git.io/fxCyr
        at throwProtectedError (admin.js:89448)
        at parse (admin.js:91579)
        at parseDate$1 (admin.js:91707)
        at validate$9 (admin.js:92156)
        at Validator._test (admin.js:86578)
        at admin.js:86797
        at Array.some (<anonymous>)
        at Validator._validate (admin.js:86795)
        at admin.js:86345
        at Array.map (<anonymous>)

**Comment by dejwCake** [comment]
Hello, this issue is fixed in release v3.0.2 of brackets/admin-generator here: https://github.com/BRACKETS-by-TRIAD/admin-generator/releases/tag/v3.0.2, please update the package and regenerate resources.
