### ISSUE TITLE
Bug with media

### ISSUE THREAD

**Issue by pancevac** [BRACKETS-by-TRIAD/craftable#91]
Hi, I discover little bug in HasMediaCollectionsTrait in method processMedium on line 92. 
I modified uploader so that i can update custom properties for images from frontend. When i send newly or updated custom properties, i'm getting SQL error: unknown column name 'customPropeties'. 

I founded on line 92 `$medium->customProperties = $inputMedium['meta_data'];`
but it should be `$medium->custom_properties` (snake case).

**Comment by SamuelT-ST** [comment]
Hi, thank you for noticing us. The bug is now fixed in the new version of media library (v2.0.1).
