### ISSUE TITLE
Laravel 5.8?

### ISSUE THREAD

**Issue by Trexology** [BRACKETS-by-TRIAD/craftable#92]
Are you guys planning to upgrade the laravel core to 5.8?

**Comment by palypster** [comment]
Thanks, we have already started to work on it. Laravel 5.8 upgrade is not so easy as Laravel 5.7 because of some incompatible packages we use. I hope in next few weeks 5.8 support will be out.

**Comment by noonanwebgroup** [comment]
Awesome work on the package! Has there been any updates on Laravel 5.8 support?

**Comment by palypster** [comment]
Done
