### ISSUE TITLE
Route closure causes error with artisan route:cache command

### ISSUE THREAD

**Issue by ammonkc** [BRACKETS-by-TRIAD/craftable#95]
The route closure in the service provider causes an error when trying to cache the routes. the `artisan route:cache` command will not work if there are any route closures registered. Could these `/login` and `/register` routes be optional?

https://github.com/BRACKETS-by-TRIAD/admin-auth/blob/eab0722b0138bf27ccfab181a2c54c937fc1c9ff/src/AdminAuthServiceProvider.php#L86-L97

**Comment by palypster** [comment]
Fixed in v3.0.2
