### ISSUE TITLE
Redirect on login

### ISSUE THREAD

**Issue by vkrms** [BRACKETS-by-TRIAD/craftable#98]
I can't login on my live server. Every time I try to, I get redirected back to admin/login.
That's what I have in the console.
> admin.js:99259 Mixed Content: The page at 'https://yourdomain.com/admin/login' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://yourdomain.com/admin/login'. This endpoint should be made available over a secure connection.

I'll apprectiate any help.

**Comment by palypster** [comment]
Closing, unrelated to Craftable.
